version: '2'
run:
  go: '1.25'
  tests: true
linters:
  default: none
  enable:
    - errcheck
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused
  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - (*os.File).Close
        - (*database/sql.DB).Close
        - (*database/sql.Rows).Close
        - (*net/http.Response).Body.Close
        - (*github.com/redis/go-redis/v9.Client).Close
    gocyclo:
      min-complexity: 15
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
  exclusions:
    generated: lax
    paths:
      - di/wire_gen.go
      - _gorm_gen
      - infrastructure/database/gen_model
      - infrastructure/database/gen_query
      - mock
      - third_party
      - builtin
      - examples
    rules:
      - linters:
          - dupl
          - errcheck
          - gocyclo
          - gosec
        path: _test\.go
      - linters:
          - revive
        path: util/.*
        text: 'avoid meaningless package names'
      - linters:
          - errcheck
        text: "Error return value of `.*\\.Close` is not checked"
      - linters:
          - errcheck
        text: "Error return value of `.*\\.Write` is not checked"
      - linters:
          - errcheck
        text: "Error return value of `.*\\.Set` is not checked"
formatters:
  settings:
    goimports:
      local-prefixes: github.com/Code0716/stock-price-repository
