// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/Code0716/stock-price-repository/infrastructure/database/gen_model"
)

func newAppliedStockSplitsHistory(db *gorm.DB, opts ...gen.DOOption) appliedStockSplitsHistory {
	_appliedStockSplitsHistory := appliedStockSplitsHistory{}

	_appliedStockSplitsHistory.appliedStockSplitsHistoryDo.UseDB(db, opts...)
	_appliedStockSplitsHistory.appliedStockSplitsHistoryDo.UseModel(&gen_model.AppliedStockSplitsHistory{})

	tableName := _appliedStockSplitsHistory.appliedStockSplitsHistoryDo.TableName()
	_appliedStockSplitsHistory.ALL = field.NewAsterisk(tableName)
	_appliedStockSplitsHistory.ID = field.NewUint64(tableName, "id")
	_appliedStockSplitsHistory.Symbol = field.NewString(tableName, "symbol")
	_appliedStockSplitsHistory.SplitDate = field.NewTime(tableName, "split_date")
	_appliedStockSplitsHistory.Ratio = field.NewFloat64(tableName, "ratio")
	_appliedStockSplitsHistory.AppliedAt = field.NewTime(tableName, "applied_at")

	_appliedStockSplitsHistory.fillFieldMap()

	return _appliedStockSplitsHistory
}

type appliedStockSplitsHistory struct {
	appliedStockSplitsHistoryDo

	ALL       field.Asterisk
	ID        field.Uint64
	Symbol    field.String  // 銘柄コード
	SplitDate field.Time    // 分割実施日
	Ratio     field.Float64 // 分割比率
	AppliedAt field.Time    // 適用日時

	fieldMap map[string]field.Expr
}

func (a appliedStockSplitsHistory) Table(newTableName string) *appliedStockSplitsHistory {
	a.appliedStockSplitsHistoryDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a appliedStockSplitsHistory) As(alias string) *appliedStockSplitsHistory {
	a.appliedStockSplitsHistoryDo.DO = *(a.appliedStockSplitsHistoryDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *appliedStockSplitsHistory) updateTableName(table string) *appliedStockSplitsHistory {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint64(table, "id")
	a.Symbol = field.NewString(table, "symbol")
	a.SplitDate = field.NewTime(table, "split_date")
	a.Ratio = field.NewFloat64(table, "ratio")
	a.AppliedAt = field.NewTime(table, "applied_at")

	a.fillFieldMap()

	return a
}

func (a *appliedStockSplitsHistory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *appliedStockSplitsHistory) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 5)
	a.fieldMap["id"] = a.ID
	a.fieldMap["symbol"] = a.Symbol
	a.fieldMap["split_date"] = a.SplitDate
	a.fieldMap["ratio"] = a.Ratio
	a.fieldMap["applied_at"] = a.AppliedAt
}

func (a appliedStockSplitsHistory) clone(db *gorm.DB) appliedStockSplitsHistory {
	a.appliedStockSplitsHistoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a appliedStockSplitsHistory) replaceDB(db *gorm.DB) appliedStockSplitsHistory {
	a.appliedStockSplitsHistoryDo.ReplaceDB(db)
	return a
}

type appliedStockSplitsHistoryDo struct{ gen.DO }

type IAppliedStockSplitsHistoryDo interface {
	gen.SubQuery
	Debug() IAppliedStockSplitsHistoryDo
	WithContext(ctx context.Context) IAppliedStockSplitsHistoryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAppliedStockSplitsHistoryDo
	WriteDB() IAppliedStockSplitsHistoryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAppliedStockSplitsHistoryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAppliedStockSplitsHistoryDo
	Not(conds ...gen.Condition) IAppliedStockSplitsHistoryDo
	Or(conds ...gen.Condition) IAppliedStockSplitsHistoryDo
	Select(conds ...field.Expr) IAppliedStockSplitsHistoryDo
	Where(conds ...gen.Condition) IAppliedStockSplitsHistoryDo
	Order(conds ...field.Expr) IAppliedStockSplitsHistoryDo
	Distinct(cols ...field.Expr) IAppliedStockSplitsHistoryDo
	Omit(cols ...field.Expr) IAppliedStockSplitsHistoryDo
	Join(table schema.Tabler, on ...field.Expr) IAppliedStockSplitsHistoryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAppliedStockSplitsHistoryDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAppliedStockSplitsHistoryDo
	Group(cols ...field.Expr) IAppliedStockSplitsHistoryDo
	Having(conds ...gen.Condition) IAppliedStockSplitsHistoryDo
	Limit(limit int) IAppliedStockSplitsHistoryDo
	Offset(offset int) IAppliedStockSplitsHistoryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAppliedStockSplitsHistoryDo
	Unscoped() IAppliedStockSplitsHistoryDo
	Create(values ...*gen_model.AppliedStockSplitsHistory) error
	CreateInBatches(values []*gen_model.AppliedStockSplitsHistory, batchSize int) error
	Save(values ...*gen_model.AppliedStockSplitsHistory) error
	First() (*gen_model.AppliedStockSplitsHistory, error)
	Take() (*gen_model.AppliedStockSplitsHistory, error)
	Last() (*gen_model.AppliedStockSplitsHistory, error)
	Find() ([]*gen_model.AppliedStockSplitsHistory, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*gen_model.AppliedStockSplitsHistory, err error)
	FindInBatches(result *[]*gen_model.AppliedStockSplitsHistory, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*gen_model.AppliedStockSplitsHistory) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAppliedStockSplitsHistoryDo
	Assign(attrs ...field.AssignExpr) IAppliedStockSplitsHistoryDo
	Joins(fields ...field.RelationField) IAppliedStockSplitsHistoryDo
	Preload(fields ...field.RelationField) IAppliedStockSplitsHistoryDo
	FirstOrInit() (*gen_model.AppliedStockSplitsHistory, error)
	FirstOrCreate() (*gen_model.AppliedStockSplitsHistory, error)
	FindByPage(offset int, limit int) (result []*gen_model.AppliedStockSplitsHistory, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAppliedStockSplitsHistoryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a appliedStockSplitsHistoryDo) Debug() IAppliedStockSplitsHistoryDo {
	return a.withDO(a.DO.Debug())
}

func (a appliedStockSplitsHistoryDo) WithContext(ctx context.Context) IAppliedStockSplitsHistoryDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a appliedStockSplitsHistoryDo) ReadDB() IAppliedStockSplitsHistoryDo {
	return a.Clauses(dbresolver.Read)
}

func (a appliedStockSplitsHistoryDo) WriteDB() IAppliedStockSplitsHistoryDo {
	return a.Clauses(dbresolver.Write)
}

func (a appliedStockSplitsHistoryDo) Session(config *gorm.Session) IAppliedStockSplitsHistoryDo {
	return a.withDO(a.DO.Session(config))
}

func (a appliedStockSplitsHistoryDo) Clauses(conds ...clause.Expression) IAppliedStockSplitsHistoryDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a appliedStockSplitsHistoryDo) Returning(value interface{}, columns ...string) IAppliedStockSplitsHistoryDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a appliedStockSplitsHistoryDo) Not(conds ...gen.Condition) IAppliedStockSplitsHistoryDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a appliedStockSplitsHistoryDo) Or(conds ...gen.Condition) IAppliedStockSplitsHistoryDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a appliedStockSplitsHistoryDo) Select(conds ...field.Expr) IAppliedStockSplitsHistoryDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a appliedStockSplitsHistoryDo) Where(conds ...gen.Condition) IAppliedStockSplitsHistoryDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a appliedStockSplitsHistoryDo) Order(conds ...field.Expr) IAppliedStockSplitsHistoryDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a appliedStockSplitsHistoryDo) Distinct(cols ...field.Expr) IAppliedStockSplitsHistoryDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a appliedStockSplitsHistoryDo) Omit(cols ...field.Expr) IAppliedStockSplitsHistoryDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a appliedStockSplitsHistoryDo) Join(table schema.Tabler, on ...field.Expr) IAppliedStockSplitsHistoryDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a appliedStockSplitsHistoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAppliedStockSplitsHistoryDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a appliedStockSplitsHistoryDo) RightJoin(table schema.Tabler, on ...field.Expr) IAppliedStockSplitsHistoryDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a appliedStockSplitsHistoryDo) Group(cols ...field.Expr) IAppliedStockSplitsHistoryDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a appliedStockSplitsHistoryDo) Having(conds ...gen.Condition) IAppliedStockSplitsHistoryDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a appliedStockSplitsHistoryDo) Limit(limit int) IAppliedStockSplitsHistoryDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a appliedStockSplitsHistoryDo) Offset(offset int) IAppliedStockSplitsHistoryDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a appliedStockSplitsHistoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAppliedStockSplitsHistoryDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a appliedStockSplitsHistoryDo) Unscoped() IAppliedStockSplitsHistoryDo {
	return a.withDO(a.DO.Unscoped())
}

func (a appliedStockSplitsHistoryDo) Create(values ...*gen_model.AppliedStockSplitsHistory) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a appliedStockSplitsHistoryDo) CreateInBatches(values []*gen_model.AppliedStockSplitsHistory, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a appliedStockSplitsHistoryDo) Save(values ...*gen_model.AppliedStockSplitsHistory) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a appliedStockSplitsHistoryDo) First() (*gen_model.AppliedStockSplitsHistory, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.AppliedStockSplitsHistory), nil
	}
}

func (a appliedStockSplitsHistoryDo) Take() (*gen_model.AppliedStockSplitsHistory, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.AppliedStockSplitsHistory), nil
	}
}

func (a appliedStockSplitsHistoryDo) Last() (*gen_model.AppliedStockSplitsHistory, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.AppliedStockSplitsHistory), nil
	}
}

func (a appliedStockSplitsHistoryDo) Find() ([]*gen_model.AppliedStockSplitsHistory, error) {
	result, err := a.DO.Find()
	return result.([]*gen_model.AppliedStockSplitsHistory), err
}

func (a appliedStockSplitsHistoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*gen_model.AppliedStockSplitsHistory, err error) {
	buf := make([]*gen_model.AppliedStockSplitsHistory, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a appliedStockSplitsHistoryDo) FindInBatches(result *[]*gen_model.AppliedStockSplitsHistory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a appliedStockSplitsHistoryDo) Attrs(attrs ...field.AssignExpr) IAppliedStockSplitsHistoryDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a appliedStockSplitsHistoryDo) Assign(attrs ...field.AssignExpr) IAppliedStockSplitsHistoryDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a appliedStockSplitsHistoryDo) Joins(fields ...field.RelationField) IAppliedStockSplitsHistoryDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a appliedStockSplitsHistoryDo) Preload(fields ...field.RelationField) IAppliedStockSplitsHistoryDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a appliedStockSplitsHistoryDo) FirstOrInit() (*gen_model.AppliedStockSplitsHistory, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.AppliedStockSplitsHistory), nil
	}
}

func (a appliedStockSplitsHistoryDo) FirstOrCreate() (*gen_model.AppliedStockSplitsHistory, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.AppliedStockSplitsHistory), nil
	}
}

func (a appliedStockSplitsHistoryDo) FindByPage(offset int, limit int) (result []*gen_model.AppliedStockSplitsHistory, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a appliedStockSplitsHistoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a appliedStockSplitsHistoryDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a appliedStockSplitsHistoryDo) Delete(models ...*gen_model.AppliedStockSplitsHistory) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *appliedStockSplitsHistoryDo) withDO(do gen.Dao) *appliedStockSplitsHistoryDo {
	a.DO = *do.(*gen.DO)
	return a
}
