// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/Code0716/stock-price-repository/infrastructure/database/gen_model"
)

func newAppliedStockConsolidationsHistory(db *gorm.DB, opts ...gen.DOOption) appliedStockConsolidationsHistory {
	_appliedStockConsolidationsHistory := appliedStockConsolidationsHistory{}

	_appliedStockConsolidationsHistory.appliedStockConsolidationsHistoryDo.UseDB(db, opts...)
	_appliedStockConsolidationsHistory.appliedStockConsolidationsHistoryDo.UseModel(&gen_model.AppliedStockConsolidationsHistory{})

	tableName := _appliedStockConsolidationsHistory.appliedStockConsolidationsHistoryDo.TableName()
	_appliedStockConsolidationsHistory.ALL = field.NewAsterisk(tableName)
	_appliedStockConsolidationsHistory.ID = field.NewUint64(tableName, "id")
	_appliedStockConsolidationsHistory.Symbol = field.NewString(tableName, "symbol")
	_appliedStockConsolidationsHistory.ConsolidationDate = field.NewTime(tableName, "consolidation_date")
	_appliedStockConsolidationsHistory.Ratio = field.NewFloat64(tableName, "ratio")
	_appliedStockConsolidationsHistory.AppliedAt = field.NewTime(tableName, "applied_at")

	_appliedStockConsolidationsHistory.fillFieldMap()

	return _appliedStockConsolidationsHistory
}

type appliedStockConsolidationsHistory struct {
	appliedStockConsolidationsHistoryDo

	ALL               field.Asterisk
	ID                field.Uint64
	Symbol            field.String  // 銘柄コード
	ConsolidationDate field.Time    // 併合実施日
	Ratio             field.Float64 // 併合比率（旧株数/新株数。例: 5株を1株に併合なら 5.0000）
	AppliedAt         field.Time    // 適用日時

	fieldMap map[string]field.Expr
}

func (a appliedStockConsolidationsHistory) Table(newTableName string) *appliedStockConsolidationsHistory {
	a.appliedStockConsolidationsHistoryDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a appliedStockConsolidationsHistory) As(alias string) *appliedStockConsolidationsHistory {
	a.appliedStockConsolidationsHistoryDo.DO = *(a.appliedStockConsolidationsHistoryDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *appliedStockConsolidationsHistory) updateTableName(table string) *appliedStockConsolidationsHistory {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint64(table, "id")
	a.Symbol = field.NewString(table, "symbol")
	a.ConsolidationDate = field.NewTime(table, "consolidation_date")
	a.Ratio = field.NewFloat64(table, "ratio")
	a.AppliedAt = field.NewTime(table, "applied_at")

	a.fillFieldMap()

	return a
}

func (a *appliedStockConsolidationsHistory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *appliedStockConsolidationsHistory) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 5)
	a.fieldMap["id"] = a.ID
	a.fieldMap["symbol"] = a.Symbol
	a.fieldMap["consolidation_date"] = a.ConsolidationDate
	a.fieldMap["ratio"] = a.Ratio
	a.fieldMap["applied_at"] = a.AppliedAt
}

func (a appliedStockConsolidationsHistory) clone(db *gorm.DB) appliedStockConsolidationsHistory {
	a.appliedStockConsolidationsHistoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a appliedStockConsolidationsHistory) replaceDB(db *gorm.DB) appliedStockConsolidationsHistory {
	a.appliedStockConsolidationsHistoryDo.ReplaceDB(db)
	return a
}

type appliedStockConsolidationsHistoryDo struct{ gen.DO }

type IAppliedStockConsolidationsHistoryDo interface {
	gen.SubQuery
	Debug() IAppliedStockConsolidationsHistoryDo
	WithContext(ctx context.Context) IAppliedStockConsolidationsHistoryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAppliedStockConsolidationsHistoryDo
	WriteDB() IAppliedStockConsolidationsHistoryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAppliedStockConsolidationsHistoryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAppliedStockConsolidationsHistoryDo
	Not(conds ...gen.Condition) IAppliedStockConsolidationsHistoryDo
	Or(conds ...gen.Condition) IAppliedStockConsolidationsHistoryDo
	Select(conds ...field.Expr) IAppliedStockConsolidationsHistoryDo
	Where(conds ...gen.Condition) IAppliedStockConsolidationsHistoryDo
	Order(conds ...field.Expr) IAppliedStockConsolidationsHistoryDo
	Distinct(cols ...field.Expr) IAppliedStockConsolidationsHistoryDo
	Omit(cols ...field.Expr) IAppliedStockConsolidationsHistoryDo
	Join(table schema.Tabler, on ...field.Expr) IAppliedStockConsolidationsHistoryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAppliedStockConsolidationsHistoryDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAppliedStockConsolidationsHistoryDo
	Group(cols ...field.Expr) IAppliedStockConsolidationsHistoryDo
	Having(conds ...gen.Condition) IAppliedStockConsolidationsHistoryDo
	Limit(limit int) IAppliedStockConsolidationsHistoryDo
	Offset(offset int) IAppliedStockConsolidationsHistoryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAppliedStockConsolidationsHistoryDo
	Unscoped() IAppliedStockConsolidationsHistoryDo
	Create(values ...*gen_model.AppliedStockConsolidationsHistory) error
	CreateInBatches(values []*gen_model.AppliedStockConsolidationsHistory, batchSize int) error
	Save(values ...*gen_model.AppliedStockConsolidationsHistory) error
	First() (*gen_model.AppliedStockConsolidationsHistory, error)
	Take() (*gen_model.AppliedStockConsolidationsHistory, error)
	Last() (*gen_model.AppliedStockConsolidationsHistory, error)
	Find() ([]*gen_model.AppliedStockConsolidationsHistory, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*gen_model.AppliedStockConsolidationsHistory, err error)
	FindInBatches(result *[]*gen_model.AppliedStockConsolidationsHistory, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*gen_model.AppliedStockConsolidationsHistory) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAppliedStockConsolidationsHistoryDo
	Assign(attrs ...field.AssignExpr) IAppliedStockConsolidationsHistoryDo
	Joins(fields ...field.RelationField) IAppliedStockConsolidationsHistoryDo
	Preload(fields ...field.RelationField) IAppliedStockConsolidationsHistoryDo
	FirstOrInit() (*gen_model.AppliedStockConsolidationsHistory, error)
	FirstOrCreate() (*gen_model.AppliedStockConsolidationsHistory, error)
	FindByPage(offset int, limit int) (result []*gen_model.AppliedStockConsolidationsHistory, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAppliedStockConsolidationsHistoryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a appliedStockConsolidationsHistoryDo) Debug() IAppliedStockConsolidationsHistoryDo {
	return a.withDO(a.DO.Debug())
}

func (a appliedStockConsolidationsHistoryDo) WithContext(ctx context.Context) IAppliedStockConsolidationsHistoryDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a appliedStockConsolidationsHistoryDo) ReadDB() IAppliedStockConsolidationsHistoryDo {
	return a.Clauses(dbresolver.Read)
}

func (a appliedStockConsolidationsHistoryDo) WriteDB() IAppliedStockConsolidationsHistoryDo {
	return a.Clauses(dbresolver.Write)
}

func (a appliedStockConsolidationsHistoryDo) Session(config *gorm.Session) IAppliedStockConsolidationsHistoryDo {
	return a.withDO(a.DO.Session(config))
}

func (a appliedStockConsolidationsHistoryDo) Clauses(conds ...clause.Expression) IAppliedStockConsolidationsHistoryDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a appliedStockConsolidationsHistoryDo) Returning(value interface{}, columns ...string) IAppliedStockConsolidationsHistoryDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a appliedStockConsolidationsHistoryDo) Not(conds ...gen.Condition) IAppliedStockConsolidationsHistoryDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a appliedStockConsolidationsHistoryDo) Or(conds ...gen.Condition) IAppliedStockConsolidationsHistoryDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a appliedStockConsolidationsHistoryDo) Select(conds ...field.Expr) IAppliedStockConsolidationsHistoryDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a appliedStockConsolidationsHistoryDo) Where(conds ...gen.Condition) IAppliedStockConsolidationsHistoryDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a appliedStockConsolidationsHistoryDo) Order(conds ...field.Expr) IAppliedStockConsolidationsHistoryDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a appliedStockConsolidationsHistoryDo) Distinct(cols ...field.Expr) IAppliedStockConsolidationsHistoryDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a appliedStockConsolidationsHistoryDo) Omit(cols ...field.Expr) IAppliedStockConsolidationsHistoryDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a appliedStockConsolidationsHistoryDo) Join(table schema.Tabler, on ...field.Expr) IAppliedStockConsolidationsHistoryDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a appliedStockConsolidationsHistoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAppliedStockConsolidationsHistoryDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a appliedStockConsolidationsHistoryDo) RightJoin(table schema.Tabler, on ...field.Expr) IAppliedStockConsolidationsHistoryDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a appliedStockConsolidationsHistoryDo) Group(cols ...field.Expr) IAppliedStockConsolidationsHistoryDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a appliedStockConsolidationsHistoryDo) Having(conds ...gen.Condition) IAppliedStockConsolidationsHistoryDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a appliedStockConsolidationsHistoryDo) Limit(limit int) IAppliedStockConsolidationsHistoryDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a appliedStockConsolidationsHistoryDo) Offset(offset int) IAppliedStockConsolidationsHistoryDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a appliedStockConsolidationsHistoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAppliedStockConsolidationsHistoryDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a appliedStockConsolidationsHistoryDo) Unscoped() IAppliedStockConsolidationsHistoryDo {
	return a.withDO(a.DO.Unscoped())
}

func (a appliedStockConsolidationsHistoryDo) Create(values ...*gen_model.AppliedStockConsolidationsHistory) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a appliedStockConsolidationsHistoryDo) CreateInBatches(values []*gen_model.AppliedStockConsolidationsHistory, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a appliedStockConsolidationsHistoryDo) Save(values ...*gen_model.AppliedStockConsolidationsHistory) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a appliedStockConsolidationsHistoryDo) First() (*gen_model.AppliedStockConsolidationsHistory, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.AppliedStockConsolidationsHistory), nil
	}
}

func (a appliedStockConsolidationsHistoryDo) Take() (*gen_model.AppliedStockConsolidationsHistory, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.AppliedStockConsolidationsHistory), nil
	}
}

func (a appliedStockConsolidationsHistoryDo) Last() (*gen_model.AppliedStockConsolidationsHistory, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.AppliedStockConsolidationsHistory), nil
	}
}

func (a appliedStockConsolidationsHistoryDo) Find() ([]*gen_model.AppliedStockConsolidationsHistory, error) {
	result, err := a.DO.Find()
	return result.([]*gen_model.AppliedStockConsolidationsHistory), err
}

func (a appliedStockConsolidationsHistoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*gen_model.AppliedStockConsolidationsHistory, err error) {
	buf := make([]*gen_model.AppliedStockConsolidationsHistory, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a appliedStockConsolidationsHistoryDo) FindInBatches(result *[]*gen_model.AppliedStockConsolidationsHistory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a appliedStockConsolidationsHistoryDo) Attrs(attrs ...field.AssignExpr) IAppliedStockConsolidationsHistoryDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a appliedStockConsolidationsHistoryDo) Assign(attrs ...field.AssignExpr) IAppliedStockConsolidationsHistoryDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a appliedStockConsolidationsHistoryDo) Joins(fields ...field.RelationField) IAppliedStockConsolidationsHistoryDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a appliedStockConsolidationsHistoryDo) Preload(fields ...field.RelationField) IAppliedStockConsolidationsHistoryDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a appliedStockConsolidationsHistoryDo) FirstOrInit() (*gen_model.AppliedStockConsolidationsHistory, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.AppliedStockConsolidationsHistory), nil
	}
}

func (a appliedStockConsolidationsHistoryDo) FirstOrCreate() (*gen_model.AppliedStockConsolidationsHistory, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.AppliedStockConsolidationsHistory), nil
	}
}

func (a appliedStockConsolidationsHistoryDo) FindByPage(offset int, limit int) (result []*gen_model.AppliedStockConsolidationsHistory, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a appliedStockConsolidationsHistoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a appliedStockConsolidationsHistoryDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a appliedStockConsolidationsHistoryDo) Delete(models ...*gen_model.AppliedStockConsolidationsHistory) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *appliedStockConsolidationsHistoryDo) withDO(do gen.Dao) *appliedStockConsolidationsHistoryDo {
	a.DO = *do.(*gen.DO)
	return a
}
