// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/Code0716/stock-price-repository/infrastructure/database/gen_model"
)

func newDaytradeExecution(db *gorm.DB, opts ...gen.DOOption) daytradeExecution {
	_daytradeExecution := daytradeExecution{}

	_daytradeExecution.daytradeExecutionDo.UseDB(db, opts...)
	_daytradeExecution.daytradeExecutionDo.UseModel(&gen_model.DaytradeExecution{})

	tableName := _daytradeExecution.daytradeExecutionDo.TableName()
	_daytradeExecution.ALL = field.NewAsterisk(tableName)
	_daytradeExecution.ID = field.NewUint64(tableName, "id")
	_daytradeExecution.ExecutedOn = field.NewTime(tableName, "executed_on")
	_daytradeExecution.TradeKind = field.NewString(tableName, "trade_kind")
	_daytradeExecution.MarginKind = field.NewString(tableName, "margin_kind")
	_daytradeExecution.TickerSymbol = field.NewString(tableName, "ticker_symbol")
	_daytradeExecution.BrandName = field.NewString(tableName, "brand_name")
	_daytradeExecution.Quantity = field.NewUint32(tableName, "quantity")
	_daytradeExecution.TradeAmount = field.NewInt64(tableName, "trade_amount")
	_daytradeExecution.UnitPrice = field.NewFloat64(tableName, "unit_price")
	_daytradeExecution.AverageCost = field.NewFloat64(tableName, "average_cost")
	_daytradeExecution.ProfitLoss = field.NewInt64(tableName, "profit_loss")
	_daytradeExecution.OccurrenceNo = field.NewUint32(tableName, "occurrence_no")
	_daytradeExecution.Source = field.NewString(tableName, "source")
	_daytradeExecution.CreatedAt = field.NewTime(tableName, "created_at")
	_daytradeExecution.UpdatedAt = field.NewTime(tableName, "updated_at")

	_daytradeExecution.fillFieldMap()

	return _daytradeExecution
}

type daytradeExecution struct {
	daytradeExecutionDo

	ALL          field.Asterisk
	ID           field.Uint64
	ExecutedOn   field.Time    // 約定日
	TradeKind    field.String  // 取引区分 (売建/買建/現物買付/現物売却 等)
	MarginKind   field.String  // 信用区分 (返済売/返済買/新規買/新規売/空)
	TickerSymbol field.String  // 銘柄コード (4桁)
	BrandName    field.String  // 銘柄名
	Quantity     field.Uint32  // 数量
	TradeAmount  field.Int64   // 約定代金 (円)
	UnitPrice    field.Float64 // 単価
	AverageCost  field.Float64 // 平均取得単価
	ProfitLoss   field.Int64   // 売買損益 (税引前・円)
	OccurrenceNo field.Uint32  // 同一自然キー内での出現順序 (0始まり)
	Source       field.String  // CSV 出力元
	CreatedAt    field.Time
	UpdatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (d daytradeExecution) Table(newTableName string) *daytradeExecution {
	d.daytradeExecutionDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d daytradeExecution) As(alias string) *daytradeExecution {
	d.daytradeExecutionDo.DO = *(d.daytradeExecutionDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *daytradeExecution) updateTableName(table string) *daytradeExecution {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewUint64(table, "id")
	d.ExecutedOn = field.NewTime(table, "executed_on")
	d.TradeKind = field.NewString(table, "trade_kind")
	d.MarginKind = field.NewString(table, "margin_kind")
	d.TickerSymbol = field.NewString(table, "ticker_symbol")
	d.BrandName = field.NewString(table, "brand_name")
	d.Quantity = field.NewUint32(table, "quantity")
	d.TradeAmount = field.NewInt64(table, "trade_amount")
	d.UnitPrice = field.NewFloat64(table, "unit_price")
	d.AverageCost = field.NewFloat64(table, "average_cost")
	d.ProfitLoss = field.NewInt64(table, "profit_loss")
	d.OccurrenceNo = field.NewUint32(table, "occurrence_no")
	d.Source = field.NewString(table, "source")
	d.CreatedAt = field.NewTime(table, "created_at")
	d.UpdatedAt = field.NewTime(table, "updated_at")

	d.fillFieldMap()

	return d
}

func (d *daytradeExecution) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *daytradeExecution) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 15)
	d.fieldMap["id"] = d.ID
	d.fieldMap["executed_on"] = d.ExecutedOn
	d.fieldMap["trade_kind"] = d.TradeKind
	d.fieldMap["margin_kind"] = d.MarginKind
	d.fieldMap["ticker_symbol"] = d.TickerSymbol
	d.fieldMap["brand_name"] = d.BrandName
	d.fieldMap["quantity"] = d.Quantity
	d.fieldMap["trade_amount"] = d.TradeAmount
	d.fieldMap["unit_price"] = d.UnitPrice
	d.fieldMap["average_cost"] = d.AverageCost
	d.fieldMap["profit_loss"] = d.ProfitLoss
	d.fieldMap["occurrence_no"] = d.OccurrenceNo
	d.fieldMap["source"] = d.Source
	d.fieldMap["created_at"] = d.CreatedAt
	d.fieldMap["updated_at"] = d.UpdatedAt
}

func (d daytradeExecution) clone(db *gorm.DB) daytradeExecution {
	d.daytradeExecutionDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d daytradeExecution) replaceDB(db *gorm.DB) daytradeExecution {
	d.daytradeExecutionDo.ReplaceDB(db)
	return d
}

type daytradeExecutionDo struct{ gen.DO }

type IDaytradeExecutionDo interface {
	gen.SubQuery
	Debug() IDaytradeExecutionDo
	WithContext(ctx context.Context) IDaytradeExecutionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDaytradeExecutionDo
	WriteDB() IDaytradeExecutionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDaytradeExecutionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDaytradeExecutionDo
	Not(conds ...gen.Condition) IDaytradeExecutionDo
	Or(conds ...gen.Condition) IDaytradeExecutionDo
	Select(conds ...field.Expr) IDaytradeExecutionDo
	Where(conds ...gen.Condition) IDaytradeExecutionDo
	Order(conds ...field.Expr) IDaytradeExecutionDo
	Distinct(cols ...field.Expr) IDaytradeExecutionDo
	Omit(cols ...field.Expr) IDaytradeExecutionDo
	Join(table schema.Tabler, on ...field.Expr) IDaytradeExecutionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDaytradeExecutionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDaytradeExecutionDo
	Group(cols ...field.Expr) IDaytradeExecutionDo
	Having(conds ...gen.Condition) IDaytradeExecutionDo
	Limit(limit int) IDaytradeExecutionDo
	Offset(offset int) IDaytradeExecutionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDaytradeExecutionDo
	Unscoped() IDaytradeExecutionDo
	Create(values ...*gen_model.DaytradeExecution) error
	CreateInBatches(values []*gen_model.DaytradeExecution, batchSize int) error
	Save(values ...*gen_model.DaytradeExecution) error
	First() (*gen_model.DaytradeExecution, error)
	Take() (*gen_model.DaytradeExecution, error)
	Last() (*gen_model.DaytradeExecution, error)
	Find() ([]*gen_model.DaytradeExecution, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*gen_model.DaytradeExecution, err error)
	FindInBatches(result *[]*gen_model.DaytradeExecution, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*gen_model.DaytradeExecution) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDaytradeExecutionDo
	Assign(attrs ...field.AssignExpr) IDaytradeExecutionDo
	Joins(fields ...field.RelationField) IDaytradeExecutionDo
	Preload(fields ...field.RelationField) IDaytradeExecutionDo
	FirstOrInit() (*gen_model.DaytradeExecution, error)
	FirstOrCreate() (*gen_model.DaytradeExecution, error)
	FindByPage(offset int, limit int) (result []*gen_model.DaytradeExecution, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDaytradeExecutionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d daytradeExecutionDo) Debug() IDaytradeExecutionDo {
	return d.withDO(d.DO.Debug())
}

func (d daytradeExecutionDo) WithContext(ctx context.Context) IDaytradeExecutionDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d daytradeExecutionDo) ReadDB() IDaytradeExecutionDo {
	return d.Clauses(dbresolver.Read)
}

func (d daytradeExecutionDo) WriteDB() IDaytradeExecutionDo {
	return d.Clauses(dbresolver.Write)
}

func (d daytradeExecutionDo) Session(config *gorm.Session) IDaytradeExecutionDo {
	return d.withDO(d.DO.Session(config))
}

func (d daytradeExecutionDo) Clauses(conds ...clause.Expression) IDaytradeExecutionDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d daytradeExecutionDo) Returning(value interface{}, columns ...string) IDaytradeExecutionDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d daytradeExecutionDo) Not(conds ...gen.Condition) IDaytradeExecutionDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d daytradeExecutionDo) Or(conds ...gen.Condition) IDaytradeExecutionDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d daytradeExecutionDo) Select(conds ...field.Expr) IDaytradeExecutionDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d daytradeExecutionDo) Where(conds ...gen.Condition) IDaytradeExecutionDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d daytradeExecutionDo) Order(conds ...field.Expr) IDaytradeExecutionDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d daytradeExecutionDo) Distinct(cols ...field.Expr) IDaytradeExecutionDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d daytradeExecutionDo) Omit(cols ...field.Expr) IDaytradeExecutionDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d daytradeExecutionDo) Join(table schema.Tabler, on ...field.Expr) IDaytradeExecutionDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d daytradeExecutionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDaytradeExecutionDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d daytradeExecutionDo) RightJoin(table schema.Tabler, on ...field.Expr) IDaytradeExecutionDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d daytradeExecutionDo) Group(cols ...field.Expr) IDaytradeExecutionDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d daytradeExecutionDo) Having(conds ...gen.Condition) IDaytradeExecutionDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d daytradeExecutionDo) Limit(limit int) IDaytradeExecutionDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d daytradeExecutionDo) Offset(offset int) IDaytradeExecutionDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d daytradeExecutionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDaytradeExecutionDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d daytradeExecutionDo) Unscoped() IDaytradeExecutionDo {
	return d.withDO(d.DO.Unscoped())
}

func (d daytradeExecutionDo) Create(values ...*gen_model.DaytradeExecution) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d daytradeExecutionDo) CreateInBatches(values []*gen_model.DaytradeExecution, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d daytradeExecutionDo) Save(values ...*gen_model.DaytradeExecution) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d daytradeExecutionDo) First() (*gen_model.DaytradeExecution, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.DaytradeExecution), nil
	}
}

func (d daytradeExecutionDo) Take() (*gen_model.DaytradeExecution, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.DaytradeExecution), nil
	}
}

func (d daytradeExecutionDo) Last() (*gen_model.DaytradeExecution, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.DaytradeExecution), nil
	}
}

func (d daytradeExecutionDo) Find() ([]*gen_model.DaytradeExecution, error) {
	result, err := d.DO.Find()
	return result.([]*gen_model.DaytradeExecution), err
}

func (d daytradeExecutionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*gen_model.DaytradeExecution, err error) {
	buf := make([]*gen_model.DaytradeExecution, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d daytradeExecutionDo) FindInBatches(result *[]*gen_model.DaytradeExecution, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d daytradeExecutionDo) Attrs(attrs ...field.AssignExpr) IDaytradeExecutionDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d daytradeExecutionDo) Assign(attrs ...field.AssignExpr) IDaytradeExecutionDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d daytradeExecutionDo) Joins(fields ...field.RelationField) IDaytradeExecutionDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d daytradeExecutionDo) Preload(fields ...field.RelationField) IDaytradeExecutionDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d daytradeExecutionDo) FirstOrInit() (*gen_model.DaytradeExecution, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.DaytradeExecution), nil
	}
}

func (d daytradeExecutionDo) FirstOrCreate() (*gen_model.DaytradeExecution, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.DaytradeExecution), nil
	}
}

func (d daytradeExecutionDo) FindByPage(offset int, limit int) (result []*gen_model.DaytradeExecution, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d daytradeExecutionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d daytradeExecutionDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d daytradeExecutionDo) Delete(models ...*gen_model.DaytradeExecution) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *daytradeExecutionDo) withDO(do gen.Dao) *daytradeExecutionDo {
	d.DO = *do.(*gen.DO)
	return d
}
