// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/Code0716/stock-price-repository/infrastructure/database/gen_model"
)

func newDaytradeTradeNote(db *gorm.DB, opts ...gen.DOOption) daytradeTradeNote {
	_daytradeTradeNote := daytradeTradeNote{}

	_daytradeTradeNote.daytradeTradeNoteDo.UseDB(db, opts...)
	_daytradeTradeNote.daytradeTradeNoteDo.UseModel(&gen_model.DaytradeTradeNote{})

	tableName := _daytradeTradeNote.daytradeTradeNoteDo.TableName()
	_daytradeTradeNote.ALL = field.NewAsterisk(tableName)
	_daytradeTradeNote.ID = field.NewUint64(tableName, "id")
	_daytradeTradeNote.TickerSymbol = field.NewString(tableName, "ticker_symbol")
	_daytradeTradeNote.ExecutedOn = field.NewTime(tableName, "executed_on")
	_daytradeTradeNote.Direction = field.NewString(tableName, "direction")
	_daytradeTradeNote.Memo = field.NewString(tableName, "memo")
	_daytradeTradeNote.Tags = field.NewString(tableName, "tags")
	_daytradeTradeNote.DeclaredStopPrice = field.NewFloat64(tableName, "declared_stop_price")
	_daytradeTradeNote.CreatedAt = field.NewTime(tableName, "created_at")
	_daytradeTradeNote.UpdatedAt = field.NewTime(tableName, "updated_at")

	_daytradeTradeNote.fillFieldMap()

	return _daytradeTradeNote
}

type daytradeTradeNote struct {
	daytradeTradeNoteDo

	ALL               field.Asterisk
	ID                field.Uint64
	TickerSymbol      field.String  // 銘柄コード
	ExecutedOn        field.Time    // 約定日（近似キー）
	Direction         field.String  // 正規化済み売買方向（近似キー）
	Memo              field.String  // 自由メモ
	Tags              field.String  // タグ配列（例: ["高値掴み","ナンピン"]）
	DeclaredStopPrice field.Float64 // 損切りライン宣言価格（自動判定はしない・記録のみ）
	CreatedAt         field.Time
	UpdatedAt         field.Time

	fieldMap map[string]field.Expr
}

func (d daytradeTradeNote) Table(newTableName string) *daytradeTradeNote {
	d.daytradeTradeNoteDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d daytradeTradeNote) As(alias string) *daytradeTradeNote {
	d.daytradeTradeNoteDo.DO = *(d.daytradeTradeNoteDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *daytradeTradeNote) updateTableName(table string) *daytradeTradeNote {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewUint64(table, "id")
	d.TickerSymbol = field.NewString(table, "ticker_symbol")
	d.ExecutedOn = field.NewTime(table, "executed_on")
	d.Direction = field.NewString(table, "direction")
	d.Memo = field.NewString(table, "memo")
	d.Tags = field.NewString(table, "tags")
	d.DeclaredStopPrice = field.NewFloat64(table, "declared_stop_price")
	d.CreatedAt = field.NewTime(table, "created_at")
	d.UpdatedAt = field.NewTime(table, "updated_at")

	d.fillFieldMap()

	return d
}

func (d *daytradeTradeNote) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *daytradeTradeNote) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 9)
	d.fieldMap["id"] = d.ID
	d.fieldMap["ticker_symbol"] = d.TickerSymbol
	d.fieldMap["executed_on"] = d.ExecutedOn
	d.fieldMap["direction"] = d.Direction
	d.fieldMap["memo"] = d.Memo
	d.fieldMap["tags"] = d.Tags
	d.fieldMap["declared_stop_price"] = d.DeclaredStopPrice
	d.fieldMap["created_at"] = d.CreatedAt
	d.fieldMap["updated_at"] = d.UpdatedAt
}

func (d daytradeTradeNote) clone(db *gorm.DB) daytradeTradeNote {
	d.daytradeTradeNoteDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d daytradeTradeNote) replaceDB(db *gorm.DB) daytradeTradeNote {
	d.daytradeTradeNoteDo.ReplaceDB(db)
	return d
}

type daytradeTradeNoteDo struct{ gen.DO }

type IDaytradeTradeNoteDo interface {
	gen.SubQuery
	Debug() IDaytradeTradeNoteDo
	WithContext(ctx context.Context) IDaytradeTradeNoteDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDaytradeTradeNoteDo
	WriteDB() IDaytradeTradeNoteDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDaytradeTradeNoteDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDaytradeTradeNoteDo
	Not(conds ...gen.Condition) IDaytradeTradeNoteDo
	Or(conds ...gen.Condition) IDaytradeTradeNoteDo
	Select(conds ...field.Expr) IDaytradeTradeNoteDo
	Where(conds ...gen.Condition) IDaytradeTradeNoteDo
	Order(conds ...field.Expr) IDaytradeTradeNoteDo
	Distinct(cols ...field.Expr) IDaytradeTradeNoteDo
	Omit(cols ...field.Expr) IDaytradeTradeNoteDo
	Join(table schema.Tabler, on ...field.Expr) IDaytradeTradeNoteDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDaytradeTradeNoteDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDaytradeTradeNoteDo
	Group(cols ...field.Expr) IDaytradeTradeNoteDo
	Having(conds ...gen.Condition) IDaytradeTradeNoteDo
	Limit(limit int) IDaytradeTradeNoteDo
	Offset(offset int) IDaytradeTradeNoteDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDaytradeTradeNoteDo
	Unscoped() IDaytradeTradeNoteDo
	Create(values ...*gen_model.DaytradeTradeNote) error
	CreateInBatches(values []*gen_model.DaytradeTradeNote, batchSize int) error
	Save(values ...*gen_model.DaytradeTradeNote) error
	First() (*gen_model.DaytradeTradeNote, error)
	Take() (*gen_model.DaytradeTradeNote, error)
	Last() (*gen_model.DaytradeTradeNote, error)
	Find() ([]*gen_model.DaytradeTradeNote, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*gen_model.DaytradeTradeNote, err error)
	FindInBatches(result *[]*gen_model.DaytradeTradeNote, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*gen_model.DaytradeTradeNote) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDaytradeTradeNoteDo
	Assign(attrs ...field.AssignExpr) IDaytradeTradeNoteDo
	Joins(fields ...field.RelationField) IDaytradeTradeNoteDo
	Preload(fields ...field.RelationField) IDaytradeTradeNoteDo
	FirstOrInit() (*gen_model.DaytradeTradeNote, error)
	FirstOrCreate() (*gen_model.DaytradeTradeNote, error)
	FindByPage(offset int, limit int) (result []*gen_model.DaytradeTradeNote, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDaytradeTradeNoteDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d daytradeTradeNoteDo) Debug() IDaytradeTradeNoteDo {
	return d.withDO(d.DO.Debug())
}

func (d daytradeTradeNoteDo) WithContext(ctx context.Context) IDaytradeTradeNoteDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d daytradeTradeNoteDo) ReadDB() IDaytradeTradeNoteDo {
	return d.Clauses(dbresolver.Read)
}

func (d daytradeTradeNoteDo) WriteDB() IDaytradeTradeNoteDo {
	return d.Clauses(dbresolver.Write)
}

func (d daytradeTradeNoteDo) Session(config *gorm.Session) IDaytradeTradeNoteDo {
	return d.withDO(d.DO.Session(config))
}

func (d daytradeTradeNoteDo) Clauses(conds ...clause.Expression) IDaytradeTradeNoteDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d daytradeTradeNoteDo) Returning(value interface{}, columns ...string) IDaytradeTradeNoteDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d daytradeTradeNoteDo) Not(conds ...gen.Condition) IDaytradeTradeNoteDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d daytradeTradeNoteDo) Or(conds ...gen.Condition) IDaytradeTradeNoteDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d daytradeTradeNoteDo) Select(conds ...field.Expr) IDaytradeTradeNoteDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d daytradeTradeNoteDo) Where(conds ...gen.Condition) IDaytradeTradeNoteDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d daytradeTradeNoteDo) Order(conds ...field.Expr) IDaytradeTradeNoteDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d daytradeTradeNoteDo) Distinct(cols ...field.Expr) IDaytradeTradeNoteDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d daytradeTradeNoteDo) Omit(cols ...field.Expr) IDaytradeTradeNoteDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d daytradeTradeNoteDo) Join(table schema.Tabler, on ...field.Expr) IDaytradeTradeNoteDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d daytradeTradeNoteDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDaytradeTradeNoteDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d daytradeTradeNoteDo) RightJoin(table schema.Tabler, on ...field.Expr) IDaytradeTradeNoteDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d daytradeTradeNoteDo) Group(cols ...field.Expr) IDaytradeTradeNoteDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d daytradeTradeNoteDo) Having(conds ...gen.Condition) IDaytradeTradeNoteDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d daytradeTradeNoteDo) Limit(limit int) IDaytradeTradeNoteDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d daytradeTradeNoteDo) Offset(offset int) IDaytradeTradeNoteDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d daytradeTradeNoteDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDaytradeTradeNoteDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d daytradeTradeNoteDo) Unscoped() IDaytradeTradeNoteDo {
	return d.withDO(d.DO.Unscoped())
}

func (d daytradeTradeNoteDo) Create(values ...*gen_model.DaytradeTradeNote) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d daytradeTradeNoteDo) CreateInBatches(values []*gen_model.DaytradeTradeNote, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d daytradeTradeNoteDo) Save(values ...*gen_model.DaytradeTradeNote) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d daytradeTradeNoteDo) First() (*gen_model.DaytradeTradeNote, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.DaytradeTradeNote), nil
	}
}

func (d daytradeTradeNoteDo) Take() (*gen_model.DaytradeTradeNote, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.DaytradeTradeNote), nil
	}
}

func (d daytradeTradeNoteDo) Last() (*gen_model.DaytradeTradeNote, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.DaytradeTradeNote), nil
	}
}

func (d daytradeTradeNoteDo) Find() ([]*gen_model.DaytradeTradeNote, error) {
	result, err := d.DO.Find()
	return result.([]*gen_model.DaytradeTradeNote), err
}

func (d daytradeTradeNoteDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*gen_model.DaytradeTradeNote, err error) {
	buf := make([]*gen_model.DaytradeTradeNote, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d daytradeTradeNoteDo) FindInBatches(result *[]*gen_model.DaytradeTradeNote, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d daytradeTradeNoteDo) Attrs(attrs ...field.AssignExpr) IDaytradeTradeNoteDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d daytradeTradeNoteDo) Assign(attrs ...field.AssignExpr) IDaytradeTradeNoteDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d daytradeTradeNoteDo) Joins(fields ...field.RelationField) IDaytradeTradeNoteDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d daytradeTradeNoteDo) Preload(fields ...field.RelationField) IDaytradeTradeNoteDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d daytradeTradeNoteDo) FirstOrInit() (*gen_model.DaytradeTradeNote, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.DaytradeTradeNote), nil
	}
}

func (d daytradeTradeNoteDo) FirstOrCreate() (*gen_model.DaytradeTradeNote, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.DaytradeTradeNote), nil
	}
}

func (d daytradeTradeNoteDo) FindByPage(offset int, limit int) (result []*gen_model.DaytradeTradeNote, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d daytradeTradeNoteDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d daytradeTradeNoteDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d daytradeTradeNoteDo) Delete(models ...*gen_model.DaytradeTradeNote) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *daytradeTradeNoteDo) withDO(do gen.Dao) *daytradeTradeNoteDo {
	d.DO = *do.(*gen.DO)
	return d
}
