// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/Code0716/stock-price-repository/infrastructure/database/gen_model"
)

func newFinAnnouncement(db *gorm.DB, opts ...gen.DOOption) finAnnouncement {
	_finAnnouncement := finAnnouncement{}

	_finAnnouncement.finAnnouncementDo.UseDB(db, opts...)
	_finAnnouncement.finAnnouncementDo.UseModel(&gen_model.FinAnnouncement{})

	tableName := _finAnnouncement.finAnnouncementDo.TableName()
	_finAnnouncement.ALL = field.NewAsterisk(tableName)
	_finAnnouncement.ID = field.NewString(tableName, "id")
	_finAnnouncement.TickerSymbol = field.NewString(tableName, "ticker_symbol")
	_finAnnouncement.StockBrandID = field.NewString(tableName, "stock_brand_id")
	_finAnnouncement.AnnouncementDate = field.NewTime(tableName, "announcement_date")
	_finAnnouncement.FiscalYear = field.NewString(tableName, "fiscal_year")
	_finAnnouncement.FiscalQuarter = field.NewString(tableName, "fiscal_quarter")
	_finAnnouncement.Sector17Code = field.NewString(tableName, "sector_17_code")
	_finAnnouncement.Sector33Code = field.NewString(tableName, "sector_33_code")
	_finAnnouncement.CreatedAt = field.NewTime(tableName, "created_at")
	_finAnnouncement.UpdatedAt = field.NewTime(tableName, "updated_at")

	_finAnnouncement.fillFieldMap()

	return _finAnnouncement
}

type finAnnouncement struct {
	finAnnouncementDo

	ALL              field.Asterisk
	ID               field.String
	TickerSymbol     field.String // 証券コード
	StockBrandID     field.String // 銘柄ID
	AnnouncementDate field.Time   // 決算発表予定日
	FiscalYear       field.String // 会計年度
	FiscalQuarter    field.String // 会計期間
	Sector17Code     field.String // 17業種コード
	Sector33Code     field.String // 33業種コード
	CreatedAt        field.Time
	UpdatedAt        field.Time

	fieldMap map[string]field.Expr
}

func (f finAnnouncement) Table(newTableName string) *finAnnouncement {
	f.finAnnouncementDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f finAnnouncement) As(alias string) *finAnnouncement {
	f.finAnnouncementDo.DO = *(f.finAnnouncementDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *finAnnouncement) updateTableName(table string) *finAnnouncement {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewString(table, "id")
	f.TickerSymbol = field.NewString(table, "ticker_symbol")
	f.StockBrandID = field.NewString(table, "stock_brand_id")
	f.AnnouncementDate = field.NewTime(table, "announcement_date")
	f.FiscalYear = field.NewString(table, "fiscal_year")
	f.FiscalQuarter = field.NewString(table, "fiscal_quarter")
	f.Sector17Code = field.NewString(table, "sector_17_code")
	f.Sector33Code = field.NewString(table, "sector_33_code")
	f.CreatedAt = field.NewTime(table, "created_at")
	f.UpdatedAt = field.NewTime(table, "updated_at")

	f.fillFieldMap()

	return f
}

func (f *finAnnouncement) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *finAnnouncement) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 10)
	f.fieldMap["id"] = f.ID
	f.fieldMap["ticker_symbol"] = f.TickerSymbol
	f.fieldMap["stock_brand_id"] = f.StockBrandID
	f.fieldMap["announcement_date"] = f.AnnouncementDate
	f.fieldMap["fiscal_year"] = f.FiscalYear
	f.fieldMap["fiscal_quarter"] = f.FiscalQuarter
	f.fieldMap["sector_17_code"] = f.Sector17Code
	f.fieldMap["sector_33_code"] = f.Sector33Code
	f.fieldMap["created_at"] = f.CreatedAt
	f.fieldMap["updated_at"] = f.UpdatedAt
}

func (f finAnnouncement) clone(db *gorm.DB) finAnnouncement {
	f.finAnnouncementDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f finAnnouncement) replaceDB(db *gorm.DB) finAnnouncement {
	f.finAnnouncementDo.ReplaceDB(db)
	return f
}

type finAnnouncementDo struct{ gen.DO }

type IFinAnnouncementDo interface {
	gen.SubQuery
	Debug() IFinAnnouncementDo
	WithContext(ctx context.Context) IFinAnnouncementDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IFinAnnouncementDo
	WriteDB() IFinAnnouncementDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IFinAnnouncementDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IFinAnnouncementDo
	Not(conds ...gen.Condition) IFinAnnouncementDo
	Or(conds ...gen.Condition) IFinAnnouncementDo
	Select(conds ...field.Expr) IFinAnnouncementDo
	Where(conds ...gen.Condition) IFinAnnouncementDo
	Order(conds ...field.Expr) IFinAnnouncementDo
	Distinct(cols ...field.Expr) IFinAnnouncementDo
	Omit(cols ...field.Expr) IFinAnnouncementDo
	Join(table schema.Tabler, on ...field.Expr) IFinAnnouncementDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IFinAnnouncementDo
	RightJoin(table schema.Tabler, on ...field.Expr) IFinAnnouncementDo
	Group(cols ...field.Expr) IFinAnnouncementDo
	Having(conds ...gen.Condition) IFinAnnouncementDo
	Limit(limit int) IFinAnnouncementDo
	Offset(offset int) IFinAnnouncementDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IFinAnnouncementDo
	Unscoped() IFinAnnouncementDo
	Create(values ...*gen_model.FinAnnouncement) error
	CreateInBatches(values []*gen_model.FinAnnouncement, batchSize int) error
	Save(values ...*gen_model.FinAnnouncement) error
	First() (*gen_model.FinAnnouncement, error)
	Take() (*gen_model.FinAnnouncement, error)
	Last() (*gen_model.FinAnnouncement, error)
	Find() ([]*gen_model.FinAnnouncement, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*gen_model.FinAnnouncement, err error)
	FindInBatches(result *[]*gen_model.FinAnnouncement, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*gen_model.FinAnnouncement) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IFinAnnouncementDo
	Assign(attrs ...field.AssignExpr) IFinAnnouncementDo
	Joins(fields ...field.RelationField) IFinAnnouncementDo
	Preload(fields ...field.RelationField) IFinAnnouncementDo
	FirstOrInit() (*gen_model.FinAnnouncement, error)
	FirstOrCreate() (*gen_model.FinAnnouncement, error)
	FindByPage(offset int, limit int) (result []*gen_model.FinAnnouncement, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IFinAnnouncementDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (f finAnnouncementDo) Debug() IFinAnnouncementDo {
	return f.withDO(f.DO.Debug())
}

func (f finAnnouncementDo) WithContext(ctx context.Context) IFinAnnouncementDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f finAnnouncementDo) ReadDB() IFinAnnouncementDo {
	return f.Clauses(dbresolver.Read)
}

func (f finAnnouncementDo) WriteDB() IFinAnnouncementDo {
	return f.Clauses(dbresolver.Write)
}

func (f finAnnouncementDo) Session(config *gorm.Session) IFinAnnouncementDo {
	return f.withDO(f.DO.Session(config))
}

func (f finAnnouncementDo) Clauses(conds ...clause.Expression) IFinAnnouncementDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f finAnnouncementDo) Returning(value interface{}, columns ...string) IFinAnnouncementDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f finAnnouncementDo) Not(conds ...gen.Condition) IFinAnnouncementDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f finAnnouncementDo) Or(conds ...gen.Condition) IFinAnnouncementDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f finAnnouncementDo) Select(conds ...field.Expr) IFinAnnouncementDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f finAnnouncementDo) Where(conds ...gen.Condition) IFinAnnouncementDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f finAnnouncementDo) Order(conds ...field.Expr) IFinAnnouncementDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f finAnnouncementDo) Distinct(cols ...field.Expr) IFinAnnouncementDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f finAnnouncementDo) Omit(cols ...field.Expr) IFinAnnouncementDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f finAnnouncementDo) Join(table schema.Tabler, on ...field.Expr) IFinAnnouncementDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f finAnnouncementDo) LeftJoin(table schema.Tabler, on ...field.Expr) IFinAnnouncementDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f finAnnouncementDo) RightJoin(table schema.Tabler, on ...field.Expr) IFinAnnouncementDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f finAnnouncementDo) Group(cols ...field.Expr) IFinAnnouncementDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f finAnnouncementDo) Having(conds ...gen.Condition) IFinAnnouncementDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f finAnnouncementDo) Limit(limit int) IFinAnnouncementDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f finAnnouncementDo) Offset(offset int) IFinAnnouncementDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f finAnnouncementDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IFinAnnouncementDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f finAnnouncementDo) Unscoped() IFinAnnouncementDo {
	return f.withDO(f.DO.Unscoped())
}

func (f finAnnouncementDo) Create(values ...*gen_model.FinAnnouncement) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f finAnnouncementDo) CreateInBatches(values []*gen_model.FinAnnouncement, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f finAnnouncementDo) Save(values ...*gen_model.FinAnnouncement) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f finAnnouncementDo) First() (*gen_model.FinAnnouncement, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.FinAnnouncement), nil
	}
}

func (f finAnnouncementDo) Take() (*gen_model.FinAnnouncement, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.FinAnnouncement), nil
	}
}

func (f finAnnouncementDo) Last() (*gen_model.FinAnnouncement, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.FinAnnouncement), nil
	}
}

func (f finAnnouncementDo) Find() ([]*gen_model.FinAnnouncement, error) {
	result, err := f.DO.Find()
	return result.([]*gen_model.FinAnnouncement), err
}

func (f finAnnouncementDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*gen_model.FinAnnouncement, err error) {
	buf := make([]*gen_model.FinAnnouncement, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f finAnnouncementDo) FindInBatches(result *[]*gen_model.FinAnnouncement, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f finAnnouncementDo) Attrs(attrs ...field.AssignExpr) IFinAnnouncementDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f finAnnouncementDo) Assign(attrs ...field.AssignExpr) IFinAnnouncementDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f finAnnouncementDo) Joins(fields ...field.RelationField) IFinAnnouncementDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f finAnnouncementDo) Preload(fields ...field.RelationField) IFinAnnouncementDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f finAnnouncementDo) FirstOrInit() (*gen_model.FinAnnouncement, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.FinAnnouncement), nil
	}
}

func (f finAnnouncementDo) FirstOrCreate() (*gen_model.FinAnnouncement, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.FinAnnouncement), nil
	}
}

func (f finAnnouncementDo) FindByPage(offset int, limit int) (result []*gen_model.FinAnnouncement, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f finAnnouncementDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f finAnnouncementDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f finAnnouncementDo) Delete(models ...*gen_model.FinAnnouncement) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *finAnnouncementDo) withDO(do gen.Dao) *finAnnouncementDo {
	f.DO = *do.(*gen.DO)
	return f
}
