// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/Code0716/stock-price-repository/infrastructure/database/gen_model"
)

func newFinStatement(db *gorm.DB, opts ...gen.DOOption) finStatement {
	_finStatement := finStatement{}

	_finStatement.finStatementDo.UseDB(db, opts...)
	_finStatement.finStatementDo.UseModel(&gen_model.FinStatement{})

	tableName := _finStatement.finStatementDo.TableName()
	_finStatement.ALL = field.NewAsterisk(tableName)
	_finStatement.ID = field.NewString(tableName, "id")
	_finStatement.TickerSymbol = field.NewString(tableName, "ticker_symbol")
	_finStatement.StockBrandID = field.NewString(tableName, "stock_brand_id")
	_finStatement.DisclosedDate = field.NewTime(tableName, "disclosed_date")
	_finStatement.FiscalYearEnd = field.NewTime(tableName, "fiscal_year_end")
	_finStatement.TypeOfDocument = field.NewString(tableName, "type_of_document")
	_finStatement.TypeOfCurrentPeriod = field.NewString(tableName, "type_of_current_period")
	_finStatement.NetSales = field.NewFloat64(tableName, "net_sales")
	_finStatement.OperatingProfit = field.NewFloat64(tableName, "operating_profit")
	_finStatement.OrdinaryProfit = field.NewFloat64(tableName, "ordinary_profit")
	_finStatement.Profit = field.NewFloat64(tableName, "profit")
	_finStatement.EarningsPerShare = field.NewFloat64(tableName, "earnings_per_share")
	_finStatement.BookValuePerShare = field.NewFloat64(tableName, "book_value_per_share")
	_finStatement.ForecastNetSales = field.NewFloat64(tableName, "forecast_net_sales")
	_finStatement.ForecastOperatingProfit = field.NewFloat64(tableName, "forecast_operating_profit")
	_finStatement.ForecastProfit = field.NewFloat64(tableName, "forecast_profit")
	_finStatement.ForecastEps = field.NewFloat64(tableName, "forecast_eps")
	_finStatement.ForecastDividendPerShareAnnual = field.NewFloat64(tableName, "forecast_dividend_per_share_annual")
	_finStatement.CreatedAt = field.NewTime(tableName, "created_at")
	_finStatement.UpdatedAt = field.NewTime(tableName, "updated_at")

	_finStatement.fillFieldMap()

	return _finStatement
}

type finStatement struct {
	finStatementDo

	ALL                            field.Asterisk
	ID                             field.String
	TickerSymbol                   field.String  // 証券コード
	StockBrandID                   field.String  // 銘柄ID
	DisclosedDate                  field.Time    // 開示日
	FiscalYearEnd                  field.Time    // 当期末日
	TypeOfDocument                 field.String  // 開示書類種別
	TypeOfCurrentPeriod            field.String  // 当会計期間の種類
	NetSales                       field.Float64 // 売上高
	OperatingProfit                field.Float64 // 営業利益
	OrdinaryProfit                 field.Float64 // 経常利益
	Profit                         field.Float64 // 当期純利益
	EarningsPerShare               field.Float64 // EPS
	BookValuePerShare              field.Float64 // BPS
	ForecastNetSales               field.Float64 // 通期予想売上高
	ForecastOperatingProfit        field.Float64 // 通期予想営業利益
	ForecastProfit                 field.Float64 // 通期予想純利益
	ForecastEps                    field.Float64 // 通期予想EPS
	ForecastDividendPerShareAnnual field.Float64 // 1株あたり当期予想配当（年間合計）
	CreatedAt                      field.Time
	UpdatedAt                      field.Time

	fieldMap map[string]field.Expr
}

func (f finStatement) Table(newTableName string) *finStatement {
	f.finStatementDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f finStatement) As(alias string) *finStatement {
	f.finStatementDo.DO = *(f.finStatementDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *finStatement) updateTableName(table string) *finStatement {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewString(table, "id")
	f.TickerSymbol = field.NewString(table, "ticker_symbol")
	f.StockBrandID = field.NewString(table, "stock_brand_id")
	f.DisclosedDate = field.NewTime(table, "disclosed_date")
	f.FiscalYearEnd = field.NewTime(table, "fiscal_year_end")
	f.TypeOfDocument = field.NewString(table, "type_of_document")
	f.TypeOfCurrentPeriod = field.NewString(table, "type_of_current_period")
	f.NetSales = field.NewFloat64(table, "net_sales")
	f.OperatingProfit = field.NewFloat64(table, "operating_profit")
	f.OrdinaryProfit = field.NewFloat64(table, "ordinary_profit")
	f.Profit = field.NewFloat64(table, "profit")
	f.EarningsPerShare = field.NewFloat64(table, "earnings_per_share")
	f.BookValuePerShare = field.NewFloat64(table, "book_value_per_share")
	f.ForecastNetSales = field.NewFloat64(table, "forecast_net_sales")
	f.ForecastOperatingProfit = field.NewFloat64(table, "forecast_operating_profit")
	f.ForecastProfit = field.NewFloat64(table, "forecast_profit")
	f.ForecastEps = field.NewFloat64(table, "forecast_eps")
	f.ForecastDividendPerShareAnnual = field.NewFloat64(table, "forecast_dividend_per_share_annual")
	f.CreatedAt = field.NewTime(table, "created_at")
	f.UpdatedAt = field.NewTime(table, "updated_at")

	f.fillFieldMap()

	return f
}

func (f *finStatement) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *finStatement) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 20)
	f.fieldMap["id"] = f.ID
	f.fieldMap["ticker_symbol"] = f.TickerSymbol
	f.fieldMap["stock_brand_id"] = f.StockBrandID
	f.fieldMap["disclosed_date"] = f.DisclosedDate
	f.fieldMap["fiscal_year_end"] = f.FiscalYearEnd
	f.fieldMap["type_of_document"] = f.TypeOfDocument
	f.fieldMap["type_of_current_period"] = f.TypeOfCurrentPeriod
	f.fieldMap["net_sales"] = f.NetSales
	f.fieldMap["operating_profit"] = f.OperatingProfit
	f.fieldMap["ordinary_profit"] = f.OrdinaryProfit
	f.fieldMap["profit"] = f.Profit
	f.fieldMap["earnings_per_share"] = f.EarningsPerShare
	f.fieldMap["book_value_per_share"] = f.BookValuePerShare
	f.fieldMap["forecast_net_sales"] = f.ForecastNetSales
	f.fieldMap["forecast_operating_profit"] = f.ForecastOperatingProfit
	f.fieldMap["forecast_profit"] = f.ForecastProfit
	f.fieldMap["forecast_eps"] = f.ForecastEps
	f.fieldMap["forecast_dividend_per_share_annual"] = f.ForecastDividendPerShareAnnual
	f.fieldMap["created_at"] = f.CreatedAt
	f.fieldMap["updated_at"] = f.UpdatedAt
}

func (f finStatement) clone(db *gorm.DB) finStatement {
	f.finStatementDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f finStatement) replaceDB(db *gorm.DB) finStatement {
	f.finStatementDo.ReplaceDB(db)
	return f
}

type finStatementDo struct{ gen.DO }

type IFinStatementDo interface {
	gen.SubQuery
	Debug() IFinStatementDo
	WithContext(ctx context.Context) IFinStatementDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IFinStatementDo
	WriteDB() IFinStatementDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IFinStatementDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IFinStatementDo
	Not(conds ...gen.Condition) IFinStatementDo
	Or(conds ...gen.Condition) IFinStatementDo
	Select(conds ...field.Expr) IFinStatementDo
	Where(conds ...gen.Condition) IFinStatementDo
	Order(conds ...field.Expr) IFinStatementDo
	Distinct(cols ...field.Expr) IFinStatementDo
	Omit(cols ...field.Expr) IFinStatementDo
	Join(table schema.Tabler, on ...field.Expr) IFinStatementDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IFinStatementDo
	RightJoin(table schema.Tabler, on ...field.Expr) IFinStatementDo
	Group(cols ...field.Expr) IFinStatementDo
	Having(conds ...gen.Condition) IFinStatementDo
	Limit(limit int) IFinStatementDo
	Offset(offset int) IFinStatementDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IFinStatementDo
	Unscoped() IFinStatementDo
	Create(values ...*gen_model.FinStatement) error
	CreateInBatches(values []*gen_model.FinStatement, batchSize int) error
	Save(values ...*gen_model.FinStatement) error
	First() (*gen_model.FinStatement, error)
	Take() (*gen_model.FinStatement, error)
	Last() (*gen_model.FinStatement, error)
	Find() ([]*gen_model.FinStatement, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*gen_model.FinStatement, err error)
	FindInBatches(result *[]*gen_model.FinStatement, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*gen_model.FinStatement) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IFinStatementDo
	Assign(attrs ...field.AssignExpr) IFinStatementDo
	Joins(fields ...field.RelationField) IFinStatementDo
	Preload(fields ...field.RelationField) IFinStatementDo
	FirstOrInit() (*gen_model.FinStatement, error)
	FirstOrCreate() (*gen_model.FinStatement, error)
	FindByPage(offset int, limit int) (result []*gen_model.FinStatement, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IFinStatementDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (f finStatementDo) Debug() IFinStatementDo {
	return f.withDO(f.DO.Debug())
}

func (f finStatementDo) WithContext(ctx context.Context) IFinStatementDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f finStatementDo) ReadDB() IFinStatementDo {
	return f.Clauses(dbresolver.Read)
}

func (f finStatementDo) WriteDB() IFinStatementDo {
	return f.Clauses(dbresolver.Write)
}

func (f finStatementDo) Session(config *gorm.Session) IFinStatementDo {
	return f.withDO(f.DO.Session(config))
}

func (f finStatementDo) Clauses(conds ...clause.Expression) IFinStatementDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f finStatementDo) Returning(value interface{}, columns ...string) IFinStatementDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f finStatementDo) Not(conds ...gen.Condition) IFinStatementDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f finStatementDo) Or(conds ...gen.Condition) IFinStatementDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f finStatementDo) Select(conds ...field.Expr) IFinStatementDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f finStatementDo) Where(conds ...gen.Condition) IFinStatementDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f finStatementDo) Order(conds ...field.Expr) IFinStatementDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f finStatementDo) Distinct(cols ...field.Expr) IFinStatementDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f finStatementDo) Omit(cols ...field.Expr) IFinStatementDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f finStatementDo) Join(table schema.Tabler, on ...field.Expr) IFinStatementDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f finStatementDo) LeftJoin(table schema.Tabler, on ...field.Expr) IFinStatementDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f finStatementDo) RightJoin(table schema.Tabler, on ...field.Expr) IFinStatementDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f finStatementDo) Group(cols ...field.Expr) IFinStatementDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f finStatementDo) Having(conds ...gen.Condition) IFinStatementDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f finStatementDo) Limit(limit int) IFinStatementDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f finStatementDo) Offset(offset int) IFinStatementDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f finStatementDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IFinStatementDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f finStatementDo) Unscoped() IFinStatementDo {
	return f.withDO(f.DO.Unscoped())
}

func (f finStatementDo) Create(values ...*gen_model.FinStatement) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f finStatementDo) CreateInBatches(values []*gen_model.FinStatement, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f finStatementDo) Save(values ...*gen_model.FinStatement) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f finStatementDo) First() (*gen_model.FinStatement, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.FinStatement), nil
	}
}

func (f finStatementDo) Take() (*gen_model.FinStatement, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.FinStatement), nil
	}
}

func (f finStatementDo) Last() (*gen_model.FinStatement, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.FinStatement), nil
	}
}

func (f finStatementDo) Find() ([]*gen_model.FinStatement, error) {
	result, err := f.DO.Find()
	return result.([]*gen_model.FinStatement), err
}

func (f finStatementDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*gen_model.FinStatement, err error) {
	buf := make([]*gen_model.FinStatement, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f finStatementDo) FindInBatches(result *[]*gen_model.FinStatement, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f finStatementDo) Attrs(attrs ...field.AssignExpr) IFinStatementDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f finStatementDo) Assign(attrs ...field.AssignExpr) IFinStatementDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f finStatementDo) Joins(fields ...field.RelationField) IFinStatementDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f finStatementDo) Preload(fields ...field.RelationField) IFinStatementDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f finStatementDo) FirstOrInit() (*gen_model.FinStatement, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.FinStatement), nil
	}
}

func (f finStatementDo) FirstOrCreate() (*gen_model.FinStatement, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.FinStatement), nil
	}
}

func (f finStatementDo) FindByPage(offset int, limit int) (result []*gen_model.FinStatement, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f finStatementDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f finStatementDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f finStatementDo) Delete(models ...*gen_model.FinStatement) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *finStatementDo) withDO(do gen.Dao) *finStatementDo {
	f.DO = *do.(*gen.DO)
	return f
}
