// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                                 = new(Query)
	AnalyzeStockBrandPriceHistory     *analyzeStockBrandPriceHistory
	AppliedStockConsolidationsHistory *appliedStockConsolidationsHistory
	AppliedStockSplitsHistory         *appliedStockSplitsHistory
	DaytradeExecution                 *daytradeExecution
	DaytradeTradeNote                 *daytradeTradeNote
	DjiStockAverageDailyStockPrice    *djiStockAverageDailyStockPrice
	FinAnnouncement                   *finAnnouncement
	FinStatement                      *finStatement
	HighVolumeStockBrand              *highVolumeStockBrand
	NikkeiStockAverageDailyPrice      *nikkeiStockAverageDailyPrice
	QuizAnswer                        *quizAnswer
	QuizDailyUniverse                 *quizDailyUniverse
	SchemaMigration                   *schemaMigration
	Sector17AverageDailyPrice         *sector17AverageDailyPrice
	Sector33AverageDailyPrice         *sector33AverageDailyPrice
	StockBrand                        *stockBrand
	StockBrandsDailyPrice             *stockBrandsDailyPrice
	StockBrandsDailyPriceForAnalyze   *stockBrandsDailyPriceForAnalyze
	TopixDailyPrice                   *topixDailyPrice
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	AnalyzeStockBrandPriceHistory = &Q.AnalyzeStockBrandPriceHistory
	AppliedStockConsolidationsHistory = &Q.AppliedStockConsolidationsHistory
	AppliedStockSplitsHistory = &Q.AppliedStockSplitsHistory
	DaytradeExecution = &Q.DaytradeExecution
	DaytradeTradeNote = &Q.DaytradeTradeNote
	DjiStockAverageDailyStockPrice = &Q.DjiStockAverageDailyStockPrice
	FinAnnouncement = &Q.FinAnnouncement
	FinStatement = &Q.FinStatement
	HighVolumeStockBrand = &Q.HighVolumeStockBrand
	NikkeiStockAverageDailyPrice = &Q.NikkeiStockAverageDailyPrice
	QuizAnswer = &Q.QuizAnswer
	QuizDailyUniverse = &Q.QuizDailyUniverse
	SchemaMigration = &Q.SchemaMigration
	Sector17AverageDailyPrice = &Q.Sector17AverageDailyPrice
	Sector33AverageDailyPrice = &Q.Sector33AverageDailyPrice
	StockBrand = &Q.StockBrand
	StockBrandsDailyPrice = &Q.StockBrandsDailyPrice
	StockBrandsDailyPriceForAnalyze = &Q.StockBrandsDailyPriceForAnalyze
	TopixDailyPrice = &Q.TopixDailyPrice
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                                db,
		AnalyzeStockBrandPriceHistory:     newAnalyzeStockBrandPriceHistory(db, opts...),
		AppliedStockConsolidationsHistory: newAppliedStockConsolidationsHistory(db, opts...),
		AppliedStockSplitsHistory:         newAppliedStockSplitsHistory(db, opts...),
		DaytradeExecution:                 newDaytradeExecution(db, opts...),
		DaytradeTradeNote:                 newDaytradeTradeNote(db, opts...),
		DjiStockAverageDailyStockPrice:    newDjiStockAverageDailyStockPrice(db, opts...),
		FinAnnouncement:                   newFinAnnouncement(db, opts...),
		FinStatement:                      newFinStatement(db, opts...),
		HighVolumeStockBrand:              newHighVolumeStockBrand(db, opts...),
		NikkeiStockAverageDailyPrice:      newNikkeiStockAverageDailyPrice(db, opts...),
		QuizAnswer:                        newQuizAnswer(db, opts...),
		QuizDailyUniverse:                 newQuizDailyUniverse(db, opts...),
		SchemaMigration:                   newSchemaMigration(db, opts...),
		Sector17AverageDailyPrice:         newSector17AverageDailyPrice(db, opts...),
		Sector33AverageDailyPrice:         newSector33AverageDailyPrice(db, opts...),
		StockBrand:                        newStockBrand(db, opts...),
		StockBrandsDailyPrice:             newStockBrandsDailyPrice(db, opts...),
		StockBrandsDailyPriceForAnalyze:   newStockBrandsDailyPriceForAnalyze(db, opts...),
		TopixDailyPrice:                   newTopixDailyPrice(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	AnalyzeStockBrandPriceHistory     analyzeStockBrandPriceHistory
	AppliedStockConsolidationsHistory appliedStockConsolidationsHistory
	AppliedStockSplitsHistory         appliedStockSplitsHistory
	DaytradeExecution                 daytradeExecution
	DaytradeTradeNote                 daytradeTradeNote
	DjiStockAverageDailyStockPrice    djiStockAverageDailyStockPrice
	FinAnnouncement                   finAnnouncement
	FinStatement                      finStatement
	HighVolumeStockBrand              highVolumeStockBrand
	NikkeiStockAverageDailyPrice      nikkeiStockAverageDailyPrice
	QuizAnswer                        quizAnswer
	QuizDailyUniverse                 quizDailyUniverse
	SchemaMigration                   schemaMigration
	Sector17AverageDailyPrice         sector17AverageDailyPrice
	Sector33AverageDailyPrice         sector33AverageDailyPrice
	StockBrand                        stockBrand
	StockBrandsDailyPrice             stockBrandsDailyPrice
	StockBrandsDailyPriceForAnalyze   stockBrandsDailyPriceForAnalyze
	TopixDailyPrice                   topixDailyPrice
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) UnderlyingDB() *gorm.DB { return q.db }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                                db,
		AnalyzeStockBrandPriceHistory:     q.AnalyzeStockBrandPriceHistory.clone(db),
		AppliedStockConsolidationsHistory: q.AppliedStockConsolidationsHistory.clone(db),
		AppliedStockSplitsHistory:         q.AppliedStockSplitsHistory.clone(db),
		DaytradeExecution:                 q.DaytradeExecution.clone(db),
		DaytradeTradeNote:                 q.DaytradeTradeNote.clone(db),
		DjiStockAverageDailyStockPrice:    q.DjiStockAverageDailyStockPrice.clone(db),
		FinAnnouncement:                   q.FinAnnouncement.clone(db),
		FinStatement:                      q.FinStatement.clone(db),
		HighVolumeStockBrand:              q.HighVolumeStockBrand.clone(db),
		NikkeiStockAverageDailyPrice:      q.NikkeiStockAverageDailyPrice.clone(db),
		QuizAnswer:                        q.QuizAnswer.clone(db),
		QuizDailyUniverse:                 q.QuizDailyUniverse.clone(db),
		SchemaMigration:                   q.SchemaMigration.clone(db),
		Sector17AverageDailyPrice:         q.Sector17AverageDailyPrice.clone(db),
		Sector33AverageDailyPrice:         q.Sector33AverageDailyPrice.clone(db),
		StockBrand:                        q.StockBrand.clone(db),
		StockBrandsDailyPrice:             q.StockBrandsDailyPrice.clone(db),
		StockBrandsDailyPriceForAnalyze:   q.StockBrandsDailyPriceForAnalyze.clone(db),
		TopixDailyPrice:                   q.TopixDailyPrice.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                                db,
		AnalyzeStockBrandPriceHistory:     q.AnalyzeStockBrandPriceHistory.replaceDB(db),
		AppliedStockConsolidationsHistory: q.AppliedStockConsolidationsHistory.replaceDB(db),
		AppliedStockSplitsHistory:         q.AppliedStockSplitsHistory.replaceDB(db),
		DaytradeExecution:                 q.DaytradeExecution.replaceDB(db),
		DaytradeTradeNote:                 q.DaytradeTradeNote.replaceDB(db),
		DjiStockAverageDailyStockPrice:    q.DjiStockAverageDailyStockPrice.replaceDB(db),
		FinAnnouncement:                   q.FinAnnouncement.replaceDB(db),
		FinStatement:                      q.FinStatement.replaceDB(db),
		HighVolumeStockBrand:              q.HighVolumeStockBrand.replaceDB(db),
		NikkeiStockAverageDailyPrice:      q.NikkeiStockAverageDailyPrice.replaceDB(db),
		QuizAnswer:                        q.QuizAnswer.replaceDB(db),
		QuizDailyUniverse:                 q.QuizDailyUniverse.replaceDB(db),
		SchemaMigration:                   q.SchemaMigration.replaceDB(db),
		Sector17AverageDailyPrice:         q.Sector17AverageDailyPrice.replaceDB(db),
		Sector33AverageDailyPrice:         q.Sector33AverageDailyPrice.replaceDB(db),
		StockBrand:                        q.StockBrand.replaceDB(db),
		StockBrandsDailyPrice:             q.StockBrandsDailyPrice.replaceDB(db),
		StockBrandsDailyPriceForAnalyze:   q.StockBrandsDailyPriceForAnalyze.replaceDB(db),
		TopixDailyPrice:                   q.TopixDailyPrice.replaceDB(db),
	}
}

type queryCtx struct {
	AnalyzeStockBrandPriceHistory     IAnalyzeStockBrandPriceHistoryDo
	AppliedStockConsolidationsHistory IAppliedStockConsolidationsHistoryDo
	AppliedStockSplitsHistory         IAppliedStockSplitsHistoryDo
	DaytradeExecution                 IDaytradeExecutionDo
	DaytradeTradeNote                 IDaytradeTradeNoteDo
	DjiStockAverageDailyStockPrice    IDjiStockAverageDailyStockPriceDo
	FinAnnouncement                   IFinAnnouncementDo
	FinStatement                      IFinStatementDo
	HighVolumeStockBrand              IHighVolumeStockBrandDo
	NikkeiStockAverageDailyPrice      INikkeiStockAverageDailyPriceDo
	QuizAnswer                        IQuizAnswerDo
	QuizDailyUniverse                 IQuizDailyUniverseDo
	SchemaMigration                   ISchemaMigrationDo
	Sector17AverageDailyPrice         ISector17AverageDailyPriceDo
	Sector33AverageDailyPrice         ISector33AverageDailyPriceDo
	StockBrand                        IStockBrandDo
	StockBrandsDailyPrice             IStockBrandsDailyPriceDo
	StockBrandsDailyPriceForAnalyze   IStockBrandsDailyPriceForAnalyzeDo
	TopixDailyPrice                   ITopixDailyPriceDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		AnalyzeStockBrandPriceHistory:     q.AnalyzeStockBrandPriceHistory.WithContext(ctx),
		AppliedStockConsolidationsHistory: q.AppliedStockConsolidationsHistory.WithContext(ctx),
		AppliedStockSplitsHistory:         q.AppliedStockSplitsHistory.WithContext(ctx),
		DaytradeExecution:                 q.DaytradeExecution.WithContext(ctx),
		DaytradeTradeNote:                 q.DaytradeTradeNote.WithContext(ctx),
		DjiStockAverageDailyStockPrice:    q.DjiStockAverageDailyStockPrice.WithContext(ctx),
		FinAnnouncement:                   q.FinAnnouncement.WithContext(ctx),
		FinStatement:                      q.FinStatement.WithContext(ctx),
		HighVolumeStockBrand:              q.HighVolumeStockBrand.WithContext(ctx),
		NikkeiStockAverageDailyPrice:      q.NikkeiStockAverageDailyPrice.WithContext(ctx),
		QuizAnswer:                        q.QuizAnswer.WithContext(ctx),
		QuizDailyUniverse:                 q.QuizDailyUniverse.WithContext(ctx),
		SchemaMigration:                   q.SchemaMigration.WithContext(ctx),
		Sector17AverageDailyPrice:         q.Sector17AverageDailyPrice.WithContext(ctx),
		Sector33AverageDailyPrice:         q.Sector33AverageDailyPrice.WithContext(ctx),
		StockBrand:                        q.StockBrand.WithContext(ctx),
		StockBrandsDailyPrice:             q.StockBrandsDailyPrice.WithContext(ctx),
		StockBrandsDailyPriceForAnalyze:   q.StockBrandsDailyPriceForAnalyze.WithContext(ctx),
		TopixDailyPrice:                   q.TopixDailyPrice.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
