// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/Code0716/stock-price-repository/infrastructure/database/gen_model"
)

func newMarketCalendar(db *gorm.DB, opts ...gen.DOOption) marketCalendar {
	_marketCalendar := marketCalendar{}

	_marketCalendar.marketCalendarDo.UseDB(db, opts...)
	_marketCalendar.marketCalendarDo.UseModel(&gen_model.MarketCalendar{})

	tableName := _marketCalendar.marketCalendarDo.TableName()
	_marketCalendar.ALL = field.NewAsterisk(tableName)
	_marketCalendar.CalendarDate = field.NewTime(tableName, "calendar_date")
	_marketCalendar.HolDiv = field.NewInt32(tableName, "hol_div")
	_marketCalendar.CreatedAt = field.NewTime(tableName, "created_at")
	_marketCalendar.UpdatedAt = field.NewTime(tableName, "updated_at")

	_marketCalendar.fillFieldMap()

	return _marketCalendar
}

type marketCalendar struct {
	marketCalendarDo

	ALL          field.Asterisk
	CalendarDate field.Time  // 日付
	HolDiv       field.Int32 // 休日区分（J-Quants HolDiv）: 0=休場 / 1=営業 / 2=半日取引 / 3=休場だが祝日取引あり
	CreatedAt    field.Time  // created_at
	UpdatedAt    field.Time  // updated_at

	fieldMap map[string]field.Expr
}

func (m marketCalendar) Table(newTableName string) *marketCalendar {
	m.marketCalendarDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m marketCalendar) As(alias string) *marketCalendar {
	m.marketCalendarDo.DO = *(m.marketCalendarDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *marketCalendar) updateTableName(table string) *marketCalendar {
	m.ALL = field.NewAsterisk(table)
	m.CalendarDate = field.NewTime(table, "calendar_date")
	m.HolDiv = field.NewInt32(table, "hol_div")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")

	m.fillFieldMap()

	return m
}

func (m *marketCalendar) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *marketCalendar) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 4)
	m.fieldMap["calendar_date"] = m.CalendarDate
	m.fieldMap["hol_div"] = m.HolDiv
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
}

func (m marketCalendar) clone(db *gorm.DB) marketCalendar {
	m.marketCalendarDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m marketCalendar) replaceDB(db *gorm.DB) marketCalendar {
	m.marketCalendarDo.ReplaceDB(db)
	return m
}

type marketCalendarDo struct{ gen.DO }

type IMarketCalendarDo interface {
	gen.SubQuery
	Debug() IMarketCalendarDo
	WithContext(ctx context.Context) IMarketCalendarDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMarketCalendarDo
	WriteDB() IMarketCalendarDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMarketCalendarDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMarketCalendarDo
	Not(conds ...gen.Condition) IMarketCalendarDo
	Or(conds ...gen.Condition) IMarketCalendarDo
	Select(conds ...field.Expr) IMarketCalendarDo
	Where(conds ...gen.Condition) IMarketCalendarDo
	Order(conds ...field.Expr) IMarketCalendarDo
	Distinct(cols ...field.Expr) IMarketCalendarDo
	Omit(cols ...field.Expr) IMarketCalendarDo
	Join(table schema.Tabler, on ...field.Expr) IMarketCalendarDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMarketCalendarDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMarketCalendarDo
	Group(cols ...field.Expr) IMarketCalendarDo
	Having(conds ...gen.Condition) IMarketCalendarDo
	Limit(limit int) IMarketCalendarDo
	Offset(offset int) IMarketCalendarDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMarketCalendarDo
	Unscoped() IMarketCalendarDo
	Create(values ...*gen_model.MarketCalendar) error
	CreateInBatches(values []*gen_model.MarketCalendar, batchSize int) error
	Save(values ...*gen_model.MarketCalendar) error
	First() (*gen_model.MarketCalendar, error)
	Take() (*gen_model.MarketCalendar, error)
	Last() (*gen_model.MarketCalendar, error)
	Find() ([]*gen_model.MarketCalendar, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*gen_model.MarketCalendar, err error)
	FindInBatches(result *[]*gen_model.MarketCalendar, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*gen_model.MarketCalendar) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMarketCalendarDo
	Assign(attrs ...field.AssignExpr) IMarketCalendarDo
	Joins(fields ...field.RelationField) IMarketCalendarDo
	Preload(fields ...field.RelationField) IMarketCalendarDo
	FirstOrInit() (*gen_model.MarketCalendar, error)
	FirstOrCreate() (*gen_model.MarketCalendar, error)
	FindByPage(offset int, limit int) (result []*gen_model.MarketCalendar, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMarketCalendarDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m marketCalendarDo) Debug() IMarketCalendarDo {
	return m.withDO(m.DO.Debug())
}

func (m marketCalendarDo) WithContext(ctx context.Context) IMarketCalendarDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m marketCalendarDo) ReadDB() IMarketCalendarDo {
	return m.Clauses(dbresolver.Read)
}

func (m marketCalendarDo) WriteDB() IMarketCalendarDo {
	return m.Clauses(dbresolver.Write)
}

func (m marketCalendarDo) Session(config *gorm.Session) IMarketCalendarDo {
	return m.withDO(m.DO.Session(config))
}

func (m marketCalendarDo) Clauses(conds ...clause.Expression) IMarketCalendarDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m marketCalendarDo) Returning(value interface{}, columns ...string) IMarketCalendarDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m marketCalendarDo) Not(conds ...gen.Condition) IMarketCalendarDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m marketCalendarDo) Or(conds ...gen.Condition) IMarketCalendarDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m marketCalendarDo) Select(conds ...field.Expr) IMarketCalendarDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m marketCalendarDo) Where(conds ...gen.Condition) IMarketCalendarDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m marketCalendarDo) Order(conds ...field.Expr) IMarketCalendarDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m marketCalendarDo) Distinct(cols ...field.Expr) IMarketCalendarDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m marketCalendarDo) Omit(cols ...field.Expr) IMarketCalendarDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m marketCalendarDo) Join(table schema.Tabler, on ...field.Expr) IMarketCalendarDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m marketCalendarDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMarketCalendarDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m marketCalendarDo) RightJoin(table schema.Tabler, on ...field.Expr) IMarketCalendarDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m marketCalendarDo) Group(cols ...field.Expr) IMarketCalendarDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m marketCalendarDo) Having(conds ...gen.Condition) IMarketCalendarDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m marketCalendarDo) Limit(limit int) IMarketCalendarDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m marketCalendarDo) Offset(offset int) IMarketCalendarDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m marketCalendarDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMarketCalendarDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m marketCalendarDo) Unscoped() IMarketCalendarDo {
	return m.withDO(m.DO.Unscoped())
}

func (m marketCalendarDo) Create(values ...*gen_model.MarketCalendar) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m marketCalendarDo) CreateInBatches(values []*gen_model.MarketCalendar, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m marketCalendarDo) Save(values ...*gen_model.MarketCalendar) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m marketCalendarDo) First() (*gen_model.MarketCalendar, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.MarketCalendar), nil
	}
}

func (m marketCalendarDo) Take() (*gen_model.MarketCalendar, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.MarketCalendar), nil
	}
}

func (m marketCalendarDo) Last() (*gen_model.MarketCalendar, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.MarketCalendar), nil
	}
}

func (m marketCalendarDo) Find() ([]*gen_model.MarketCalendar, error) {
	result, err := m.DO.Find()
	return result.([]*gen_model.MarketCalendar), err
}

func (m marketCalendarDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*gen_model.MarketCalendar, err error) {
	buf := make([]*gen_model.MarketCalendar, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m marketCalendarDo) FindInBatches(result *[]*gen_model.MarketCalendar, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m marketCalendarDo) Attrs(attrs ...field.AssignExpr) IMarketCalendarDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m marketCalendarDo) Assign(attrs ...field.AssignExpr) IMarketCalendarDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m marketCalendarDo) Joins(fields ...field.RelationField) IMarketCalendarDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m marketCalendarDo) Preload(fields ...field.RelationField) IMarketCalendarDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m marketCalendarDo) FirstOrInit() (*gen_model.MarketCalendar, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.MarketCalendar), nil
	}
}

func (m marketCalendarDo) FirstOrCreate() (*gen_model.MarketCalendar, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.MarketCalendar), nil
	}
}

func (m marketCalendarDo) FindByPage(offset int, limit int) (result []*gen_model.MarketCalendar, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m marketCalendarDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m marketCalendarDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m marketCalendarDo) Delete(models ...*gen_model.MarketCalendar) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *marketCalendarDo) withDO(do gen.Dao) *marketCalendarDo {
	m.DO = *do.(*gen.DO)
	return m
}
