// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/Code0716/stock-price-repository/infrastructure/database/gen_model"
)

func newMarketEvent(db *gorm.DB, opts ...gen.DOOption) marketEvent {
	_marketEvent := marketEvent{}

	_marketEvent.marketEventDo.UseDB(db, opts...)
	_marketEvent.marketEventDo.UseModel(&gen_model.MarketEvent{})

	tableName := _marketEvent.marketEventDo.TableName()
	_marketEvent.ALL = field.NewAsterisk(tableName)
	_marketEvent.ID = field.NewUint64(tableName, "id")
	_marketEvent.EventDate = field.NewTime(tableName, "event_date")
	_marketEvent.Kind = field.NewString(tableName, "kind")
	_marketEvent.Label = field.NewString(tableName, "label")
	_marketEvent.Source = field.NewString(tableName, "source")
	_marketEvent.CreatedAt = field.NewTime(tableName, "created_at")
	_marketEvent.UpdatedAt = field.NewTime(tableName, "updated_at")

	_marketEvent.fillFieldMap()

	return _marketEvent
}

type marketEvent struct {
	marketEventDo

	ALL       field.Asterisk
	ID        field.Uint64 // id
	EventDate field.Time   // カレンダー上に表示する日付（FOMCは結果発表の日本時間の日付）
	Kind      field.String // イベント種別: sq_major / sq_mini / boj / fomc / us_cpi / us_nfp
	Label     field.String // 表示ラベル
	Source    field.String // 取得元: jquants_calc / boj_html / fed_html / bls_ics / manual
	CreatedAt field.Time   // created_at
	UpdatedAt field.Time   // updated_at

	fieldMap map[string]field.Expr
}

func (m marketEvent) Table(newTableName string) *marketEvent {
	m.marketEventDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m marketEvent) As(alias string) *marketEvent {
	m.marketEventDo.DO = *(m.marketEventDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *marketEvent) updateTableName(table string) *marketEvent {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewUint64(table, "id")
	m.EventDate = field.NewTime(table, "event_date")
	m.Kind = field.NewString(table, "kind")
	m.Label = field.NewString(table, "label")
	m.Source = field.NewString(table, "source")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")

	m.fillFieldMap()

	return m
}

func (m *marketEvent) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *marketEvent) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 7)
	m.fieldMap["id"] = m.ID
	m.fieldMap["event_date"] = m.EventDate
	m.fieldMap["kind"] = m.Kind
	m.fieldMap["label"] = m.Label
	m.fieldMap["source"] = m.Source
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
}

func (m marketEvent) clone(db *gorm.DB) marketEvent {
	m.marketEventDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m marketEvent) replaceDB(db *gorm.DB) marketEvent {
	m.marketEventDo.ReplaceDB(db)
	return m
}

type marketEventDo struct{ gen.DO }

type IMarketEventDo interface {
	gen.SubQuery
	Debug() IMarketEventDo
	WithContext(ctx context.Context) IMarketEventDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMarketEventDo
	WriteDB() IMarketEventDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMarketEventDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMarketEventDo
	Not(conds ...gen.Condition) IMarketEventDo
	Or(conds ...gen.Condition) IMarketEventDo
	Select(conds ...field.Expr) IMarketEventDo
	Where(conds ...gen.Condition) IMarketEventDo
	Order(conds ...field.Expr) IMarketEventDo
	Distinct(cols ...field.Expr) IMarketEventDo
	Omit(cols ...field.Expr) IMarketEventDo
	Join(table schema.Tabler, on ...field.Expr) IMarketEventDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMarketEventDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMarketEventDo
	Group(cols ...field.Expr) IMarketEventDo
	Having(conds ...gen.Condition) IMarketEventDo
	Limit(limit int) IMarketEventDo
	Offset(offset int) IMarketEventDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMarketEventDo
	Unscoped() IMarketEventDo
	Create(values ...*gen_model.MarketEvent) error
	CreateInBatches(values []*gen_model.MarketEvent, batchSize int) error
	Save(values ...*gen_model.MarketEvent) error
	First() (*gen_model.MarketEvent, error)
	Take() (*gen_model.MarketEvent, error)
	Last() (*gen_model.MarketEvent, error)
	Find() ([]*gen_model.MarketEvent, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*gen_model.MarketEvent, err error)
	FindInBatches(result *[]*gen_model.MarketEvent, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*gen_model.MarketEvent) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMarketEventDo
	Assign(attrs ...field.AssignExpr) IMarketEventDo
	Joins(fields ...field.RelationField) IMarketEventDo
	Preload(fields ...field.RelationField) IMarketEventDo
	FirstOrInit() (*gen_model.MarketEvent, error)
	FirstOrCreate() (*gen_model.MarketEvent, error)
	FindByPage(offset int, limit int) (result []*gen_model.MarketEvent, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMarketEventDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m marketEventDo) Debug() IMarketEventDo {
	return m.withDO(m.DO.Debug())
}

func (m marketEventDo) WithContext(ctx context.Context) IMarketEventDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m marketEventDo) ReadDB() IMarketEventDo {
	return m.Clauses(dbresolver.Read)
}

func (m marketEventDo) WriteDB() IMarketEventDo {
	return m.Clauses(dbresolver.Write)
}

func (m marketEventDo) Session(config *gorm.Session) IMarketEventDo {
	return m.withDO(m.DO.Session(config))
}

func (m marketEventDo) Clauses(conds ...clause.Expression) IMarketEventDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m marketEventDo) Returning(value interface{}, columns ...string) IMarketEventDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m marketEventDo) Not(conds ...gen.Condition) IMarketEventDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m marketEventDo) Or(conds ...gen.Condition) IMarketEventDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m marketEventDo) Select(conds ...field.Expr) IMarketEventDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m marketEventDo) Where(conds ...gen.Condition) IMarketEventDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m marketEventDo) Order(conds ...field.Expr) IMarketEventDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m marketEventDo) Distinct(cols ...field.Expr) IMarketEventDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m marketEventDo) Omit(cols ...field.Expr) IMarketEventDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m marketEventDo) Join(table schema.Tabler, on ...field.Expr) IMarketEventDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m marketEventDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMarketEventDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m marketEventDo) RightJoin(table schema.Tabler, on ...field.Expr) IMarketEventDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m marketEventDo) Group(cols ...field.Expr) IMarketEventDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m marketEventDo) Having(conds ...gen.Condition) IMarketEventDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m marketEventDo) Limit(limit int) IMarketEventDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m marketEventDo) Offset(offset int) IMarketEventDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m marketEventDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMarketEventDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m marketEventDo) Unscoped() IMarketEventDo {
	return m.withDO(m.DO.Unscoped())
}

func (m marketEventDo) Create(values ...*gen_model.MarketEvent) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m marketEventDo) CreateInBatches(values []*gen_model.MarketEvent, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m marketEventDo) Save(values ...*gen_model.MarketEvent) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m marketEventDo) First() (*gen_model.MarketEvent, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.MarketEvent), nil
	}
}

func (m marketEventDo) Take() (*gen_model.MarketEvent, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.MarketEvent), nil
	}
}

func (m marketEventDo) Last() (*gen_model.MarketEvent, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.MarketEvent), nil
	}
}

func (m marketEventDo) Find() ([]*gen_model.MarketEvent, error) {
	result, err := m.DO.Find()
	return result.([]*gen_model.MarketEvent), err
}

func (m marketEventDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*gen_model.MarketEvent, err error) {
	buf := make([]*gen_model.MarketEvent, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m marketEventDo) FindInBatches(result *[]*gen_model.MarketEvent, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m marketEventDo) Attrs(attrs ...field.AssignExpr) IMarketEventDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m marketEventDo) Assign(attrs ...field.AssignExpr) IMarketEventDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m marketEventDo) Joins(fields ...field.RelationField) IMarketEventDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m marketEventDo) Preload(fields ...field.RelationField) IMarketEventDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m marketEventDo) FirstOrInit() (*gen_model.MarketEvent, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.MarketEvent), nil
	}
}

func (m marketEventDo) FirstOrCreate() (*gen_model.MarketEvent, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.MarketEvent), nil
	}
}

func (m marketEventDo) FindByPage(offset int, limit int) (result []*gen_model.MarketEvent, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m marketEventDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m marketEventDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m marketEventDo) Delete(models ...*gen_model.MarketEvent) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *marketEventDo) withDO(do gen.Dao) *marketEventDo {
	m.DO = *do.(*gen.DO)
	return m
}
