// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/Code0716/stock-price-repository/infrastructure/database/gen_model"
)

func newQuizAnswer(db *gorm.DB, opts ...gen.DOOption) quizAnswer {
	_quizAnswer := quizAnswer{}

	_quizAnswer.quizAnswerDo.UseDB(db, opts...)
	_quizAnswer.quizAnswerDo.UseModel(&gen_model.QuizAnswer{})

	tableName := _quizAnswer.quizAnswerDo.TableName()
	_quizAnswer.ALL = field.NewAsterisk(tableName)
	_quizAnswer.ID = field.NewUint64(tableName, "id")
	_quizAnswer.QuizDate = field.NewTime(tableName, "quiz_date")
	_quizAnswer.StockBrandID = field.NewString(tableName, "stock_brand_id")
	_quizAnswer.TickerSymbol = field.NewString(tableName, "ticker_symbol")
	_quizAnswer.Prediction = field.NewString(tableName, "prediction")
	_quizAnswer.AnsweredAt = field.NewTime(tableName, "answered_at")
	_quizAnswer.NextClosePrice = field.NewFloat64(tableName, "next_close_price")
	_quizAnswer.ActualReturn = field.NewFloat64(tableName, "actual_return")
	_quizAnswer.Outcome = field.NewString(tableName, "outcome")
	_quizAnswer.Score = field.NewInt32(tableName, "score")
	_quizAnswer.GradedAt = field.NewTime(tableName, "graded_at")
	_quizAnswer.CreatedAt = field.NewTime(tableName, "created_at")
	_quizAnswer.UpdatedAt = field.NewTime(tableName, "updated_at")

	_quizAnswer.fillFieldMap()

	return _quizAnswer
}

type quizAnswer struct {
	quizAnswerDo

	ALL            field.Asterisk
	ID             field.Uint64
	QuizDate       field.Time    // クイズ対象日
	StockBrandID   field.String  // stock_brand.id
	TickerSymbol   field.String  // 銘柄コード
	Prediction     field.String  // 回答: strong_down/down/up/strong_up
	AnsweredAt     field.Time    // 回答日時
	NextClosePrice field.Float64 // 翌営業日終値（採点時に確定）
	ActualReturn   field.Float64 // (翌営業日終値-基準終値)/基準終値
	Outcome        field.String  // 採点結果: correct/incorrect/draw/void
	Score          field.Int32   // 獲得スコア +2/+1/0/-1/-2
	GradedAt       field.Time    // 採点日時
	CreatedAt      field.Time    // created_at
	UpdatedAt      field.Time    // updated_at

	fieldMap map[string]field.Expr
}

func (q quizAnswer) Table(newTableName string) *quizAnswer {
	q.quizAnswerDo.UseTable(newTableName)
	return q.updateTableName(newTableName)
}

func (q quizAnswer) As(alias string) *quizAnswer {
	q.quizAnswerDo.DO = *(q.quizAnswerDo.As(alias).(*gen.DO))
	return q.updateTableName(alias)
}

func (q *quizAnswer) updateTableName(table string) *quizAnswer {
	q.ALL = field.NewAsterisk(table)
	q.ID = field.NewUint64(table, "id")
	q.QuizDate = field.NewTime(table, "quiz_date")
	q.StockBrandID = field.NewString(table, "stock_brand_id")
	q.TickerSymbol = field.NewString(table, "ticker_symbol")
	q.Prediction = field.NewString(table, "prediction")
	q.AnsweredAt = field.NewTime(table, "answered_at")
	q.NextClosePrice = field.NewFloat64(table, "next_close_price")
	q.ActualReturn = field.NewFloat64(table, "actual_return")
	q.Outcome = field.NewString(table, "outcome")
	q.Score = field.NewInt32(table, "score")
	q.GradedAt = field.NewTime(table, "graded_at")
	q.CreatedAt = field.NewTime(table, "created_at")
	q.UpdatedAt = field.NewTime(table, "updated_at")

	q.fillFieldMap()

	return q
}

func (q *quizAnswer) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := q.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (q *quizAnswer) fillFieldMap() {
	q.fieldMap = make(map[string]field.Expr, 13)
	q.fieldMap["id"] = q.ID
	q.fieldMap["quiz_date"] = q.QuizDate
	q.fieldMap["stock_brand_id"] = q.StockBrandID
	q.fieldMap["ticker_symbol"] = q.TickerSymbol
	q.fieldMap["prediction"] = q.Prediction
	q.fieldMap["answered_at"] = q.AnsweredAt
	q.fieldMap["next_close_price"] = q.NextClosePrice
	q.fieldMap["actual_return"] = q.ActualReturn
	q.fieldMap["outcome"] = q.Outcome
	q.fieldMap["score"] = q.Score
	q.fieldMap["graded_at"] = q.GradedAt
	q.fieldMap["created_at"] = q.CreatedAt
	q.fieldMap["updated_at"] = q.UpdatedAt
}

func (q quizAnswer) clone(db *gorm.DB) quizAnswer {
	q.quizAnswerDo.ReplaceConnPool(db.Statement.ConnPool)
	return q
}

func (q quizAnswer) replaceDB(db *gorm.DB) quizAnswer {
	q.quizAnswerDo.ReplaceDB(db)
	return q
}

type quizAnswerDo struct{ gen.DO }

type IQuizAnswerDo interface {
	gen.SubQuery
	Debug() IQuizAnswerDo
	WithContext(ctx context.Context) IQuizAnswerDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IQuizAnswerDo
	WriteDB() IQuizAnswerDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IQuizAnswerDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IQuizAnswerDo
	Not(conds ...gen.Condition) IQuizAnswerDo
	Or(conds ...gen.Condition) IQuizAnswerDo
	Select(conds ...field.Expr) IQuizAnswerDo
	Where(conds ...gen.Condition) IQuizAnswerDo
	Order(conds ...field.Expr) IQuizAnswerDo
	Distinct(cols ...field.Expr) IQuizAnswerDo
	Omit(cols ...field.Expr) IQuizAnswerDo
	Join(table schema.Tabler, on ...field.Expr) IQuizAnswerDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IQuizAnswerDo
	RightJoin(table schema.Tabler, on ...field.Expr) IQuizAnswerDo
	Group(cols ...field.Expr) IQuizAnswerDo
	Having(conds ...gen.Condition) IQuizAnswerDo
	Limit(limit int) IQuizAnswerDo
	Offset(offset int) IQuizAnswerDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IQuizAnswerDo
	Unscoped() IQuizAnswerDo
	Create(values ...*gen_model.QuizAnswer) error
	CreateInBatches(values []*gen_model.QuizAnswer, batchSize int) error
	Save(values ...*gen_model.QuizAnswer) error
	First() (*gen_model.QuizAnswer, error)
	Take() (*gen_model.QuizAnswer, error)
	Last() (*gen_model.QuizAnswer, error)
	Find() ([]*gen_model.QuizAnswer, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*gen_model.QuizAnswer, err error)
	FindInBatches(result *[]*gen_model.QuizAnswer, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*gen_model.QuizAnswer) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IQuizAnswerDo
	Assign(attrs ...field.AssignExpr) IQuizAnswerDo
	Joins(fields ...field.RelationField) IQuizAnswerDo
	Preload(fields ...field.RelationField) IQuizAnswerDo
	FirstOrInit() (*gen_model.QuizAnswer, error)
	FirstOrCreate() (*gen_model.QuizAnswer, error)
	FindByPage(offset int, limit int) (result []*gen_model.QuizAnswer, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IQuizAnswerDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (q quizAnswerDo) Debug() IQuizAnswerDo {
	return q.withDO(q.DO.Debug())
}

func (q quizAnswerDo) WithContext(ctx context.Context) IQuizAnswerDo {
	return q.withDO(q.DO.WithContext(ctx))
}

func (q quizAnswerDo) ReadDB() IQuizAnswerDo {
	return q.Clauses(dbresolver.Read)
}

func (q quizAnswerDo) WriteDB() IQuizAnswerDo {
	return q.Clauses(dbresolver.Write)
}

func (q quizAnswerDo) Session(config *gorm.Session) IQuizAnswerDo {
	return q.withDO(q.DO.Session(config))
}

func (q quizAnswerDo) Clauses(conds ...clause.Expression) IQuizAnswerDo {
	return q.withDO(q.DO.Clauses(conds...))
}

func (q quizAnswerDo) Returning(value interface{}, columns ...string) IQuizAnswerDo {
	return q.withDO(q.DO.Returning(value, columns...))
}

func (q quizAnswerDo) Not(conds ...gen.Condition) IQuizAnswerDo {
	return q.withDO(q.DO.Not(conds...))
}

func (q quizAnswerDo) Or(conds ...gen.Condition) IQuizAnswerDo {
	return q.withDO(q.DO.Or(conds...))
}

func (q quizAnswerDo) Select(conds ...field.Expr) IQuizAnswerDo {
	return q.withDO(q.DO.Select(conds...))
}

func (q quizAnswerDo) Where(conds ...gen.Condition) IQuizAnswerDo {
	return q.withDO(q.DO.Where(conds...))
}

func (q quizAnswerDo) Order(conds ...field.Expr) IQuizAnswerDo {
	return q.withDO(q.DO.Order(conds...))
}

func (q quizAnswerDo) Distinct(cols ...field.Expr) IQuizAnswerDo {
	return q.withDO(q.DO.Distinct(cols...))
}

func (q quizAnswerDo) Omit(cols ...field.Expr) IQuizAnswerDo {
	return q.withDO(q.DO.Omit(cols...))
}

func (q quizAnswerDo) Join(table schema.Tabler, on ...field.Expr) IQuizAnswerDo {
	return q.withDO(q.DO.Join(table, on...))
}

func (q quizAnswerDo) LeftJoin(table schema.Tabler, on ...field.Expr) IQuizAnswerDo {
	return q.withDO(q.DO.LeftJoin(table, on...))
}

func (q quizAnswerDo) RightJoin(table schema.Tabler, on ...field.Expr) IQuizAnswerDo {
	return q.withDO(q.DO.RightJoin(table, on...))
}

func (q quizAnswerDo) Group(cols ...field.Expr) IQuizAnswerDo {
	return q.withDO(q.DO.Group(cols...))
}

func (q quizAnswerDo) Having(conds ...gen.Condition) IQuizAnswerDo {
	return q.withDO(q.DO.Having(conds...))
}

func (q quizAnswerDo) Limit(limit int) IQuizAnswerDo {
	return q.withDO(q.DO.Limit(limit))
}

func (q quizAnswerDo) Offset(offset int) IQuizAnswerDo {
	return q.withDO(q.DO.Offset(offset))
}

func (q quizAnswerDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IQuizAnswerDo {
	return q.withDO(q.DO.Scopes(funcs...))
}

func (q quizAnswerDo) Unscoped() IQuizAnswerDo {
	return q.withDO(q.DO.Unscoped())
}

func (q quizAnswerDo) Create(values ...*gen_model.QuizAnswer) error {
	if len(values) == 0 {
		return nil
	}
	return q.DO.Create(values)
}

func (q quizAnswerDo) CreateInBatches(values []*gen_model.QuizAnswer, batchSize int) error {
	return q.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (q quizAnswerDo) Save(values ...*gen_model.QuizAnswer) error {
	if len(values) == 0 {
		return nil
	}
	return q.DO.Save(values)
}

func (q quizAnswerDo) First() (*gen_model.QuizAnswer, error) {
	if result, err := q.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.QuizAnswer), nil
	}
}

func (q quizAnswerDo) Take() (*gen_model.QuizAnswer, error) {
	if result, err := q.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.QuizAnswer), nil
	}
}

func (q quizAnswerDo) Last() (*gen_model.QuizAnswer, error) {
	if result, err := q.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.QuizAnswer), nil
	}
}

func (q quizAnswerDo) Find() ([]*gen_model.QuizAnswer, error) {
	result, err := q.DO.Find()
	return result.([]*gen_model.QuizAnswer), err
}

func (q quizAnswerDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*gen_model.QuizAnswer, err error) {
	buf := make([]*gen_model.QuizAnswer, 0, batchSize)
	err = q.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (q quizAnswerDo) FindInBatches(result *[]*gen_model.QuizAnswer, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return q.DO.FindInBatches(result, batchSize, fc)
}

func (q quizAnswerDo) Attrs(attrs ...field.AssignExpr) IQuizAnswerDo {
	return q.withDO(q.DO.Attrs(attrs...))
}

func (q quizAnswerDo) Assign(attrs ...field.AssignExpr) IQuizAnswerDo {
	return q.withDO(q.DO.Assign(attrs...))
}

func (q quizAnswerDo) Joins(fields ...field.RelationField) IQuizAnswerDo {
	for _, _f := range fields {
		q = *q.withDO(q.DO.Joins(_f))
	}
	return &q
}

func (q quizAnswerDo) Preload(fields ...field.RelationField) IQuizAnswerDo {
	for _, _f := range fields {
		q = *q.withDO(q.DO.Preload(_f))
	}
	return &q
}

func (q quizAnswerDo) FirstOrInit() (*gen_model.QuizAnswer, error) {
	if result, err := q.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.QuizAnswer), nil
	}
}

func (q quizAnswerDo) FirstOrCreate() (*gen_model.QuizAnswer, error) {
	if result, err := q.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.QuizAnswer), nil
	}
}

func (q quizAnswerDo) FindByPage(offset int, limit int) (result []*gen_model.QuizAnswer, count int64, err error) {
	result, err = q.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = q.Offset(-1).Limit(-1).Count()
	return
}

func (q quizAnswerDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = q.Count()
	if err != nil {
		return
	}

	err = q.Offset(offset).Limit(limit).Scan(result)
	return
}

func (q quizAnswerDo) Scan(result interface{}) (err error) {
	return q.DO.Scan(result)
}

func (q quizAnswerDo) Delete(models ...*gen_model.QuizAnswer) (result gen.ResultInfo, err error) {
	return q.DO.Delete(models)
}

func (q *quizAnswerDo) withDO(do gen.Dao) *quizAnswerDo {
	q.DO = *do.(*gen.DO)
	return q
}
