// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/Code0716/stock-price-repository/infrastructure/database/gen_model"
)

func newTopixDailyPrice(db *gorm.DB, opts ...gen.DOOption) topixDailyPrice {
	_topixDailyPrice := topixDailyPrice{}

	_topixDailyPrice.topixDailyPriceDo.UseDB(db, opts...)
	_topixDailyPrice.topixDailyPriceDo.UseModel(&gen_model.TopixDailyPrice{})

	tableName := _topixDailyPrice.topixDailyPriceDo.TableName()
	_topixDailyPrice.ALL = field.NewAsterisk(tableName)
	_topixDailyPrice.Date = field.NewTime(tableName, "date")
	_topixDailyPrice.OpenPrice = field.NewFloat64(tableName, "open_price")
	_topixDailyPrice.ClosePrice = field.NewFloat64(tableName, "close_price")
	_topixDailyPrice.HighPrice = field.NewFloat64(tableName, "high_price")
	_topixDailyPrice.LowPrice = field.NewFloat64(tableName, "low_price")
	_topixDailyPrice.AdjClosePrice = field.NewFloat64(tableName, "adj_close_price")
	_topixDailyPrice.CreatedAt = field.NewTime(tableName, "created_at")
	_topixDailyPrice.UpdatedAt = field.NewTime(tableName, "updated_at")

	_topixDailyPrice.fillFieldMap()

	return _topixDailyPrice
}

type topixDailyPrice struct {
	topixDailyPriceDo

	ALL           field.Asterisk
	Date          field.Time    // date
	OpenPrice     field.Float64 // 始値
	ClosePrice    field.Float64 // 終値
	HighPrice     field.Float64 // 高値
	LowPrice      field.Float64 // 安値
	AdjClosePrice field.Float64 // 配当や株式分割を考慮した終値
	CreatedAt     field.Time    // created_at
	UpdatedAt     field.Time    // updated_at

	fieldMap map[string]field.Expr
}

func (t topixDailyPrice) Table(newTableName string) *topixDailyPrice {
	t.topixDailyPriceDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t topixDailyPrice) As(alias string) *topixDailyPrice {
	t.topixDailyPriceDo.DO = *(t.topixDailyPriceDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *topixDailyPrice) updateTableName(table string) *topixDailyPrice {
	t.ALL = field.NewAsterisk(table)
	t.Date = field.NewTime(table, "date")
	t.OpenPrice = field.NewFloat64(table, "open_price")
	t.ClosePrice = field.NewFloat64(table, "close_price")
	t.HighPrice = field.NewFloat64(table, "high_price")
	t.LowPrice = field.NewFloat64(table, "low_price")
	t.AdjClosePrice = field.NewFloat64(table, "adj_close_price")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")

	t.fillFieldMap()

	return t
}

func (t *topixDailyPrice) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *topixDailyPrice) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 8)
	t.fieldMap["date"] = t.Date
	t.fieldMap["open_price"] = t.OpenPrice
	t.fieldMap["close_price"] = t.ClosePrice
	t.fieldMap["high_price"] = t.HighPrice
	t.fieldMap["low_price"] = t.LowPrice
	t.fieldMap["adj_close_price"] = t.AdjClosePrice
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
}

func (t topixDailyPrice) clone(db *gorm.DB) topixDailyPrice {
	t.topixDailyPriceDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t topixDailyPrice) replaceDB(db *gorm.DB) topixDailyPrice {
	t.topixDailyPriceDo.ReplaceDB(db)
	return t
}

type topixDailyPriceDo struct{ gen.DO }

type ITopixDailyPriceDo interface {
	gen.SubQuery
	Debug() ITopixDailyPriceDo
	WithContext(ctx context.Context) ITopixDailyPriceDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITopixDailyPriceDo
	WriteDB() ITopixDailyPriceDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITopixDailyPriceDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITopixDailyPriceDo
	Not(conds ...gen.Condition) ITopixDailyPriceDo
	Or(conds ...gen.Condition) ITopixDailyPriceDo
	Select(conds ...field.Expr) ITopixDailyPriceDo
	Where(conds ...gen.Condition) ITopixDailyPriceDo
	Order(conds ...field.Expr) ITopixDailyPriceDo
	Distinct(cols ...field.Expr) ITopixDailyPriceDo
	Omit(cols ...field.Expr) ITopixDailyPriceDo
	Join(table schema.Tabler, on ...field.Expr) ITopixDailyPriceDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITopixDailyPriceDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITopixDailyPriceDo
	Group(cols ...field.Expr) ITopixDailyPriceDo
	Having(conds ...gen.Condition) ITopixDailyPriceDo
	Limit(limit int) ITopixDailyPriceDo
	Offset(offset int) ITopixDailyPriceDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITopixDailyPriceDo
	Unscoped() ITopixDailyPriceDo
	Create(values ...*gen_model.TopixDailyPrice) error
	CreateInBatches(values []*gen_model.TopixDailyPrice, batchSize int) error
	Save(values ...*gen_model.TopixDailyPrice) error
	First() (*gen_model.TopixDailyPrice, error)
	Take() (*gen_model.TopixDailyPrice, error)
	Last() (*gen_model.TopixDailyPrice, error)
	Find() ([]*gen_model.TopixDailyPrice, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*gen_model.TopixDailyPrice, err error)
	FindInBatches(result *[]*gen_model.TopixDailyPrice, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*gen_model.TopixDailyPrice) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITopixDailyPriceDo
	Assign(attrs ...field.AssignExpr) ITopixDailyPriceDo
	Joins(fields ...field.RelationField) ITopixDailyPriceDo
	Preload(fields ...field.RelationField) ITopixDailyPriceDo
	FirstOrInit() (*gen_model.TopixDailyPrice, error)
	FirstOrCreate() (*gen_model.TopixDailyPrice, error)
	FindByPage(offset int, limit int) (result []*gen_model.TopixDailyPrice, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITopixDailyPriceDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t topixDailyPriceDo) Debug() ITopixDailyPriceDo {
	return t.withDO(t.DO.Debug())
}

func (t topixDailyPriceDo) WithContext(ctx context.Context) ITopixDailyPriceDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t topixDailyPriceDo) ReadDB() ITopixDailyPriceDo {
	return t.Clauses(dbresolver.Read)
}

func (t topixDailyPriceDo) WriteDB() ITopixDailyPriceDo {
	return t.Clauses(dbresolver.Write)
}

func (t topixDailyPriceDo) Session(config *gorm.Session) ITopixDailyPriceDo {
	return t.withDO(t.DO.Session(config))
}

func (t topixDailyPriceDo) Clauses(conds ...clause.Expression) ITopixDailyPriceDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t topixDailyPriceDo) Returning(value interface{}, columns ...string) ITopixDailyPriceDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t topixDailyPriceDo) Not(conds ...gen.Condition) ITopixDailyPriceDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t topixDailyPriceDo) Or(conds ...gen.Condition) ITopixDailyPriceDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t topixDailyPriceDo) Select(conds ...field.Expr) ITopixDailyPriceDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t topixDailyPriceDo) Where(conds ...gen.Condition) ITopixDailyPriceDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t topixDailyPriceDo) Order(conds ...field.Expr) ITopixDailyPriceDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t topixDailyPriceDo) Distinct(cols ...field.Expr) ITopixDailyPriceDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t topixDailyPriceDo) Omit(cols ...field.Expr) ITopixDailyPriceDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t topixDailyPriceDo) Join(table schema.Tabler, on ...field.Expr) ITopixDailyPriceDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t topixDailyPriceDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITopixDailyPriceDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t topixDailyPriceDo) RightJoin(table schema.Tabler, on ...field.Expr) ITopixDailyPriceDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t topixDailyPriceDo) Group(cols ...field.Expr) ITopixDailyPriceDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t topixDailyPriceDo) Having(conds ...gen.Condition) ITopixDailyPriceDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t topixDailyPriceDo) Limit(limit int) ITopixDailyPriceDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t topixDailyPriceDo) Offset(offset int) ITopixDailyPriceDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t topixDailyPriceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITopixDailyPriceDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t topixDailyPriceDo) Unscoped() ITopixDailyPriceDo {
	return t.withDO(t.DO.Unscoped())
}

func (t topixDailyPriceDo) Create(values ...*gen_model.TopixDailyPrice) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t topixDailyPriceDo) CreateInBatches(values []*gen_model.TopixDailyPrice, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t topixDailyPriceDo) Save(values ...*gen_model.TopixDailyPrice) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t topixDailyPriceDo) First() (*gen_model.TopixDailyPrice, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.TopixDailyPrice), nil
	}
}

func (t topixDailyPriceDo) Take() (*gen_model.TopixDailyPrice, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.TopixDailyPrice), nil
	}
}

func (t topixDailyPriceDo) Last() (*gen_model.TopixDailyPrice, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.TopixDailyPrice), nil
	}
}

func (t topixDailyPriceDo) Find() ([]*gen_model.TopixDailyPrice, error) {
	result, err := t.DO.Find()
	return result.([]*gen_model.TopixDailyPrice), err
}

func (t topixDailyPriceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*gen_model.TopixDailyPrice, err error) {
	buf := make([]*gen_model.TopixDailyPrice, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t topixDailyPriceDo) FindInBatches(result *[]*gen_model.TopixDailyPrice, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t topixDailyPriceDo) Attrs(attrs ...field.AssignExpr) ITopixDailyPriceDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t topixDailyPriceDo) Assign(attrs ...field.AssignExpr) ITopixDailyPriceDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t topixDailyPriceDo) Joins(fields ...field.RelationField) ITopixDailyPriceDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t topixDailyPriceDo) Preload(fields ...field.RelationField) ITopixDailyPriceDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t topixDailyPriceDo) FirstOrInit() (*gen_model.TopixDailyPrice, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.TopixDailyPrice), nil
	}
}

func (t topixDailyPriceDo) FirstOrCreate() (*gen_model.TopixDailyPrice, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.TopixDailyPrice), nil
	}
}

func (t topixDailyPriceDo) FindByPage(offset int, limit int) (result []*gen_model.TopixDailyPrice, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t topixDailyPriceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t topixDailyPriceDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t topixDailyPriceDo) Delete(models ...*gen_model.TopixDailyPrice) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *topixDailyPriceDo) withDO(do gen.Dao) *topixDailyPriceDo {
	t.DO = *do.(*gen.DO)
	return t
}
