// Code generated by MockGen. DO NOT EDIT.
// Source: db.go
//
// Generated by this command:
//
//	mockgen -source=db.go -package=mock_driver -destination=../mock/driver/db.go
//

// Package mock_driver is a generated GoMock package.
package mock_driver
