// Code generated by MockGen. DO NOT EDIT.
// Source: gorm.go
//
// Generated by this command:
//
//	mockgen -source=gorm.go -package=mock_driver -destination=../mock/driver/gorm.go
//

// Package mock_driver is a generated GoMock package.
package mock_driver
