// Code generated by MockGen. DO NOT EDIT.
// Source: http_server.go
//
// Generated by this command:
//
//	mockgen -source=http_server.go -package=mock_driver -destination=../mock/driver/http_server.go
//

// Package mock_driver is a generated GoMock package.
package mock_driver

import (
	http "net/http"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockHTTPServer is a mock of HTTPServer interface.
type MockHTTPServer struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPServerMockRecorder
	isgomock struct{}
}

// MockHTTPServerMockRecorder is the mock recorder for MockHTTPServer.
type MockHTTPServerMockRecorder struct {
	mock *MockHTTPServer
}

// NewMockHTTPServer creates a new mock instance.
func NewMockHTTPServer(ctrl *gomock.Controller) *MockHTTPServer {
	mock := &MockHTTPServer{ctrl: ctrl}
	mock.recorder = &MockHTTPServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPServer) EXPECT() *MockHTTPServerMockRecorder {
	return m.recorder
}

// GetQueryParam mocks base method.
func (m *MockHTTPServer) GetQueryParam(r *http.Request, key string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQueryParam", r, key)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetQueryParam indicates an expected call of GetQueryParam.
func (mr *MockHTTPServerMockRecorder) GetQueryParam(r, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQueryParam", reflect.TypeOf((*MockHTTPServer)(nil).GetQueryParam), r, key)
}

// GetQueryParamDate mocks base method.
func (m *MockHTTPServer) GetQueryParamDate(r *http.Request, key, layout string) (*time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQueryParamDate", r, key, layout)
	ret0, _ := ret[0].(*time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQueryParamDate indicates an expected call of GetQueryParamDate.
func (mr *MockHTTPServerMockRecorder) GetQueryParamDate(r, key, layout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQueryParamDate", reflect.TypeOf((*MockHTTPServer)(nil).GetQueryParamDate), r, key, layout)
}

// GetQueryParamInt mocks base method.
func (m *MockHTTPServer) GetQueryParamInt(r *http.Request, key string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQueryParamInt", r, key)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQueryParamInt indicates an expected call of GetQueryParamInt.
func (mr *MockHTTPServerMockRecorder) GetQueryParamInt(r, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQueryParamInt", reflect.TypeOf((*MockHTTPServer)(nil).GetQueryParamInt), r, key)
}

// ParseJSONBody mocks base method.
func (m *MockHTTPServer) ParseJSONBody(r *http.Request, v any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseJSONBody", r, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// ParseJSONBody indicates an expected call of ParseJSONBody.
func (mr *MockHTTPServerMockRecorder) ParseJSONBody(r, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseJSONBody", reflect.TypeOf((*MockHTTPServer)(nil).ParseJSONBody), r, v)
}
