// Code generated by MockGen. DO NOT EDIT.
// Source: j_quants_api_models.go
//
// Generated by this command:
//
//	mockgen -source=j_quants_api_models.go -package=mock_driver -destination=../mock/driver/j_quants_api_models.go
//

// Package mock_driver is a generated GoMock package.
package mock_driver
