// Code generated by MockGen. DO NOT EDIT.
// Source: msqldump.go
//
// Generated by this command:
//
//	mockgen -source=msqldump.go -package=mock_driver -destination=../mock/driver/msqldump.go
//

// Package mock_driver is a generated GoMock package.
package mock_driver
