// Code generated by MockGen. DO NOT EDIT.
// Source: redis.go
//
// Generated by this command:
//
//	mockgen -source=redis.go -package=mock_driver -destination=../mock/driver/redis.go
//

// Package mock_driver is a generated GoMock package.
package mock_driver
