// Code generated by MockGen. DO NOT EDIT.
// Source: slack.go
//
// Generated by this command:
//
//	mockgen -source=slack.go -package=mock_driver -destination=../mock/driver/slack.go
//

// Package mock_driver is a generated GoMock package.
package mock_driver
