// Code generated by MockGen. DO NOT EDIT.
// Source: stock_api.go
//
// Generated by this command:
//
//	mockgen -source=stock_api.go -package=mock_driver -destination=../mock/driver/stock_api.go
//

// Package mock_driver is a generated GoMock package.
package mock_driver
