// Code generated by MockGen. DO NOT EDIT.
// Source: yahoo_finance_models.go
//
// Generated by this command:
//
//	mockgen -source=yahoo_finance_models.go -package=mock_driver -destination=../mock/driver/yahoo_finance_models.go
//

// Package mock_driver is a generated GoMock package.
package mock_driver
