// Code generated by MockGen. DO NOT EDIT.
// Source: backtest_interactor.go
//
// Generated by this command:
//
//	mockgen -source=backtest_interactor.go -package=mock_usecase -destination=../mock/usecase/backtest_interactor.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/Code0716/stock-price-repository/models"
	gomock "go.uber.org/mock/gomock"
)

// MockBacktestInteractor is a mock of BacktestInteractor interface.
type MockBacktestInteractor struct {
	ctrl     *gomock.Controller
	recorder *MockBacktestInteractorMockRecorder
	isgomock struct{}
}

// MockBacktestInteractorMockRecorder is the mock recorder for MockBacktestInteractor.
type MockBacktestInteractorMockRecorder struct {
	mock *MockBacktestInteractor
}

// NewMockBacktestInteractor creates a new mock instance.
func NewMockBacktestInteractor(ctrl *gomock.Controller) *MockBacktestInteractor {
	mock := &MockBacktestInteractor{ctrl: ctrl}
	mock.recorder = &MockBacktestInteractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBacktestInteractor) EXPECT() *MockBacktestInteractorMockRecorder {
	return m.recorder
}

// GetBacktestComparison mocks base method.
func (m *MockBacktestInteractor) GetBacktestComparison(ctx context.Context, symbol string, from, to *time.Time, params models.BacktestParams) (*models.BacktestComparison, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBacktestComparison", ctx, symbol, from, to, params)
	ret0, _ := ret[0].(*models.BacktestComparison)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBacktestComparison indicates an expected call of GetBacktestComparison.
func (mr *MockBacktestInteractorMockRecorder) GetBacktestComparison(ctx, symbol, from, to, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBacktestComparison", reflect.TypeOf((*MockBacktestInteractor)(nil).GetBacktestComparison), ctx, symbol, from, to, params)
}
