// Code generated by MockGen. DO NOT EDIT.
// Source: create_daily_avoid_stocks.go
//
// Generated by this command:
//
//	mockgen -source=create_daily_avoid_stocks.go -package=mock_usecase -destination=../mock/usecase/create_daily_avoid_stocks.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockCreateDailyAvoidStocksInteractor is a mock of CreateDailyAvoidStocksInteractor interface.
type MockCreateDailyAvoidStocksInteractor struct {
	ctrl     *gomock.Controller
	recorder *MockCreateDailyAvoidStocksInteractorMockRecorder
	isgomock struct{}
}

// MockCreateDailyAvoidStocksInteractorMockRecorder is the mock recorder for MockCreateDailyAvoidStocksInteractor.
type MockCreateDailyAvoidStocksInteractorMockRecorder struct {
	mock *MockCreateDailyAvoidStocksInteractor
}

// NewMockCreateDailyAvoidStocksInteractor creates a new mock instance.
func NewMockCreateDailyAvoidStocksInteractor(ctrl *gomock.Controller) *MockCreateDailyAvoidStocksInteractor {
	mock := &MockCreateDailyAvoidStocksInteractor{ctrl: ctrl}
	mock.recorder = &MockCreateDailyAvoidStocksInteractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateDailyAvoidStocksInteractor) EXPECT() *MockCreateDailyAvoidStocksInteractorMockRecorder {
	return m.recorder
}

// CreateDailyAvoidStocks mocks base method.
func (m *MockCreateDailyAvoidStocksInteractor) CreateDailyAvoidStocks(ctx context.Context, now time.Time, asOf *time.Time, concurrency int, force bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDailyAvoidStocks", ctx, now, asOf, concurrency, force)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDailyAvoidStocks indicates an expected call of CreateDailyAvoidStocks.
func (mr *MockCreateDailyAvoidStocksInteractorMockRecorder) CreateDailyAvoidStocks(ctx, now, asOf, concurrency, force any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDailyAvoidStocks", reflect.TypeOf((*MockCreateDailyAvoidStocksInteractor)(nil).CreateDailyAvoidStocks), ctx, now, asOf, concurrency, force)
}
