// Code generated by MockGen. DO NOT EDIT.
// Source: create_daily_stock_picks.go
//
// Generated by this command:
//
//	mockgen -source=create_daily_stock_picks.go -package=mock_usecase -destination=../mock/usecase/create_daily_stock_picks.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockCreateDailyStockPicksInteractor is a mock of CreateDailyStockPicksInteractor interface.
type MockCreateDailyStockPicksInteractor struct {
	ctrl     *gomock.Controller
	recorder *MockCreateDailyStockPicksInteractorMockRecorder
	isgomock struct{}
}

// MockCreateDailyStockPicksInteractorMockRecorder is the mock recorder for MockCreateDailyStockPicksInteractor.
type MockCreateDailyStockPicksInteractorMockRecorder struct {
	mock *MockCreateDailyStockPicksInteractor
}

// NewMockCreateDailyStockPicksInteractor creates a new mock instance.
func NewMockCreateDailyStockPicksInteractor(ctrl *gomock.Controller) *MockCreateDailyStockPicksInteractor {
	mock := &MockCreateDailyStockPicksInteractor{ctrl: ctrl}
	mock.recorder = &MockCreateDailyStockPicksInteractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateDailyStockPicksInteractor) EXPECT() *MockCreateDailyStockPicksInteractorMockRecorder {
	return m.recorder
}

// CreateDailyStockPicks mocks base method.
func (m *MockCreateDailyStockPicksInteractor) CreateDailyStockPicks(ctx context.Context, now time.Time, topN, maxPerSector, concurrency int, force bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDailyStockPicks", ctx, now, topN, maxPerSector, concurrency, force)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDailyStockPicks indicates an expected call of CreateDailyStockPicks.
func (mr *MockCreateDailyStockPicksInteractorMockRecorder) CreateDailyStockPicks(ctx, now, topN, maxPerSector, concurrency, force any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDailyStockPicks", reflect.TypeOf((*MockCreateDailyStockPicksInteractor)(nil).CreateDailyStockPicks), ctx, now, topN, maxPerSector, concurrency, force)
}
