// Code generated by MockGen. DO NOT EDIT.
// Source: create_quiz_daily_universe.go
//
// Generated by this command:
//
//	mockgen -source=create_quiz_daily_universe.go -package=mock_usecase -destination=../mock/usecase/create_quiz_daily_universe.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockCreateQuizDailyUniverseInteractor is a mock of CreateQuizDailyUniverseInteractor interface.
type MockCreateQuizDailyUniverseInteractor struct {
	ctrl     *gomock.Controller
	recorder *MockCreateQuizDailyUniverseInteractorMockRecorder
	isgomock struct{}
}

// MockCreateQuizDailyUniverseInteractorMockRecorder is the mock recorder for MockCreateQuizDailyUniverseInteractor.
type MockCreateQuizDailyUniverseInteractorMockRecorder struct {
	mock *MockCreateQuizDailyUniverseInteractor
}

// NewMockCreateQuizDailyUniverseInteractor creates a new mock instance.
func NewMockCreateQuizDailyUniverseInteractor(ctrl *gomock.Controller) *MockCreateQuizDailyUniverseInteractor {
	mock := &MockCreateQuizDailyUniverseInteractor{ctrl: ctrl}
	mock.recorder = &MockCreateQuizDailyUniverseInteractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateQuizDailyUniverseInteractor) EXPECT() *MockCreateQuizDailyUniverseInteractorMockRecorder {
	return m.recorder
}

// CreateQuizDailyUniverse mocks base method.
func (m *MockCreateQuizDailyUniverseInteractor) CreateQuizDailyUniverse(ctx context.Context, now time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateQuizDailyUniverse", ctx, now)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateQuizDailyUniverse indicates an expected call of CreateQuizDailyUniverse.
func (mr *MockCreateQuizDailyUniverseInteractorMockRecorder) CreateQuizDailyUniverse(ctx, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateQuizDailyUniverse", reflect.TypeOf((*MockCreateQuizDailyUniverseInteractor)(nil).CreateQuizDailyUniverse), ctx, now)
}
