// Code generated by MockGen. DO NOT EDIT.
// Source: daytrade_interactor.go
//
// Generated by this command:
//
//	mockgen -source=daytrade_interactor.go -package=mock_usecase -destination=../mock/usecase/daytrade_interactor.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	io "io"
	reflect "reflect"
	time "time"

	models "github.com/Code0716/stock-price-repository/models"
	gomock "go.uber.org/mock/gomock"
)

// MockDaytradeInteractor is a mock of DaytradeInteractor interface.
type MockDaytradeInteractor struct {
	ctrl     *gomock.Controller
	recorder *MockDaytradeInteractorMockRecorder
	isgomock struct{}
}

// MockDaytradeInteractorMockRecorder is the mock recorder for MockDaytradeInteractor.
type MockDaytradeInteractorMockRecorder struct {
	mock *MockDaytradeInteractor
}

// NewMockDaytradeInteractor creates a new mock instance.
func NewMockDaytradeInteractor(ctrl *gomock.Controller) *MockDaytradeInteractor {
	mock := &MockDaytradeInteractor{ctrl: ctrl}
	mock.recorder = &MockDaytradeInteractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDaytradeInteractor) EXPECT() *MockDaytradeInteractorMockRecorder {
	return m.recorder
}

// GetCoveredRange mocks base method.
func (m *MockDaytradeInteractor) GetCoveredRange(ctx context.Context) (*time.Time, *time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCoveredRange", ctx)
	ret0, _ := ret[0].(*time.Time)
	ret1, _ := ret[1].(*time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetCoveredRange indicates an expected call of GetCoveredRange.
func (mr *MockDaytradeInteractorMockRecorder) GetCoveredRange(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCoveredRange", reflect.TypeOf((*MockDaytradeInteractor)(nil).GetCoveredRange), ctx)
}

// GetExecutionsByDate mocks base method.
func (m *MockDaytradeInteractor) GetExecutionsByDate(ctx context.Context, date time.Time) ([]*models.DaytradeExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExecutionsByDate", ctx, date)
	ret0, _ := ret[0].([]*models.DaytradeExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExecutionsByDate indicates an expected call of GetExecutionsByDate.
func (mr *MockDaytradeInteractorMockRecorder) GetExecutionsByDate(ctx, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExecutionsByDate", reflect.TypeOf((*MockDaytradeInteractor)(nil).GetExecutionsByDate), ctx, date)
}

// GetInsights mocks base method.
func (m *MockDaytradeInteractor) GetInsights(ctx context.Context, from, to *time.Time) (*models.DaytradeInsights, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInsights", ctx, from, to)
	ret0, _ := ret[0].(*models.DaytradeInsights)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInsights indicates an expected call of GetInsights.
func (mr *MockDaytradeInteractorMockRecorder) GetInsights(ctx, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInsights", reflect.TypeOf((*MockDaytradeInteractor)(nil).GetInsights), ctx, from, to)
}

// GetPeriodStats mocks base method.
func (m *MockDaytradeInteractor) GetPeriodStats(ctx context.Context, from, to *time.Time) (*models.DaytradePeriodStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPeriodStats", ctx, from, to)
	ret0, _ := ret[0].(*models.DaytradePeriodStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPeriodStats indicates an expected call of GetPeriodStats.
func (mr *MockDaytradeInteractorMockRecorder) GetPeriodStats(ctx, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPeriodStats", reflect.TypeOf((*MockDaytradeInteractor)(nil).GetPeriodStats), ctx, from, to)
}

// GetSummary mocks base method.
func (m *MockDaytradeInteractor) GetSummary(ctx context.Context, from, to *time.Time, g models.DaytradeSummaryGranularity) ([]*models.DaytradeSummaryBucket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSummary", ctx, from, to, g)
	ret0, _ := ret[0].([]*models.DaytradeSummaryBucket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSummary indicates an expected call of GetSummary.
func (mr *MockDaytradeInteractorMockRecorder) GetSummary(ctx, from, to, g any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSummary", reflect.TypeOf((*MockDaytradeInteractor)(nil).GetSummary), ctx, from, to, g)
}

// GetSummaryByTickerSymbol mocks base method.
func (m *MockDaytradeInteractor) GetSummaryByTickerSymbol(ctx context.Context, from, to *time.Time) ([]*models.DaytradeSymbolSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSummaryByTickerSymbol", ctx, from, to)
	ret0, _ := ret[0].([]*models.DaytradeSymbolSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSummaryByTickerSymbol indicates an expected call of GetSummaryByTickerSymbol.
func (mr *MockDaytradeInteractorMockRecorder) GetSummaryByTickerSymbol(ctx, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSummaryByTickerSymbol", reflect.TypeOf((*MockDaytradeInteractor)(nil).GetSummaryByTickerSymbol), ctx, from, to)
}

// GetTagStats mocks base method.
func (m *MockDaytradeInteractor) GetTagStats(ctx context.Context, from, to *time.Time) ([]models.DaytradeTagStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagStats", ctx, from, to)
	ret0, _ := ret[0].([]models.DaytradeTagStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTagStats indicates an expected call of GetTagStats.
func (mr *MockDaytradeInteractorMockRecorder) GetTagStats(ctx, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagStats", reflect.TypeOf((*MockDaytradeInteractor)(nil).GetTagStats), ctx, from, to)
}

// GetTrades mocks base method.
func (m *MockDaytradeInteractor) GetTrades(ctx context.Context, from, to *time.Time) ([]*models.DaytradeTradeWithNote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrades", ctx, from, to)
	ret0, _ := ret[0].([]*models.DaytradeTradeWithNote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrades indicates an expected call of GetTrades.
func (mr *MockDaytradeInteractorMockRecorder) GetTrades(ctx, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrades", reflect.TypeOf((*MockDaytradeInteractor)(nil).GetTrades), ctx, from, to)
}

// ImportSBICsv mocks base method.
func (m *MockDaytradeInteractor) ImportSBICsv(ctx context.Context, r io.Reader) (*models.DaytradeImportResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportSBICsv", ctx, r)
	ret0, _ := ret[0].(*models.DaytradeImportResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImportSBICsv indicates an expected call of ImportSBICsv.
func (mr *MockDaytradeInteractorMockRecorder) ImportSBICsv(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportSBICsv", reflect.TypeOf((*MockDaytradeInteractor)(nil).ImportSBICsv), ctx, r)
}

// UpsertTradeNote mocks base method.
func (m *MockDaytradeInteractor) UpsertTradeNote(ctx context.Context, rec *models.DaytradeTradeNoteRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertTradeNote", ctx, rec)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertTradeNote indicates an expected call of UpsertTradeNote.
func (mr *MockDaytradeInteractorMockRecorder) UpsertTradeNote(ctx, rec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertTradeNote", reflect.TypeOf((*MockDaytradeInteractor)(nil).UpsertTradeNote), ctx, rec)
}
