// Code generated by MockGen. DO NOT EDIT.
// Source: get_high_volume_stock_brands.go
//
// Generated by this command:
//
//	mockgen -source=get_high_volume_stock_brands.go -package=mock_usecase -destination=../mock/usecase/get_high_volume_stock_brands.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	models "github.com/Code0716/stock-price-repository/models"
	gomock "go.uber.org/mock/gomock"
)

// MockGetHighVolumeStockBrandsUseCase is a mock of GetHighVolumeStockBrandsUseCase interface.
type MockGetHighVolumeStockBrandsUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetHighVolumeStockBrandsUseCaseMockRecorder
	isgomock struct{}
}

// MockGetHighVolumeStockBrandsUseCaseMockRecorder is the mock recorder for MockGetHighVolumeStockBrandsUseCase.
type MockGetHighVolumeStockBrandsUseCaseMockRecorder struct {
	mock *MockGetHighVolumeStockBrandsUseCase
}

// NewMockGetHighVolumeStockBrandsUseCase creates a new mock instance.
func NewMockGetHighVolumeStockBrandsUseCase(ctrl *gomock.Controller) *MockGetHighVolumeStockBrandsUseCase {
	mock := &MockGetHighVolumeStockBrandsUseCase{ctrl: ctrl}
	mock.recorder = &MockGetHighVolumeStockBrandsUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetHighVolumeStockBrandsUseCase) EXPECT() *MockGetHighVolumeStockBrandsUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetHighVolumeStockBrandsUseCase) Execute(ctx context.Context) ([]*models.HighVolumeStockBrand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx)
	ret0, _ := ret[0].([]*models.HighVolumeStockBrand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetHighVolumeStockBrandsUseCaseMockRecorder) Execute(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetHighVolumeStockBrandsUseCase)(nil).Execute), ctx)
}

// ExecuteWithPagination mocks base method.
func (m *MockGetHighVolumeStockBrandsUseCase) ExecuteWithPagination(ctx context.Context, symbolFrom string, limit int) (*models.PaginatedHighVolumeStockBrands, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteWithPagination", ctx, symbolFrom, limit)
	ret0, _ := ret[0].(*models.PaginatedHighVolumeStockBrands)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteWithPagination indicates an expected call of ExecuteWithPagination.
func (mr *MockGetHighVolumeStockBrandsUseCaseMockRecorder) ExecuteWithPagination(ctx, symbolFrom, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteWithPagination", reflect.TypeOf((*MockGetHighVolumeStockBrandsUseCase)(nil).ExecuteWithPagination), ctx, symbolFrom, limit)
}
