// Code generated by MockGen. DO NOT EDIT.
// Source: grade_quiz_answers.go
//
// Generated by this command:
//
//	mockgen -source=grade_quiz_answers.go -package=mock_usecase -destination=../mock/usecase/grade_quiz_answers.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGradeQuizAnswersInteractor is a mock of GradeQuizAnswersInteractor interface.
type MockGradeQuizAnswersInteractor struct {
	ctrl     *gomock.Controller
	recorder *MockGradeQuizAnswersInteractorMockRecorder
	isgomock struct{}
}

// MockGradeQuizAnswersInteractorMockRecorder is the mock recorder for MockGradeQuizAnswersInteractor.
type MockGradeQuizAnswersInteractorMockRecorder struct {
	mock *MockGradeQuizAnswersInteractor
}

// NewMockGradeQuizAnswersInteractor creates a new mock instance.
func NewMockGradeQuizAnswersInteractor(ctrl *gomock.Controller) *MockGradeQuizAnswersInteractor {
	mock := &MockGradeQuizAnswersInteractor{ctrl: ctrl}
	mock.recorder = &MockGradeQuizAnswersInteractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGradeQuizAnswersInteractor) EXPECT() *MockGradeQuizAnswersInteractorMockRecorder {
	return m.recorder
}

// GradeQuizAnswers mocks base method.
func (m *MockGradeQuizAnswersInteractor) GradeQuizAnswers(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GradeQuizAnswers", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// GradeQuizAnswers indicates an expected call of GradeQuizAnswers.
func (mr *MockGradeQuizAnswersInteractorMockRecorder) GradeQuizAnswers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GradeQuizAnswers", reflect.TypeOf((*MockGradeQuizAnswersInteractor)(nil).GradeQuizAnswers), ctx)
}
