// Code generated by MockGen. DO NOT EDIT.
// Source: market_calendar_interactor.go
//
// Generated by this command:
//
//	mockgen -source=market_calendar_interactor.go -package=mock_usecase -destination=../mock/usecase/market_calendar_interactor.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"
	time "time"

	usecase "github.com/Code0716/stock-price-repository/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockMarketCalendarInteractor is a mock of MarketCalendarInteractor interface.
type MockMarketCalendarInteractor struct {
	ctrl     *gomock.Controller
	recorder *MockMarketCalendarInteractorMockRecorder
	isgomock struct{}
}

// MockMarketCalendarInteractorMockRecorder is the mock recorder for MockMarketCalendarInteractor.
type MockMarketCalendarInteractorMockRecorder struct {
	mock *MockMarketCalendarInteractor
}

// NewMockMarketCalendarInteractor creates a new mock instance.
func NewMockMarketCalendarInteractor(ctrl *gomock.Controller) *MockMarketCalendarInteractor {
	mock := &MockMarketCalendarInteractor{ctrl: ctrl}
	mock.recorder = &MockMarketCalendarInteractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMarketCalendarInteractor) EXPECT() *MockMarketCalendarInteractorMockRecorder {
	return m.recorder
}

// GetMarketCalendar mocks base method.
func (m *MockMarketCalendarInteractor) GetMarketCalendar(ctx context.Context, from, to time.Time) (*usecase.MarketCalendar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMarketCalendar", ctx, from, to)
	ret0, _ := ret[0].(*usecase.MarketCalendar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMarketCalendar indicates an expected call of GetMarketCalendar.
func (mr *MockMarketCalendarInteractorMockRecorder) GetMarketCalendar(ctx, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMarketCalendar", reflect.TypeOf((*MockMarketCalendarInteractor)(nil).GetMarketCalendar), ctx, from, to)
}
