// Code generated by MockGen. DO NOT EDIT.
// Source: notification_history_interactor.go
//
// Generated by this command:
//
//	mockgen -source=notification_history_interactor.go -package=mock_usecase -destination=../mock/usecase/notification_history_interactor.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	models "github.com/Code0716/stock-price-repository/models"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificationHistoryInteractor is a mock of NotificationHistoryInteractor interface.
type MockNotificationHistoryInteractor struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationHistoryInteractorMockRecorder
	isgomock struct{}
}

// MockNotificationHistoryInteractorMockRecorder is the mock recorder for MockNotificationHistoryInteractor.
type MockNotificationHistoryInteractorMockRecorder struct {
	mock *MockNotificationHistoryInteractor
}

// NewMockNotificationHistoryInteractor creates a new mock instance.
func NewMockNotificationHistoryInteractor(ctrl *gomock.Controller) *MockNotificationHistoryInteractor {
	mock := &MockNotificationHistoryInteractor{ctrl: ctrl}
	mock.recorder = &MockNotificationHistoryInteractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationHistoryInteractor) EXPECT() *MockNotificationHistoryInteractorMockRecorder {
	return m.recorder
}

// GetNotificationHistories mocks base method.
func (m *MockNotificationHistoryInteractor) GetNotificationHistories(ctx context.Context, filter *models.NotificationHistoryFilter) (*models.PaginatedNotificationHistories, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotificationHistories", ctx, filter)
	ret0, _ := ret[0].(*models.PaginatedNotificationHistories)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotificationHistories indicates an expected call of GetNotificationHistories.
func (mr *MockNotificationHistoryInteractorMockRecorder) GetNotificationHistories(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotificationHistories", reflect.TypeOf((*MockNotificationHistoryInteractor)(nil).GetNotificationHistories), ctx, filter)
}
