// Code generated by MockGen. DO NOT EDIT.
// Source: sector_performance_interactor.go
//
// Generated by this command:
//
//	mockgen -source=sector_performance_interactor.go -package=mock_usecase -destination=../mock/usecase/sector_performance_interactor.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/Code0716/stock-price-repository/models"
	gomock "go.uber.org/mock/gomock"
)

// MockSectorPerformanceInteractor is a mock of SectorPerformanceInteractor interface.
type MockSectorPerformanceInteractor struct {
	ctrl     *gomock.Controller
	recorder *MockSectorPerformanceInteractorMockRecorder
	isgomock struct{}
}

// MockSectorPerformanceInteractorMockRecorder is the mock recorder for MockSectorPerformanceInteractor.
type MockSectorPerformanceInteractorMockRecorder struct {
	mock *MockSectorPerformanceInteractor
}

// NewMockSectorPerformanceInteractor creates a new mock instance.
func NewMockSectorPerformanceInteractor(ctrl *gomock.Controller) *MockSectorPerformanceInteractor {
	mock := &MockSectorPerformanceInteractor{ctrl: ctrl}
	mock.recorder = &MockSectorPerformanceInteractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSectorPerformanceInteractor) EXPECT() *MockSectorPerformanceInteractorMockRecorder {
	return m.recorder
}

// GetSectorPerformance mocks base method.
func (m *MockSectorPerformanceInteractor) GetSectorPerformance(ctx context.Context, from, to time.Time, granularity string) (*models.SectorPerformance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSectorPerformance", ctx, from, to, granularity)
	ret0, _ := ret[0].(*models.SectorPerformance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSectorPerformance indicates an expected call of GetSectorPerformance.
func (mr *MockSectorPerformanceInteractorMockRecorder) GetSectorPerformance(ctx, from, to, granularity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSectorPerformance", reflect.TypeOf((*MockSectorPerformanceInteractor)(nil).GetSectorPerformance), ctx, from, to, granularity)
}
