// Code generated by MockGen. DO NOT EDIT.
// Source: update_stock_brands.go
//
// Generated by this command:
//
//	mockgen -source=update_stock_brands.go -package=mock_usecase -destination=../mock/usecase/update_stock_brands.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase
