// Code generated by MockGen. DO NOT EDIT.
// Source: valuation_interactor.go
//
// Generated by this command:
//
//	mockgen -source=valuation_interactor.go -package=mock_usecase -destination=../mock/usecase/valuation_interactor.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	models "github.com/Code0716/stock-price-repository/models"
	gomock "go.uber.org/mock/gomock"
)

// MockValuationInteractor is a mock of ValuationInteractor interface.
type MockValuationInteractor struct {
	ctrl     *gomock.Controller
	recorder *MockValuationInteractorMockRecorder
	isgomock struct{}
}

// MockValuationInteractorMockRecorder is the mock recorder for MockValuationInteractor.
type MockValuationInteractorMockRecorder struct {
	mock *MockValuationInteractor
}

// NewMockValuationInteractor creates a new mock instance.
func NewMockValuationInteractor(ctrl *gomock.Controller) *MockValuationInteractor {
	mock := &MockValuationInteractor{ctrl: ctrl}
	mock.recorder = &MockValuationInteractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValuationInteractor) EXPECT() *MockValuationInteractorMockRecorder {
	return m.recorder
}

// GetValuation mocks base method.
func (m *MockValuationInteractor) GetValuation(ctx context.Context, symbol string) (*models.Valuation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValuation", ctx, symbol)
	ret0, _ := ret[0].(*models.Valuation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValuation indicates an expected call of GetValuation.
func (mr *MockValuationInteractorMockRecorder) GetValuation(ctx, symbol any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValuation", reflect.TypeOf((*MockValuationInteractor)(nil).GetValuation), ctx, symbol)
}
