// Code generated by MockGen. DO NOT EDIT.
// Source: box_client.go
//
// Generated by this command:
//
//	mockgen -source=box_client.go -package=mock_gateway -destination=../../mock/gateway/box_client.go
//

// Package mock_gateway is a generated GoMock package.
package mock_gateway

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBoxClient is a mock of BoxClient interface.
type MockBoxClient struct {
	ctrl     *gomock.Controller
	recorder *MockBoxClientMockRecorder
	isgomock struct{}
}

// MockBoxClientMockRecorder is the mock recorder for MockBoxClient.
type MockBoxClientMockRecorder struct {
	mock *MockBoxClient
}

// NewMockBoxClient creates a new mock instance.
func NewMockBoxClient(ctrl *gomock.Controller) *MockBoxClient {
	mock := &MockBoxClient{ctrl: ctrl}
	mock.recorder = &MockBoxClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBoxClient) EXPECT() *MockBoxClientMockRecorder {
	return m.recorder
}

// UploadFile mocks base method.
func (m *MockBoxClient) UploadFile(ctx context.Context, localFilePath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFile", ctx, localFilePath)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockBoxClientMockRecorder) UploadFile(ctx, localFilePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockBoxClient)(nil).UploadFile), ctx, localFilePath)
}
