// Code generated by MockGen. DO NOT EDIT.
// Source: economic_calendar_client.go
//
// Generated by this command:
//
//	mockgen -source=economic_calendar_client.go -package=mock_gateway -destination=../../mock/gateway/economic_calendar_client.go
//

// Package mock_gateway is a generated GoMock package.
package mock_gateway

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEconomicCalendarClient is a mock of EconomicCalendarClient interface.
type MockEconomicCalendarClient struct {
	ctrl     *gomock.Controller
	recorder *MockEconomicCalendarClientMockRecorder
	isgomock struct{}
}

// MockEconomicCalendarClientMockRecorder is the mock recorder for MockEconomicCalendarClient.
type MockEconomicCalendarClientMockRecorder struct {
	mock *MockEconomicCalendarClient
}

// NewMockEconomicCalendarClient creates a new mock instance.
func NewMockEconomicCalendarClient(ctrl *gomock.Controller) *MockEconomicCalendarClient {
	mock := &MockEconomicCalendarClient{ctrl: ctrl}
	mock.recorder = &MockEconomicCalendarClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEconomicCalendarClient) EXPECT() *MockEconomicCalendarClientMockRecorder {
	return m.recorder
}

// FetchBLSICS mocks base method.
func (m *MockEconomicCalendarClient) FetchBLSICS(ctx context.Context) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchBLSICS", ctx)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchBLSICS indicates an expected call of FetchBLSICS.
func (mr *MockEconomicCalendarClientMockRecorder) FetchBLSICS(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchBLSICS", reflect.TypeOf((*MockEconomicCalendarClient)(nil).FetchBLSICS), ctx)
}

// FetchBOJSchedulePage mocks base method.
func (m *MockEconomicCalendarClient) FetchBOJSchedulePage(ctx context.Context) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchBOJSchedulePage", ctx)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchBOJSchedulePage indicates an expected call of FetchBOJSchedulePage.
func (mr *MockEconomicCalendarClientMockRecorder) FetchBOJSchedulePage(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchBOJSchedulePage", reflect.TypeOf((*MockEconomicCalendarClient)(nil).FetchBOJSchedulePage), ctx)
}

// FetchFOMCPage mocks base method.
func (m *MockEconomicCalendarClient) FetchFOMCPage(ctx context.Context) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchFOMCPage", ctx)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchFOMCPage indicates an expected call of FetchFOMCPage.
func (mr *MockEconomicCalendarClientMockRecorder) FetchFOMCPage(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchFOMCPage", reflect.TypeOf((*MockEconomicCalendarClient)(nil).FetchFOMCPage), ctx)
}
