// Code generated by MockGen. DO NOT EDIT.
// Source: adjusted_daily_price.go
//
// Generated by this command:
//
//	mockgen -source=adjusted_daily_price.go -package=mock_repositories -destination=../mock/repositories/adjusted_daily_price.go
//

// Package mock_repositories is a generated GoMock package.
package mock_repositories

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/Code0716/stock-price-repository/models"
	gomock "go.uber.org/mock/gomock"
)

// MockAdjustedDailyPriceRepository is a mock of AdjustedDailyPriceRepository interface.
type MockAdjustedDailyPriceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAdjustedDailyPriceRepositoryMockRecorder
	isgomock struct{}
}

// MockAdjustedDailyPriceRepositoryMockRecorder is the mock recorder for MockAdjustedDailyPriceRepository.
type MockAdjustedDailyPriceRepositoryMockRecorder struct {
	mock *MockAdjustedDailyPriceRepository
}

// NewMockAdjustedDailyPriceRepository creates a new mock instance.
func NewMockAdjustedDailyPriceRepository(ctrl *gomock.Controller) *MockAdjustedDailyPriceRepository {
	mock := &MockAdjustedDailyPriceRepository{ctrl: ctrl}
	mock.recorder = &MockAdjustedDailyPriceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdjustedDailyPriceRepository) EXPECT() *MockAdjustedDailyPriceRepositoryMockRecorder {
	return m.recorder
}

// FindNextTradingDate mocks base method.
func (m *MockAdjustedDailyPriceRepository) FindNextTradingDate(ctx context.Context, after time.Time) (*time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindNextTradingDate", ctx, after)
	ret0, _ := ret[0].(*time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindNextTradingDate indicates an expected call of FindNextTradingDate.
func (mr *MockAdjustedDailyPriceRepositoryMockRecorder) FindNextTradingDate(ctx, after any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindNextTradingDate", reflect.TypeOf((*MockAdjustedDailyPriceRepository)(nil).FindNextTradingDate), ctx, after)
}

// GetLatestPriceBySymbol mocks base method.
func (m *MockAdjustedDailyPriceRepository) GetLatestPriceBySymbol(ctx context.Context, symbol string) (*models.StockBrandDailyPrice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestPriceBySymbol", ctx, symbol)
	ret0, _ := ret[0].(*models.StockBrandDailyPrice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestPriceBySymbol indicates an expected call of GetLatestPriceBySymbol.
func (mr *MockAdjustedDailyPriceRepositoryMockRecorder) GetLatestPriceBySymbol(ctx, symbol any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestPriceBySymbol", reflect.TypeOf((*MockAdjustedDailyPriceRepository)(nil).GetLatestPriceBySymbol), ctx, symbol)
}

// ListDailyPricesBySymbol mocks base method.
func (m *MockAdjustedDailyPriceRepository) ListDailyPricesBySymbol(ctx context.Context, filter models.ListDailyPricesBySymbolFilter) ([]*models.StockBrandDailyPrice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDailyPricesBySymbol", ctx, filter)
	ret0, _ := ret[0].([]*models.StockBrandDailyPrice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDailyPricesBySymbol indicates an expected call of ListDailyPricesBySymbol.
func (mr *MockAdjustedDailyPriceRepositoryMockRecorder) ListDailyPricesBySymbol(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDailyPricesBySymbol", reflect.TypeOf((*MockAdjustedDailyPriceRepository)(nil).ListDailyPricesBySymbol), ctx, filter)
}

// ListPricesByDateRange mocks base method.
func (m *MockAdjustedDailyPriceRepository) ListPricesByDateRange(ctx context.Context, from, to time.Time) ([]*models.StockBrandDailyPrice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPricesByDateRange", ctx, from, to)
	ret0, _ := ret[0].([]*models.StockBrandDailyPrice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPricesByDateRange indicates an expected call of ListPricesByDateRange.
func (mr *MockAdjustedDailyPriceRepositoryMockRecorder) ListPricesByDateRange(ctx, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPricesByDateRange", reflect.TypeOf((*MockAdjustedDailyPriceRepository)(nil).ListPricesByDateRange), ctx, from, to)
}

// ListRangePricesBySymbols mocks base method.
func (m *MockAdjustedDailyPriceRepository) ListRangePricesBySymbols(ctx context.Context, filter models.ListRangePricesBySymbolsFilter) ([]*models.StockBrandDailyPrice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRangePricesBySymbols", ctx, filter)
	ret0, _ := ret[0].([]*models.StockBrandDailyPrice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRangePricesBySymbols indicates an expected call of ListRangePricesBySymbols.
func (mr *MockAdjustedDailyPriceRepositoryMockRecorder) ListRangePricesBySymbols(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRangePricesBySymbols", reflect.TypeOf((*MockAdjustedDailyPriceRepository)(nil).ListRangePricesBySymbols), ctx, filter)
}

// ListRecentTradingDates mocks base method.
func (m *MockAdjustedDailyPriceRepository) ListRecentTradingDates(ctx context.Context, onOrBefore time.Time, limit int) ([]time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRecentTradingDates", ctx, onOrBefore, limit)
	ret0, _ := ret[0].([]time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRecentTradingDates indicates an expected call of ListRecentTradingDates.
func (mr *MockAdjustedDailyPriceRepositoryMockRecorder) ListRecentTradingDates(ctx, onOrBefore, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRecentTradingDates", reflect.TypeOf((*MockAdjustedDailyPriceRepository)(nil).ListRecentTradingDates), ctx, onOrBefore, limit)
}
