// Code generated by MockGen. DO NOT EDIT.
// Source: analyze_stock_brand_price_history.go
//
// Generated by this command:
//
//	mockgen -source=analyze_stock_brand_price_history.go -package=mock_repositories -destination=../mock/repositories/analyze_stock_brand_price_history.go
//

// Package mock_repositories is a generated GoMock package.
package mock_repositories

import (
	context "context"
	reflect "reflect"

	models "github.com/Code0716/stock-price-repository/models"
	gomock "go.uber.org/mock/gomock"
)

// MockAnalyzeStockBrandPriceHistoryRepository is a mock of AnalyzeStockBrandPriceHistoryRepository interface.
type MockAnalyzeStockBrandPriceHistoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAnalyzeStockBrandPriceHistoryRepositoryMockRecorder
	isgomock struct{}
}

// MockAnalyzeStockBrandPriceHistoryRepositoryMockRecorder is the mock recorder for MockAnalyzeStockBrandPriceHistoryRepository.
type MockAnalyzeStockBrandPriceHistoryRepositoryMockRecorder struct {
	mock *MockAnalyzeStockBrandPriceHistoryRepository
}

// NewMockAnalyzeStockBrandPriceHistoryRepository creates a new mock instance.
func NewMockAnalyzeStockBrandPriceHistoryRepository(ctrl *gomock.Controller) *MockAnalyzeStockBrandPriceHistoryRepository {
	mock := &MockAnalyzeStockBrandPriceHistoryRepository{ctrl: ctrl}
	mock.recorder = &MockAnalyzeStockBrandPriceHistoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnalyzeStockBrandPriceHistoryRepository) EXPECT() *MockAnalyzeStockBrandPriceHistoryRepositoryMockRecorder {
	return m.recorder
}

// CountDistinctDates mocks base method.
func (m *MockAnalyzeStockBrandPriceHistoryRepository) CountDistinctDates(ctx context.Context, filter *models.AnalyzeStockBrandPriceHistoryFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountDistinctDates", ctx, filter)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountDistinctDates indicates an expected call of CountDistinctDates.
func (mr *MockAnalyzeStockBrandPriceHistoryRepositoryMockRecorder) CountDistinctDates(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountDistinctDates", reflect.TypeOf((*MockAnalyzeStockBrandPriceHistoryRepository)(nil).CountDistinctDates), ctx, filter)
}

// CountWithFilter mocks base method.
func (m *MockAnalyzeStockBrandPriceHistoryRepository) CountWithFilter(ctx context.Context, filter *models.AnalyzeStockBrandPriceHistoryFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountWithFilter", ctx, filter)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountWithFilter indicates an expected call of CountWithFilter.
func (mr *MockAnalyzeStockBrandPriceHistoryRepositoryMockRecorder) CountWithFilter(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountWithFilter", reflect.TypeOf((*MockAnalyzeStockBrandPriceHistoryRepository)(nil).CountWithFilter), ctx, filter)
}

// DeleteByStockBrandIDs mocks base method.
func (m *MockAnalyzeStockBrandPriceHistoryRepository) DeleteByStockBrandIDs(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByStockBrandIDs", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByStockBrandIDs indicates an expected call of DeleteByStockBrandIDs.
func (mr *MockAnalyzeStockBrandPriceHistoryRepositoryMockRecorder) DeleteByStockBrandIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByStockBrandIDs", reflect.TypeOf((*MockAnalyzeStockBrandPriceHistoryRepository)(nil).DeleteByStockBrandIDs), ctx, ids)
}

// FindByDates mocks base method.
func (m *MockAnalyzeStockBrandPriceHistoryRepository) FindByDates(ctx context.Context, filter *models.AnalyzeStockBrandPriceHistoryFilter, dates []string) ([]*models.AnalyzeStockBrandPriceHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByDates", ctx, filter, dates)
	ret0, _ := ret[0].([]*models.AnalyzeStockBrandPriceHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByDates indicates an expected call of FindByDates.
func (mr *MockAnalyzeStockBrandPriceHistoryRepositoryMockRecorder) FindByDates(ctx, filter, dates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByDates", reflect.TypeOf((*MockAnalyzeStockBrandPriceHistoryRepository)(nil).FindByDates), ctx, filter, dates)
}

// FindDistinctDates mocks base method.
func (m *MockAnalyzeStockBrandPriceHistoryRepository) FindDistinctDates(ctx context.Context, filter *models.AnalyzeStockBrandPriceHistoryFilter) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDistinctDates", ctx, filter)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDistinctDates indicates an expected call of FindDistinctDates.
func (mr *MockAnalyzeStockBrandPriceHistoryRepositoryMockRecorder) FindDistinctDates(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDistinctDates", reflect.TypeOf((*MockAnalyzeStockBrandPriceHistoryRepository)(nil).FindDistinctDates), ctx, filter)
}

// FindMultipleSignals mocks base method.
func (m *MockAnalyzeStockBrandPriceHistoryRepository) FindMultipleSignals(ctx context.Context, filter *models.MultipleSignalStockFilter) ([]*models.MultipleSignalStock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMultipleSignals", ctx, filter)
	ret0, _ := ret[0].([]*models.MultipleSignalStock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMultipleSignals indicates an expected call of FindMultipleSignals.
func (mr *MockAnalyzeStockBrandPriceHistoryRepositoryMockRecorder) FindMultipleSignals(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMultipleSignals", reflect.TypeOf((*MockAnalyzeStockBrandPriceHistoryRepository)(nil).FindMultipleSignals), ctx, filter)
}

// FindWithFilter mocks base method.
func (m *MockAnalyzeStockBrandPriceHistoryRepository) FindWithFilter(ctx context.Context, filter *models.AnalyzeStockBrandPriceHistoryFilter) ([]*models.AnalyzeStockBrandPriceHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWithFilter", ctx, filter)
	ret0, _ := ret[0].([]*models.AnalyzeStockBrandPriceHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindWithFilter indicates an expected call of FindWithFilter.
func (mr *MockAnalyzeStockBrandPriceHistoryRepositoryMockRecorder) FindWithFilter(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWithFilter", reflect.TypeOf((*MockAnalyzeStockBrandPriceHistoryRepository)(nil).FindWithFilter), ctx, filter)
}
