// Code generated by MockGen. DO NOT EDIT.
// Source: applied_stock_consolidation_history.go
//
// Generated by this command:
//
//	mockgen -source=applied_stock_consolidation_history.go -package=mock_repositories -destination=../mock/repositories/applied_stock_consolidation_history.go
//

// Package mock_repositories is a generated GoMock package.
package mock_repositories

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/Code0716/stock-price-repository/models"
	gomock "go.uber.org/mock/gomock"
)

// MockAppliedStockConsolidationsHistoryRepository is a mock of AppliedStockConsolidationsHistoryRepository interface.
type MockAppliedStockConsolidationsHistoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAppliedStockConsolidationsHistoryRepositoryMockRecorder
	isgomock struct{}
}

// MockAppliedStockConsolidationsHistoryRepositoryMockRecorder is the mock recorder for MockAppliedStockConsolidationsHistoryRepository.
type MockAppliedStockConsolidationsHistoryRepositoryMockRecorder struct {
	mock *MockAppliedStockConsolidationsHistoryRepository
}

// NewMockAppliedStockConsolidationsHistoryRepository creates a new mock instance.
func NewMockAppliedStockConsolidationsHistoryRepository(ctrl *gomock.Controller) *MockAppliedStockConsolidationsHistoryRepository {
	mock := &MockAppliedStockConsolidationsHistoryRepository{ctrl: ctrl}
	mock.recorder = &MockAppliedStockConsolidationsHistoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppliedStockConsolidationsHistoryRepository) EXPECT() *MockAppliedStockConsolidationsHistoryRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAppliedStockConsolidationsHistoryRepository) Create(ctx context.Context, history *models.AppliedStockConsolidationHistory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, history)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAppliedStockConsolidationsHistoryRepositoryMockRecorder) Create(ctx, history any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAppliedStockConsolidationsHistoryRepository)(nil).Create), ctx, history)
}

// Exists mocks base method.
func (m *MockAppliedStockConsolidationsHistoryRepository) Exists(ctx context.Context, symbol string, consolidationDate time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, symbol, consolidationDate)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockAppliedStockConsolidationsHistoryRepositoryMockRecorder) Exists(ctx, symbol, consolidationDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockAppliedStockConsolidationsHistoryRepository)(nil).Exists), ctx, symbol, consolidationDate)
}
