// Code generated by MockGen. DO NOT EDIT.
// Source: applied_stock_split_history.go
//
// Generated by this command:
//
//	mockgen -source=applied_stock_split_history.go -package=mock_repositories -destination=../mock/repositories/applied_stock_split_history.go
//

// Package mock_repositories is a generated GoMock package.
package mock_repositories

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/Code0716/stock-price-repository/models"
	gomock "go.uber.org/mock/gomock"
)

// MockAppliedStockSplitsHistoryRepository is a mock of AppliedStockSplitsHistoryRepository interface.
type MockAppliedStockSplitsHistoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAppliedStockSplitsHistoryRepositoryMockRecorder
	isgomock struct{}
}

// MockAppliedStockSplitsHistoryRepositoryMockRecorder is the mock recorder for MockAppliedStockSplitsHistoryRepository.
type MockAppliedStockSplitsHistoryRepositoryMockRecorder struct {
	mock *MockAppliedStockSplitsHistoryRepository
}

// NewMockAppliedStockSplitsHistoryRepository creates a new mock instance.
func NewMockAppliedStockSplitsHistoryRepository(ctrl *gomock.Controller) *MockAppliedStockSplitsHistoryRepository {
	mock := &MockAppliedStockSplitsHistoryRepository{ctrl: ctrl}
	mock.recorder = &MockAppliedStockSplitsHistoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppliedStockSplitsHistoryRepository) EXPECT() *MockAppliedStockSplitsHistoryRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAppliedStockSplitsHistoryRepository) Create(ctx context.Context, history *models.AppliedStockSplitHistory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, history)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAppliedStockSplitsHistoryRepositoryMockRecorder) Create(ctx, history any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAppliedStockSplitsHistoryRepository)(nil).Create), ctx, history)
}

// Exists mocks base method.
func (m *MockAppliedStockSplitsHistoryRepository) Exists(ctx context.Context, symbol string, splitDate time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, symbol, splitDate)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockAppliedStockSplitsHistoryRepositoryMockRecorder) Exists(ctx, symbol, splitDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockAppliedStockSplitsHistoryRepository)(nil).Exists), ctx, symbol, splitDate)
}
