// Code generated by MockGen. DO NOT EDIT.
// Source: daily_avoid_stock.go
//
// Generated by this command:
//
//	mockgen -source=daily_avoid_stock.go -package=mock_repositories -destination=../mock/repositories/daily_avoid_stock.go
//

// Package mock_repositories is a generated GoMock package.
package mock_repositories

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/Code0716/stock-price-repository/models"
	gomock "go.uber.org/mock/gomock"
)

// MockDailyAvoidStockRepository is a mock of DailyAvoidStockRepository interface.
type MockDailyAvoidStockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDailyAvoidStockRepositoryMockRecorder
	isgomock struct{}
}

// MockDailyAvoidStockRepositoryMockRecorder is the mock recorder for MockDailyAvoidStockRepository.
type MockDailyAvoidStockRepositoryMockRecorder struct {
	mock *MockDailyAvoidStockRepository
}

// NewMockDailyAvoidStockRepository creates a new mock instance.
func NewMockDailyAvoidStockRepository(ctrl *gomock.Controller) *MockDailyAvoidStockRepository {
	mock := &MockDailyAvoidStockRepository{ctrl: ctrl}
	mock.recorder = &MockDailyAvoidStockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDailyAvoidStockRepository) EXPECT() *MockDailyAvoidStockRepositoryMockRecorder {
	return m.recorder
}

// BulkCreate mocks base method.
func (m *MockDailyAvoidStockRepository) BulkCreate(ctx context.Context, rows []*models.DailyAvoidStock) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkCreate", ctx, rows)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkCreate indicates an expected call of BulkCreate.
func (mr *MockDailyAvoidStockRepositoryMockRecorder) BulkCreate(ctx, rows any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkCreate", reflect.TypeOf((*MockDailyAvoidStockRepository)(nil).BulkCreate), ctx, rows)
}

// DeleteByAsOfDate mocks base method.
func (m *MockDailyAvoidStockRepository) DeleteByAsOfDate(ctx context.Context, asOfDate time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByAsOfDate", ctx, asOfDate)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByAsOfDate indicates an expected call of DeleteByAsOfDate.
func (mr *MockDailyAvoidStockRepositoryMockRecorder) DeleteByAsOfDate(ctx, asOfDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByAsOfDate", reflect.TypeOf((*MockDailyAvoidStockRepository)(nil).DeleteByAsOfDate), ctx, asOfDate)
}

// ExistsByAsOfDate mocks base method.
func (m *MockDailyAvoidStockRepository) ExistsByAsOfDate(ctx context.Context, asOfDate time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByAsOfDate", ctx, asOfDate)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByAsOfDate indicates an expected call of ExistsByAsOfDate.
func (mr *MockDailyAvoidStockRepositoryMockRecorder) ExistsByAsOfDate(ctx, asOfDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByAsOfDate", reflect.TypeOf((*MockDailyAvoidStockRepository)(nil).ExistsByAsOfDate), ctx, asOfDate)
}

// FindLatestAsOfDate mocks base method.
func (m *MockDailyAvoidStockRepository) FindLatestAsOfDate(ctx context.Context) (*time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLatestAsOfDate", ctx)
	ret0, _ := ret[0].(*time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLatestAsOfDate indicates an expected call of FindLatestAsOfDate.
func (mr *MockDailyAvoidStockRepositoryMockRecorder) FindLatestAsOfDate(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLatestAsOfDate", reflect.TypeOf((*MockDailyAvoidStockRepository)(nil).FindLatestAsOfDate), ctx)
}

// ListAsOfDates mocks base method.
func (m *MockDailyAvoidStockRepository) ListAsOfDates(ctx context.Context, limit int) ([]time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAsOfDates", ctx, limit)
	ret0, _ := ret[0].([]time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAsOfDates indicates an expected call of ListAsOfDates.
func (mr *MockDailyAvoidStockRepositoryMockRecorder) ListAsOfDates(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAsOfDates", reflect.TypeOf((*MockDailyAvoidStockRepository)(nil).ListAsOfDates), ctx, limit)
}

// ListByAsOfDate mocks base method.
func (m *MockDailyAvoidStockRepository) ListByAsOfDate(ctx context.Context, asOfDate time.Time) ([]*models.DailyAvoidStock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAsOfDate", ctx, asOfDate)
	ret0, _ := ret[0].([]*models.DailyAvoidStock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAsOfDate indicates an expected call of ListByAsOfDate.
func (mr *MockDailyAvoidStockRepositoryMockRecorder) ListByAsOfDate(ctx, asOfDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAsOfDate", reflect.TypeOf((*MockDailyAvoidStockRepository)(nil).ListByAsOfDate), ctx, asOfDate)
}
