// Code generated by MockGen. DO NOT EDIT.
// Source: daytrade_execution.go
//
// Generated by this command:
//
//	mockgen -source=daytrade_execution.go -package=mock_repositories -destination=../mock/repositories/daytrade_execution.go
//

// Package mock_repositories is a generated GoMock package.
package mock_repositories

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/Code0716/stock-price-repository/models"
	gomock "go.uber.org/mock/gomock"
)

// MockDaytradeExecutionRepository is a mock of DaytradeExecutionRepository interface.
type MockDaytradeExecutionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDaytradeExecutionRepositoryMockRecorder
	isgomock struct{}
}

// MockDaytradeExecutionRepositoryMockRecorder is the mock recorder for MockDaytradeExecutionRepository.
type MockDaytradeExecutionRepositoryMockRecorder struct {
	mock *MockDaytradeExecutionRepository
}

// NewMockDaytradeExecutionRepository creates a new mock instance.
func NewMockDaytradeExecutionRepository(ctrl *gomock.Controller) *MockDaytradeExecutionRepository {
	mock := &MockDaytradeExecutionRepository{ctrl: ctrl}
	mock.recorder = &MockDaytradeExecutionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDaytradeExecutionRepository) EXPECT() *MockDaytradeExecutionRepositoryMockRecorder {
	return m.recorder
}

// Aggregate mocks base method.
func (m *MockDaytradeExecutionRepository) Aggregate(ctx context.Context, from, to *time.Time, g models.DaytradeSummaryGranularity) ([]*models.DaytradeSummaryBucket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Aggregate", ctx, from, to, g)
	ret0, _ := ret[0].([]*models.DaytradeSummaryBucket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Aggregate indicates an expected call of Aggregate.
func (mr *MockDaytradeExecutionRepositoryMockRecorder) Aggregate(ctx, from, to, g any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Aggregate", reflect.TypeOf((*MockDaytradeExecutionRepository)(nil).Aggregate), ctx, from, to, g)
}

// AggregateByTickerSymbol mocks base method.
func (m *MockDaytradeExecutionRepository) AggregateByTickerSymbol(ctx context.Context, from, to *time.Time) ([]*models.DaytradeSymbolSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AggregateByTickerSymbol", ctx, from, to)
	ret0, _ := ret[0].([]*models.DaytradeSymbolSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AggregateByTickerSymbol indicates an expected call of AggregateByTickerSymbol.
func (mr *MockDaytradeExecutionRepositoryMockRecorder) AggregateByTickerSymbol(ctx, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AggregateByTickerSymbol", reflect.TypeOf((*MockDaytradeExecutionRepository)(nil).AggregateByTickerSymbol), ctx, from, to)
}

// AggregateStats mocks base method.
func (m *MockDaytradeExecutionRepository) AggregateStats(ctx context.Context, from, to *time.Time) (*models.DaytradeStatsAggregate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AggregateStats", ctx, from, to)
	ret0, _ := ret[0].(*models.DaytradeStatsAggregate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AggregateStats indicates an expected call of AggregateStats.
func (mr *MockDaytradeExecutionRepositoryMockRecorder) AggregateStats(ctx, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AggregateStats", reflect.TypeOf((*MockDaytradeExecutionRepository)(nil).AggregateStats), ctx, from, to)
}

// BulkInsertIgnore mocks base method.
func (m *MockDaytradeExecutionRepository) BulkInsertIgnore(ctx context.Context, executions []*models.DaytradeExecution) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkInsertIgnore", ctx, executions)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkInsertIgnore indicates an expected call of BulkInsertIgnore.
func (mr *MockDaytradeExecutionRepositoryMockRecorder) BulkInsertIgnore(ctx, executions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkInsertIgnore", reflect.TypeOf((*MockDaytradeExecutionRepository)(nil).BulkInsertIgnore), ctx, executions)
}

// DeleteBySourceAndDates mocks base method.
func (m *MockDaytradeExecutionRepository) DeleteBySourceAndDates(ctx context.Context, source string, dates []time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBySourceAndDates", ctx, source, dates)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBySourceAndDates indicates an expected call of DeleteBySourceAndDates.
func (mr *MockDaytradeExecutionRepositoryMockRecorder) DeleteBySourceAndDates(ctx, source, dates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBySourceAndDates", reflect.TypeOf((*MockDaytradeExecutionRepository)(nil).DeleteBySourceAndDates), ctx, source, dates)
}

// FindByDate mocks base method.
func (m *MockDaytradeExecutionRepository) FindByDate(ctx context.Context, date time.Time) ([]*models.DaytradeExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByDate", ctx, date)
	ret0, _ := ret[0].([]*models.DaytradeExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByDate indicates an expected call of FindByDate.
func (mr *MockDaytradeExecutionRepositoryMockRecorder) FindByDate(ctx, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByDate", reflect.TypeOf((*MockDaytradeExecutionRepository)(nil).FindByDate), ctx, date)
}

// FindByDateRange mocks base method.
func (m *MockDaytradeExecutionRepository) FindByDateRange(ctx context.Context, from, to *time.Time) ([]*models.DaytradeExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByDateRange", ctx, from, to)
	ret0, _ := ret[0].([]*models.DaytradeExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByDateRange indicates an expected call of FindByDateRange.
func (mr *MockDaytradeExecutionRepositoryMockRecorder) FindByDateRange(ctx, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByDateRange", reflect.TypeOf((*MockDaytradeExecutionRepository)(nil).FindByDateRange), ctx, from, to)
}

// GetCoveredRange mocks base method.
func (m *MockDaytradeExecutionRepository) GetCoveredRange(ctx context.Context) (*time.Time, *time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCoveredRange", ctx)
	ret0, _ := ret[0].(*time.Time)
	ret1, _ := ret[1].(*time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetCoveredRange indicates an expected call of GetCoveredRange.
func (mr *MockDaytradeExecutionRepositoryMockRecorder) GetCoveredRange(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCoveredRange", reflect.TypeOf((*MockDaytradeExecutionRepository)(nil).GetCoveredRange), ctx)
}
