// Code generated by MockGen. DO NOT EDIT.
// Source: daytrade_trade_note.go
//
// Generated by this command:
//
//	mockgen -source=daytrade_trade_note.go -package=mock_repositories -destination=../mock/repositories/daytrade_trade_note.go
//

// Package mock_repositories is a generated GoMock package.
package mock_repositories

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/Code0716/stock-price-repository/models"
	gomock "go.uber.org/mock/gomock"
)

// MockDaytradeTradeNoteRepository is a mock of DaytradeTradeNoteRepository interface.
type MockDaytradeTradeNoteRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDaytradeTradeNoteRepositoryMockRecorder
	isgomock struct{}
}

// MockDaytradeTradeNoteRepositoryMockRecorder is the mock recorder for MockDaytradeTradeNoteRepository.
type MockDaytradeTradeNoteRepositoryMockRecorder struct {
	mock *MockDaytradeTradeNoteRepository
}

// NewMockDaytradeTradeNoteRepository creates a new mock instance.
func NewMockDaytradeTradeNoteRepository(ctrl *gomock.Controller) *MockDaytradeTradeNoteRepository {
	mock := &MockDaytradeTradeNoteRepository{ctrl: ctrl}
	mock.recorder = &MockDaytradeTradeNoteRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDaytradeTradeNoteRepository) EXPECT() *MockDaytradeTradeNoteRepositoryMockRecorder {
	return m.recorder
}

// FindByDateRange mocks base method.
func (m *MockDaytradeTradeNoteRepository) FindByDateRange(ctx context.Context, from, to *time.Time) ([]*models.DaytradeTradeNoteRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByDateRange", ctx, from, to)
	ret0, _ := ret[0].([]*models.DaytradeTradeNoteRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByDateRange indicates an expected call of FindByDateRange.
func (mr *MockDaytradeTradeNoteRepositoryMockRecorder) FindByDateRange(ctx, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByDateRange", reflect.TypeOf((*MockDaytradeTradeNoteRepository)(nil).FindByDateRange), ctx, from, to)
}

// Upsert mocks base method.
func (m *MockDaytradeTradeNoteRepository) Upsert(ctx context.Context, rec *models.DaytradeTradeNoteRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, rec)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockDaytradeTradeNoteRepositoryMockRecorder) Upsert(ctx, rec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockDaytradeTradeNoteRepository)(nil).Upsert), ctx, rec)
}
