// Code generated by MockGen. DO NOT EDIT.
// Source: market_calendar.go
//
// Generated by this command:
//
//	mockgen -source=market_calendar.go -package=mock_repositories -destination=../mock/repositories/market_calendar.go
//

// Package mock_repositories is a generated GoMock package.
package mock_repositories

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/Code0716/stock-price-repository/models"
	gomock "go.uber.org/mock/gomock"
)

// MockMarketCalendarRepository is a mock of MarketCalendarRepository interface.
type MockMarketCalendarRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMarketCalendarRepositoryMockRecorder
	isgomock struct{}
}

// MockMarketCalendarRepositoryMockRecorder is the mock recorder for MockMarketCalendarRepository.
type MockMarketCalendarRepositoryMockRecorder struct {
	mock *MockMarketCalendarRepository
}

// NewMockMarketCalendarRepository creates a new mock instance.
func NewMockMarketCalendarRepository(ctrl *gomock.Controller) *MockMarketCalendarRepository {
	mock := &MockMarketCalendarRepository{ctrl: ctrl}
	mock.recorder = &MockMarketCalendarRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMarketCalendarRepository) EXPECT() *MockMarketCalendarRepositoryMockRecorder {
	return m.recorder
}

// ListDays mocks base method.
func (m *MockMarketCalendarRepository) ListDays(ctx context.Context, from, to time.Time) ([]*models.MarketCalendarDay, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDays", ctx, from, to)
	ret0, _ := ret[0].([]*models.MarketCalendarDay)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDays indicates an expected call of ListDays.
func (mr *MockMarketCalendarRepositoryMockRecorder) ListDays(ctx, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDays", reflect.TypeOf((*MockMarketCalendarRepository)(nil).ListDays), ctx, from, to)
}

// ListEvents mocks base method.
func (m *MockMarketCalendarRepository) ListEvents(ctx context.Context, from, to time.Time) ([]*models.MarketEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEvents", ctx, from, to)
	ret0, _ := ret[0].([]*models.MarketEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEvents indicates an expected call of ListEvents.
func (mr *MockMarketCalendarRepositoryMockRecorder) ListEvents(ctx, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEvents", reflect.TypeOf((*MockMarketCalendarRepository)(nil).ListEvents), ctx, from, to)
}

// ReplaceEvents mocks base method.
func (m *MockMarketCalendarRepository) ReplaceEvents(ctx context.Context, kind string, from, to time.Time, events []*models.MarketEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceEvents", ctx, kind, from, to, events)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceEvents indicates an expected call of ReplaceEvents.
func (mr *MockMarketCalendarRepositoryMockRecorder) ReplaceEvents(ctx, kind, from, to, events any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceEvents", reflect.TypeOf((*MockMarketCalendarRepository)(nil).ReplaceEvents), ctx, kind, from, to, events)
}

// UpsertDays mocks base method.
func (m *MockMarketCalendarRepository) UpsertDays(ctx context.Context, days []*models.MarketCalendarDay) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertDays", ctx, days)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertDays indicates an expected call of UpsertDays.
func (mr *MockMarketCalendarRepositoryMockRecorder) UpsertDays(ctx, days any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertDays", reflect.TypeOf((*MockMarketCalendarRepository)(nil).UpsertDays), ctx, days)
}
