// Code generated by MockGen. DO NOT EDIT.
// Source: notification_history.go
//
// Generated by this command:
//
//	mockgen -source=notification_history.go -package=mock_repositories -destination=../mock/repositories/notification_history.go
//

// Package mock_repositories is a generated GoMock package.
package mock_repositories

import (
	context "context"
	reflect "reflect"

	models "github.com/Code0716/stock-price-repository/models"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificationHistoryRepository is a mock of NotificationHistoryRepository interface.
type MockNotificationHistoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationHistoryRepositoryMockRecorder
	isgomock struct{}
}

// MockNotificationHistoryRepositoryMockRecorder is the mock recorder for MockNotificationHistoryRepository.
type MockNotificationHistoryRepositoryMockRecorder struct {
	mock *MockNotificationHistoryRepository
}

// NewMockNotificationHistoryRepository creates a new mock instance.
func NewMockNotificationHistoryRepository(ctrl *gomock.Controller) *MockNotificationHistoryRepository {
	mock := &MockNotificationHistoryRepository{ctrl: ctrl}
	mock.recorder = &MockNotificationHistoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationHistoryRepository) EXPECT() *MockNotificationHistoryRepositoryMockRecorder {
	return m.recorder
}

// CountWithFilter mocks base method.
func (m *MockNotificationHistoryRepository) CountWithFilter(ctx context.Context, filter *models.NotificationHistoryFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountWithFilter", ctx, filter)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountWithFilter indicates an expected call of CountWithFilter.
func (mr *MockNotificationHistoryRepositoryMockRecorder) CountWithFilter(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountWithFilter", reflect.TypeOf((*MockNotificationHistoryRepository)(nil).CountWithFilter), ctx, filter)
}

// Create mocks base method.
func (m *MockNotificationHistoryRepository) Create(ctx context.Context, notification *models.NotificationHistory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, notification)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockNotificationHistoryRepositoryMockRecorder) Create(ctx, notification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNotificationHistoryRepository)(nil).Create), ctx, notification)
}

// FindWithFilter mocks base method.
func (m *MockNotificationHistoryRepository) FindWithFilter(ctx context.Context, filter *models.NotificationHistoryFilter) ([]*models.NotificationHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWithFilter", ctx, filter)
	ret0, _ := ret[0].([]*models.NotificationHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindWithFilter indicates an expected call of FindWithFilter.
func (mr *MockNotificationHistoryRepositoryMockRecorder) FindWithFilter(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWithFilter", reflect.TypeOf((*MockNotificationHistoryRepository)(nil).FindWithFilter), ctx, filter)
}
