// Code generated by MockGen. DO NOT EDIT.
// Source: quiz_daily_universe.go
//
// Generated by this command:
//
//	mockgen -source=quiz_daily_universe.go -package=mock_repositories -destination=../mock/repositories/quiz_daily_universe.go
//

// Package mock_repositories is a generated GoMock package.
package mock_repositories

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/Code0716/stock-price-repository/models"
	gomock "go.uber.org/mock/gomock"
)

// MockQuizDailyUniverseRepository is a mock of QuizDailyUniverseRepository interface.
type MockQuizDailyUniverseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockQuizDailyUniverseRepositoryMockRecorder
	isgomock struct{}
}

// MockQuizDailyUniverseRepositoryMockRecorder is the mock recorder for MockQuizDailyUniverseRepository.
type MockQuizDailyUniverseRepositoryMockRecorder struct {
	mock *MockQuizDailyUniverseRepository
}

// NewMockQuizDailyUniverseRepository creates a new mock instance.
func NewMockQuizDailyUniverseRepository(ctrl *gomock.Controller) *MockQuizDailyUniverseRepository {
	mock := &MockQuizDailyUniverseRepository{ctrl: ctrl}
	mock.recorder = &MockQuizDailyUniverseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuizDailyUniverseRepository) EXPECT() *MockQuizDailyUniverseRepositoryMockRecorder {
	return m.recorder
}

// BulkCreate mocks base method.
func (m *MockQuizDailyUniverseRepository) BulkCreate(ctx context.Context, entries []*models.QuizUniverseEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkCreate", ctx, entries)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkCreate indicates an expected call of BulkCreate.
func (mr *MockQuizDailyUniverseRepositoryMockRecorder) BulkCreate(ctx, entries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkCreate", reflect.TypeOf((*MockQuizDailyUniverseRepository)(nil).BulkCreate), ctx, entries)
}

// ExistsByQuizDate mocks base method.
func (m *MockQuizDailyUniverseRepository) ExistsByQuizDate(ctx context.Context, quizDate time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByQuizDate", ctx, quizDate)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByQuizDate indicates an expected call of ExistsByQuizDate.
func (mr *MockQuizDailyUniverseRepositoryMockRecorder) ExistsByQuizDate(ctx, quizDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByQuizDate", reflect.TypeOf((*MockQuizDailyUniverseRepository)(nil).ExistsByQuizDate), ctx, quizDate)
}

// FindByQuizDateAndStockBrandID mocks base method.
func (m *MockQuizDailyUniverseRepository) FindByQuizDateAndStockBrandID(ctx context.Context, quizDate time.Time, stockBrandID string) (*models.QuizUniverseEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByQuizDateAndStockBrandID", ctx, quizDate, stockBrandID)
	ret0, _ := ret[0].(*models.QuizUniverseEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByQuizDateAndStockBrandID indicates an expected call of FindByQuizDateAndStockBrandID.
func (mr *MockQuizDailyUniverseRepositoryMockRecorder) FindByQuizDateAndStockBrandID(ctx, quizDate, stockBrandID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByQuizDateAndStockBrandID", reflect.TypeOf((*MockQuizDailyUniverseRepository)(nil).FindByQuizDateAndStockBrandID), ctx, quizDate, stockBrandID)
}

// FindLatestQuizDate mocks base method.
func (m *MockQuizDailyUniverseRepository) FindLatestQuizDate(ctx context.Context) (*time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLatestQuizDate", ctx)
	ret0, _ := ret[0].(*time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLatestQuizDate indicates an expected call of FindLatestQuizDate.
func (mr *MockQuizDailyUniverseRepositoryMockRecorder) FindLatestQuizDate(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLatestQuizDate", reflect.TypeOf((*MockQuizDailyUniverseRepository)(nil).FindLatestQuizDate), ctx)
}

// ListByQuizDate mocks base method.
func (m *MockQuizDailyUniverseRepository) ListByQuizDate(ctx context.Context, quizDate time.Time) ([]*models.QuizUniverseEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByQuizDate", ctx, quizDate)
	ret0, _ := ret[0].([]*models.QuizUniverseEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByQuizDate indicates an expected call of ListByQuizDate.
func (mr *MockQuizDailyUniverseRepositoryMockRecorder) ListByQuizDate(ctx, quizDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByQuizDate", reflect.TypeOf((*MockQuizDailyUniverseRepository)(nil).ListByQuizDate), ctx, quizDate)
}
