// Code generated by MockGen. DO NOT EDIT.
// Source: sector.go
//
// Generated by this command:
//
//	mockgen -source=sector.go -package=mock_repositories -destination=../mock/repositories/sector.go
//

// Package mock_repositories is a generated GoMock package.
package mock_repositories

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/Code0716/stock-price-repository/models"
	gomock "go.uber.org/mock/gomock"
)

// MockSector33AverageDailyPriceRepository is a mock of Sector33AverageDailyPriceRepository interface.
type MockSector33AverageDailyPriceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSector33AverageDailyPriceRepositoryMockRecorder
	isgomock struct{}
}

// MockSector33AverageDailyPriceRepositoryMockRecorder is the mock recorder for MockSector33AverageDailyPriceRepository.
type MockSector33AverageDailyPriceRepositoryMockRecorder struct {
	mock *MockSector33AverageDailyPriceRepository
}

// NewMockSector33AverageDailyPriceRepository creates a new mock instance.
func NewMockSector33AverageDailyPriceRepository(ctrl *gomock.Controller) *MockSector33AverageDailyPriceRepository {
	mock := &MockSector33AverageDailyPriceRepository{ctrl: ctrl}
	mock.recorder = &MockSector33AverageDailyPriceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSector33AverageDailyPriceRepository) EXPECT() *MockSector33AverageDailyPriceRepositoryMockRecorder {
	return m.recorder
}

// ListRangeAll mocks base method.
func (m *MockSector33AverageDailyPriceRepository) ListRangeAll(ctx context.Context, from, to time.Time) ([]*models.Sector33AverageDailyPrice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRangeAll", ctx, from, to)
	ret0, _ := ret[0].([]*models.Sector33AverageDailyPrice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRangeAll indicates an expected call of ListRangeAll.
func (mr *MockSector33AverageDailyPriceRepositoryMockRecorder) ListRangeAll(ctx, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRangeAll", reflect.TypeOf((*MockSector33AverageDailyPriceRepository)(nil).ListRangeAll), ctx, from, to)
}
