// Code generated by MockGen. DO NOT EDIT.
// Source: stock_brands_daily_stock_price_analyze.go
//
// Generated by this command:
//
//	mockgen -source=stock_brands_daily_stock_price_analyze.go -package=mock_repositories -destination=../mock/repositories/stock_brands_daily_stock_price_analyze.go
//

// Package mock_repositories is a generated GoMock package.
package mock_repositories

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/Code0716/stock-price-repository/models"
	gomock "go.uber.org/mock/gomock"
)

// MockStockBrandsDailyPriceForAnalyzeRepository is a mock of StockBrandsDailyPriceForAnalyzeRepository interface.
type MockStockBrandsDailyPriceForAnalyzeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStockBrandsDailyPriceForAnalyzeRepositoryMockRecorder
	isgomock struct{}
}

// MockStockBrandsDailyPriceForAnalyzeRepositoryMockRecorder is the mock recorder for MockStockBrandsDailyPriceForAnalyzeRepository.
type MockStockBrandsDailyPriceForAnalyzeRepositoryMockRecorder struct {
	mock *MockStockBrandsDailyPriceForAnalyzeRepository
}

// NewMockStockBrandsDailyPriceForAnalyzeRepository creates a new mock instance.
func NewMockStockBrandsDailyPriceForAnalyzeRepository(ctrl *gomock.Controller) *MockStockBrandsDailyPriceForAnalyzeRepository {
	mock := &MockStockBrandsDailyPriceForAnalyzeRepository{ctrl: ctrl}
	mock.recorder = &MockStockBrandsDailyPriceForAnalyzeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStockBrandsDailyPriceForAnalyzeRepository) EXPECT() *MockStockBrandsDailyPriceForAnalyzeRepositoryMockRecorder {
	return m.recorder
}

// CreateStockBrandDailyPriceForAnalyze mocks base method.
func (m *MockStockBrandsDailyPriceForAnalyzeRepository) CreateStockBrandDailyPriceForAnalyze(ctx context.Context, dailyPrice []*models.StockBrandDailyPriceForAnalyze) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStockBrandDailyPriceForAnalyze", ctx, dailyPrice)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateStockBrandDailyPriceForAnalyze indicates an expected call of CreateStockBrandDailyPriceForAnalyze.
func (mr *MockStockBrandsDailyPriceForAnalyzeRepositoryMockRecorder) CreateStockBrandDailyPriceForAnalyze(ctx, dailyPrice any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStockBrandDailyPriceForAnalyze", reflect.TypeOf((*MockStockBrandsDailyPriceForAnalyzeRepository)(nil).CreateStockBrandDailyPriceForAnalyze), ctx, dailyPrice)
}

// DeleteBeforeDate mocks base method.
func (m *MockStockBrandsDailyPriceForAnalyzeRepository) DeleteBeforeDate(ctx context.Context, date time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBeforeDate", ctx, date)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBeforeDate indicates an expected call of DeleteBeforeDate.
func (mr *MockStockBrandsDailyPriceForAnalyzeRepositoryMockRecorder) DeleteBeforeDate(ctx, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBeforeDate", reflect.TypeOf((*MockStockBrandsDailyPriceForAnalyzeRepository)(nil).DeleteBeforeDate), ctx, date)
}

// DeleteBySymbols mocks base method.
func (m *MockStockBrandsDailyPriceForAnalyzeRepository) DeleteBySymbols(ctx context.Context, deleteSymbols []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBySymbols", ctx, deleteSymbols)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBySymbols indicates an expected call of DeleteBySymbols.
func (mr *MockStockBrandsDailyPriceForAnalyzeRepositoryMockRecorder) DeleteBySymbols(ctx, deleteSymbols any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBySymbols", reflect.TypeOf((*MockStockBrandsDailyPriceForAnalyzeRepository)(nil).DeleteBySymbols), ctx, deleteSymbols)
}

// ListLatestPriceBySymbols mocks base method.
func (m *MockStockBrandsDailyPriceForAnalyzeRepository) ListLatestPriceBySymbols(ctx context.Context, symbols []*string) ([]*models.StockBrandDailyPriceForAnalyze, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLatestPriceBySymbols", ctx, symbols)
	ret0, _ := ret[0].([]*models.StockBrandDailyPriceForAnalyze)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLatestPriceBySymbols indicates an expected call of ListLatestPriceBySymbols.
func (mr *MockStockBrandsDailyPriceForAnalyzeRepositoryMockRecorder) ListLatestPriceBySymbols(ctx, symbols any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLatestPriceBySymbols", reflect.TypeOf((*MockStockBrandsDailyPriceForAnalyzeRepository)(nil).ListLatestPriceBySymbols), ctx, symbols)
}
