// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_model

import (
	"time"
)

const TableNameAppliedStockConsolidationsHistory = "applied_stock_consolidations_history"

// AppliedStockConsolidationsHistory mapped from table <applied_stock_consolidations_history>
type AppliedStockConsolidationsHistory struct {
	ID                uint64     `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	Symbol            string     `gorm:"column:symbol;type:varchar(5);not null;comment:銘柄コード" json:"symbol"`                               // 銘柄コード
	ConsolidationDate time.Time  `gorm:"column:consolidation_date;type:date;not null;comment:併合実施日" json:"consolidation_date"`             // 併合実施日
	Ratio             float64    `gorm:"column:ratio;type:decimal(10,4);not null;comment:併合比率（旧株数/新株数。例: 5株を1株に併合なら 5.0000）" json:"ratio"` // 併合比率（旧株数/新株数。例: 5株を1株に併合なら 5.0000）
	AppliedAt         *time.Time `gorm:"column:applied_at;type:timestamp;default:CURRENT_TIMESTAMP;comment:適用日時" json:"applied_at"`        // 適用日時
}

// TableName AppliedStockConsolidationsHistory's table name
func (*AppliedStockConsolidationsHistory) TableName() string {
	return TableNameAppliedStockConsolidationsHistory
}
