// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_model

import (
	"time"
)

const TableNameFinAnnouncement = "fin_announcement"

// FinAnnouncement mapped from table <fin_announcement>
type FinAnnouncement struct {
	ID               string    `gorm:"column:id;type:char(36);primaryKey" json:"id"`
	TickerSymbol     string    `gorm:"column:ticker_symbol;type:varchar(10);not null;comment:証券コード" json:"ticker_symbol"`    // 証券コード
	StockBrandID     *string   `gorm:"column:stock_brand_id;type:char(36);comment:銘柄ID" json:"stock_brand_id"`               // 銘柄ID
	AnnouncementDate time.Time `gorm:"column:announcement_date;type:date;not null;comment:決算発表予定日" json:"announcement_date"` // 決算発表予定日
	FiscalYear       *string   `gorm:"column:fiscal_year;type:varchar(10);comment:会計年度" json:"fiscal_year"`                  // 会計年度
	FiscalQuarter    *string   `gorm:"column:fiscal_quarter;type:varchar(10);comment:会計期間" json:"fiscal_quarter"`            // 会計期間
	Sector17Code     *string   `gorm:"column:sector_17_code;type:varchar(10);comment:17業種コード" json:"sector_17_code"`         // 17業種コード
	Sector33Code     *string   `gorm:"column:sector_33_code;type:varchar(10);comment:33業種コード" json:"sector_33_code"`         // 33業種コード
	CreatedAt        time.Time `gorm:"column:created_at;type:datetime;not null" json:"created_at"`
	UpdatedAt        time.Time `gorm:"column:updated_at;type:datetime;not null" json:"updated_at"`
}

// TableName FinAnnouncement's table name
func (*FinAnnouncement) TableName() string {
	return TableNameFinAnnouncement
}
