// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_model

import (
	"time"
)

const TableNameFinStatement = "fin_statement"

// FinStatement mapped from table <fin_statement>
type FinStatement struct {
	ID                             string     `gorm:"column:id;type:char(36);primaryKey" json:"id"`
	TickerSymbol                   string     `gorm:"column:ticker_symbol;type:varchar(10);not null;comment:証券コード" json:"ticker_symbol"`                                                // 証券コード
	StockBrandID                   *string    `gorm:"column:stock_brand_id;type:char(36);comment:銘柄ID" json:"stock_brand_id"`                                                           // 銘柄ID
	DisclosedDate                  time.Time  `gorm:"column:disclosed_date;type:date;not null;comment:開示日" json:"disclosed_date"`                                                       // 開示日
	FiscalYearEnd                  *time.Time `gorm:"column:fiscal_year_end;type:date;comment:当期末日" json:"fiscal_year_end"`                                                             // 当期末日
	TypeOfDocument                 *string    `gorm:"column:type_of_document;type:varchar(64);comment:開示書類種別" json:"type_of_document"`                                                  // 開示書類種別
	TypeOfCurrentPeriod            *string    `gorm:"column:type_of_current_period;type:varchar(10);comment:当会計期間の種類" json:"type_of_current_period"`                                    // 当会計期間の種類
	NetSales                       *float64   `gorm:"column:net_sales;type:decimal(20,2);comment:売上高" json:"net_sales"`                                                                 // 売上高
	OperatingProfit                *float64   `gorm:"column:operating_profit;type:decimal(20,2);comment:営業利益" json:"operating_profit"`                                                  // 営業利益
	OrdinaryProfit                 *float64   `gorm:"column:ordinary_profit;type:decimal(20,2);comment:経常利益" json:"ordinary_profit"`                                                    // 経常利益
	Profit                         *float64   `gorm:"column:profit;type:decimal(20,2);comment:当期純利益" json:"profit"`                                                                     // 当期純利益
	EarningsPerShare               *float64   `gorm:"column:earnings_per_share;type:decimal(20,4);comment:EPS" json:"earnings_per_share"`                                               // EPS
	BookValuePerShare              *float64   `gorm:"column:book_value_per_share;type:decimal(20,4);comment:BPS" json:"book_value_per_share"`                                           // BPS
	ForecastNetSales               *float64   `gorm:"column:forecast_net_sales;type:decimal(20,2);comment:通期予想売上高" json:"forecast_net_sales"`                                           // 通期予想売上高
	ForecastOperatingProfit        *float64   `gorm:"column:forecast_operating_profit;type:decimal(20,2);comment:通期予想営業利益" json:"forecast_operating_profit"`                            // 通期予想営業利益
	ForecastProfit                 *float64   `gorm:"column:forecast_profit;type:decimal(20,2);comment:通期予想純利益" json:"forecast_profit"`                                                 // 通期予想純利益
	ForecastEps                    *float64   `gorm:"column:forecast_eps;type:decimal(20,4);comment:通期予想EPS" json:"forecast_eps"`                                                       // 通期予想EPS
	ForecastDividendPerShareAnnual *float64   `gorm:"column:forecast_dividend_per_share_annual;type:decimal(20,4);comment:1株あたり当期予想配当（年間合計）" json:"forecast_dividend_per_share_annual"` // 1株あたり当期予想配当（年間合計）
	CreatedAt                      time.Time  `gorm:"column:created_at;type:datetime;not null" json:"created_at"`
	UpdatedAt                      time.Time  `gorm:"column:updated_at;type:datetime;not null" json:"updated_at"`
}

// TableName FinStatement's table name
func (*FinStatement) TableName() string {
	return TableNameFinStatement
}
