// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_model

import (
	"time"
)

const TableNameHighVolumeStockBrand = "high_volume_stock_brands"

// HighVolumeStockBrand mapped from table <high_volume_stock_brands>
type HighVolumeStockBrand struct {
	StockBrandID  string    `gorm:"column:stock_brand_id;type:char(36);primaryKey;comment:uuid" json:"stock_brand_id"`                       // uuid
	TickerSymbol  string    `gorm:"column:ticker_symbol;type:varchar(5);not null;comment:証券コード" json:"ticker_symbol"`                        // 証券コード
	VolumeAverage uint64    `gorm:"column:volume_average;type:bigint unsigned;not null;comment:一ヶ月間の出来高平均" json:"volume_average"`            // 一ヶ月間の出来高平均
	CreatedAt     time.Time `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:created_at" json:"created_at"` // created_at
}

// TableName HighVolumeStockBrand's table name
func (*HighVolumeStockBrand) TableName() string {
	return TableNameHighVolumeStockBrand
}
