// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_model

import (
	"time"
)

const TableNameMarketEvent = "market_event"

// MarketEvent mapped from table <market_event>
type MarketEvent struct {
	ID        uint64    `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:id" json:"id"`                                        // id
	EventDate time.Time `gorm:"column:event_date;type:date;not null;comment:カレンダー上に表示する日付（FOMCは結果発表の日本時間の日付）" json:"event_date"`                          // カレンダー上に表示する日付（FOMCは結果発表の日本時間の日付）
	Kind      string    `gorm:"column:kind;type:varchar(32);not null;comment:イベント種別: sq_major / sq_mini / boj / fomc / us_cpi / us_nfp" json:"kind"`      // イベント種別: sq_major / sq_mini / boj / fomc / us_cpi / us_nfp
	Label     string    `gorm:"column:label;type:varchar(64);not null;comment:表示ラベル" json:"label"`                                                        // 表示ラベル
	Source    string    `gorm:"column:source;type:varchar(32);not null;comment:取得元: jquants_calc / boj_html / fed_html / bls_ics / manual" json:"source"` // 取得元: jquants_calc / boj_html / fed_html / bls_ics / manual
	CreatedAt time.Time `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:created_at" json:"created_at"`                  // created_at
	UpdatedAt time.Time `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:updated_at" json:"updated_at"`                  // updated_at
}

// TableName MarketEvent's table name
func (*MarketEvent) TableName() string {
	return TableNameMarketEvent
}
