// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_model

import (
	"time"
)

const TableNameQuizAnswer = "quiz_answer"

// QuizAnswer mapped from table <quiz_answer>
type QuizAnswer struct {
	ID             uint64     `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	QuizDate       time.Time  `gorm:"column:quiz_date;type:date;not null;comment:クイズ対象日" json:"quiz_date"`                                     // クイズ対象日
	StockBrandID   string     `gorm:"column:stock_brand_id;type:char(36);not null;comment:stock_brand.id" json:"stock_brand_id"`               // stock_brand.id
	TickerSymbol   string     `gorm:"column:ticker_symbol;type:varchar(10);not null;comment:銘柄コード" json:"ticker_symbol"`                       // 銘柄コード
	Prediction     string     `gorm:"column:prediction;type:varchar(16);not null;comment:回答: strong_down/down/up/strong_up" json:"prediction"` // 回答: strong_down/down/up/strong_up
	AnsweredAt     time.Time  `gorm:"column:answered_at;type:datetime;not null;comment:回答日時" json:"answered_at"`                               // 回答日時
	NextClosePrice *float64   `gorm:"column:next_close_price;type:decimal(10,4);comment:翌営業日終値（採点時に確定）" json:"next_close_price"`               // 翌営業日終値（採点時に確定）
	ActualReturn   *float64   `gorm:"column:actual_return;type:decimal(12,6);comment:(翌営業日終値-基準終値)/基準終値" json:"actual_return"`                 // (翌営業日終値-基準終値)/基準終値
	Outcome        *string    `gorm:"column:outcome;type:varchar(16);comment:採点結果: correct/incorrect/draw/void" json:"outcome"`                // 採点結果: correct/incorrect/draw/void
	Score          *int32     `gorm:"column:score;type:tinyint;comment:獲得スコア +2/+1/0/-1/-2" json:"score"`                                      // 獲得スコア +2/+1/0/-1/-2
	GradedAt       *time.Time `gorm:"column:graded_at;type:datetime;comment:採点日時" json:"graded_at"`                                            // 採点日時
	CreatedAt      time.Time  `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:created_at" json:"created_at"` // created_at
	UpdatedAt      time.Time  `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:updated_at" json:"updated_at"` // updated_at
}

// TableName QuizAnswer's table name
func (*QuizAnswer) TableName() string {
	return TableNameQuizAnswer
}
