// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_model

import (
	"time"
)

const TableNameQuizDailyUniverse = "quiz_daily_universe"

// QuizDailyUniverse mapped from table <quiz_daily_universe>
type QuizDailyUniverse struct {
	QuizDate        time.Time `gorm:"column:quiz_date;type:date;primaryKey;comment:クイズ対象日（この日の終値までチャート表示、翌営業日終値を予想）" json:"quiz_date"`                  // クイズ対象日（この日の終値までチャート表示、翌営業日終値を予想）
	StockBrandID    string    `gorm:"column:stock_brand_id;type:char(36);primaryKey;comment:stock_brand.id" json:"stock_brand_id"`                      // stock_brand.id
	TickerSymbol    string    `gorm:"column:ticker_symbol;type:varchar(10);not null;comment:銘柄コード" json:"ticker_symbol"`                                // 銘柄コード
	QuestionOrder   uint32    `gorm:"column:question_order;type:int unsigned;not null;comment:出題順 1..300" json:"question_order"`                        // 出題順 1..300
	AvgTradingValue float64   `gorm:"column:avg_trading_value;type:decimal(24,4);not null;comment:直近20営業日平均売買代金 volume*close" json:"avg_trading_value"` // 直近20営業日平均売買代金 volume*close
	AvgDailyRange   float64   `gorm:"column:avg_daily_range;type:decimal(12,6);not null;comment:直近20営業日平均値幅率 (high-low)/close" json:"avg_daily_range"`  // 直近20営業日平均値幅率 (high-low)/close
	BaseClosePrice  float64   `gorm:"column:base_close_price;type:decimal(10,4);not null;comment:quiz_date終値（採点基準のスナップショット）" json:"base_close_price"`   // quiz_date終値（採点基準のスナップショット）
	CreatedAt       time.Time `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:created_at" json:"created_at"`          // created_at
	UpdatedAt       time.Time `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:updated_at" json:"updated_at"`          // updated_at
}

// TableName QuizDailyUniverse's table name
func (*QuizDailyUniverse) TableName() string {
	return TableNameQuizDailyUniverse
}
