// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_model

import (
	"time"
)

const TableNameSector17AverageDailyPrice = "sector_17_average_daily_price"

// Sector17AverageDailyPrice mapped from table <sector_17_average_daily_price>
type Sector17AverageDailyPrice struct {
	ID            string    `gorm:"column:id;type:char(36);primaryKey;comment:uuid" json:"id"`                                               // uuid
	Date          time.Time `gorm:"column:date;type:date;not null;comment:date" json:"date"`                                                 // date
	Sector33Code  *string   `gorm:"column:sector_33_code;type:varchar(4);comment:33業種コード" json:"sector_33_code"`                             // 33業種コード
	Sector17Code  *string   `gorm:"column:sector_17_code;type:varchar(4);comment:17業種コード" json:"sector_17_code"`                             // 17業種コード
	OpenPrice     float64   `gorm:"column:open_price;type:decimal(10,4);not null;comment:始値" json:"open_price"`                              // 始値
	ClosePrice    float64   `gorm:"column:close_price;type:decimal(10,4);not null;comment:終値" json:"close_price"`                            // 終値
	HighPrice     float64   `gorm:"column:high_price;type:decimal(10,4);not null;comment:高値" json:"high_price"`                              // 高値
	LowPrice      float64   `gorm:"column:low_price;type:decimal(10,4);not null;comment:安値" json:"low_price"`                                // 安値
	AdjClosePrice float64   `gorm:"column:adj_close_price;type:decimal(10,4);not null;comment:配当や株式分割を考慮した終値" json:"adj_close_price"`        // 配当や株式分割を考慮した終値
	CreatedAt     time.Time `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:created_at" json:"created_at"` // created_at
	UpdatedAt     time.Time `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:updated_at" json:"updated_at"` // updated_at
}

// TableName Sector17AverageDailyPrice's table name
func (*Sector17AverageDailyPrice) TableName() string {
	return TableNameSector17AverageDailyPrice
}
