// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameStockBrand = "stock_brand"

// StockBrand mapped from table <stock_brand>
type StockBrand struct {
	ID               string         `gorm:"column:id;type:char(36);primaryKey;default:lower(uuid());comment:uuid" json:"id"`                         // uuid
	TickerSymbol     string         `gorm:"column:ticker_symbol;type:varchar(5);not null;comment:証券コード" json:"ticker_symbol"`                        // 証券コード
	Name             string         `gorm:"column:name;type:varchar(255);not null;comment:銘柄名" json:"name"`                                          // 銘柄名
	MarketCode       string         `gorm:"column:market_code;type:varchar(255);not null;comment:市場コード" json:"market_code"`                          // 市場コード
	MarketName       string         `gorm:"column:market_name;type:varchar(255);not null;comment:市場名" json:"market_name"`                            // 市場名
	Sector33Code     *string        `gorm:"column:sector_33_code;type:varchar(4);comment:33業種コード" json:"sector_33_code"`                             // 33業種コード
	Sector33CodeName *string        `gorm:"column:sector_33_code_name;type:varchar(255);comment:33業種区分" json:"sector_33_code_name"`                  // 33業種区分
	Sector17Code     *string        `gorm:"column:sector_17_code;type:varchar(4);comment:17業種コード" json:"sector_17_code"`                             // 17業種コード
	Sector17CodeName *string        `gorm:"column:sector_17_code_name;type:varchar(255);comment:17業種区分" json:"sector_17_code_name"`                  // 17業種区分
	CreatedAt        time.Time      `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:created_at" json:"created_at"` // created_at
	UpdatedAt        time.Time      `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:updated_at" json:"updated_at"` // updated_at
	DeletedAt        gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:deleted_at" json:"deleted_at"`                                    // deleted_at
}

// TableName StockBrand's table name
func (*StockBrand) TableName() string {
	return TableNameStockBrand
}
