// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameStockBrandsDailyPrice = "stock_brands_daily_price"

// StockBrandsDailyPrice mapped from table <stock_brands_daily_price>
type StockBrandsDailyPrice struct {
	ID            string         `gorm:"column:id;type:char(36);primaryKey;comment:uuid" json:"id"`                                               // uuid
	StockBrandID  string         `gorm:"column:stock_brand_id;type:char(36);not null;comment:uuid" json:"stock_brand_id"`                         // uuid
	TickerSymbol  string         `gorm:"column:ticker_symbol;type:varchar(36);not null;comment:ticker symbol" json:"ticker_symbol"`               // ticker symbol
	Date          time.Time      `gorm:"column:date;type:date;not null;comment:date" json:"date"`                                                 // date
	OpenPrice     float64        `gorm:"column:open_price;type:decimal(10,4);not null;comment:始値" json:"open_price"`                              // 始値
	ClosePrice    float64        `gorm:"column:close_price;type:decimal(10,4);not null;comment:終値" json:"close_price"`                            // 終値
	HighPrice     float64        `gorm:"column:high_price;type:decimal(10,4);not null;comment:高値" json:"high_price"`                              // 高値
	LowPrice      float64        `gorm:"column:low_price;type:decimal(10,4);not null;comment:安値" json:"low_price"`                                // 安値
	AdjClosePrice float64        `gorm:"column:adj_close_price;type:decimal(10,4);not null;comment:配当や株式分割を考慮した終値" json:"adj_close_price"`        // 配当や株式分割を考慮した終値
	Volume        uint64         `gorm:"column:volume;type:bigint unsigned;not null;comment:出来高" json:"volume"`                                   // 出来高
	CreatedAt     time.Time      `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:created_at" json:"created_at"` // created_at
	UpdatedAt     time.Time      `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:updated_at" json:"updated_at"` // updated_at
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:deleted_at" json:"deleted_at"`                                    // deleted_at
}

// TableName StockBrandsDailyPrice's table name
func (*StockBrandsDailyPrice) TableName() string {
	return TableNameStockBrandsDailyPrice
}
