// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: stock_brand.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StockBrand represents a stock brand (銘柄)
type StockBrand struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TickerSymbol     string                 `protobuf:"bytes,2,opt,name=ticker_symbol,json=tickerSymbol,proto3" json:"ticker_symbol,omitempty"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	MarketCode       string                 `protobuf:"bytes,4,opt,name=market_code,json=marketCode,proto3" json:"market_code,omitempty"`
	MarketName       string                 `protobuf:"bytes,5,opt,name=market_name,json=marketName,proto3" json:"market_name,omitempty"`
	Sector33Code     string                 `protobuf:"bytes,6,opt,name=sector33_code,json=sector33Code,proto3" json:"sector33_code,omitempty"`
	Sector33CodeName string                 `protobuf:"bytes,7,opt,name=sector33_code_name,json=sector33CodeName,proto3" json:"sector33_code_name,omitempty"`
	Sector17Code     string                 `protobuf:"bytes,8,opt,name=sector17_code,json=sector17Code,proto3" json:"sector17_code,omitempty"`
	Sector17CodeName string                 `protobuf:"bytes,9,opt,name=sector17_code_name,json=sector17CodeName,proto3" json:"sector17_code_name,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // RFC3339
	UpdatedAt        string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // RFC3339
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StockBrand) Reset() {
	*x = StockBrand{}
	mi := &file_stock_brand_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockBrand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockBrand) ProtoMessage() {}

func (x *StockBrand) ProtoReflect() protoreflect.Message {
	mi := &file_stock_brand_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockBrand.ProtoReflect.Descriptor instead.
func (*StockBrand) Descriptor() ([]byte, []int) {
	return file_stock_brand_proto_rawDescGZIP(), []int{0}
}

func (x *StockBrand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StockBrand) GetTickerSymbol() string {
	if x != nil {
		return x.TickerSymbol
	}
	return ""
}

func (x *StockBrand) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StockBrand) GetMarketCode() string {
	if x != nil {
		return x.MarketCode
	}
	return ""
}

func (x *StockBrand) GetMarketName() string {
	if x != nil {
		return x.MarketName
	}
	return ""
}

func (x *StockBrand) GetSector33Code() string {
	if x != nil {
		return x.Sector33Code
	}
	return ""
}

func (x *StockBrand) GetSector33CodeName() string {
	if x != nil {
		return x.Sector33CodeName
	}
	return ""
}

func (x *StockBrand) GetSector17Code() string {
	if x != nil {
		return x.Sector17Code
	}
	return ""
}

func (x *StockBrand) GetSector17CodeName() string {
	if x != nil {
		return x.Sector17CodeName
	}
	return ""
}

func (x *StockBrand) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *StockBrand) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_stock_brand_proto protoreflect.FileDescriptor

const file_stock_brand_proto_rawDesc = "" +
	"\n" +
	"\x11stock_brand.proto\x12\x05stock\"\xfb\x02\n" +
	"\n" +
	"StockBrand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rticker_symbol\x18\x02 \x01(\tR\ftickerSymbol\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1f\n" +
	"\vmarket_code\x18\x04 \x01(\tR\n" +
	"marketCode\x12\x1f\n" +
	"\vmarket_name\x18\x05 \x01(\tR\n" +
	"marketName\x12#\n" +
	"\rsector33_code\x18\x06 \x01(\tR\fsector33Code\x12,\n" +
	"\x12sector33_code_name\x18\a \x01(\tR\x10sector33CodeName\x12#\n" +
	"\rsector17_code\x18\b \x01(\tR\fsector17Code\x12,\n" +
	"\x12sector17_code_name\x18\t \x01(\tR\x10sector17CodeName\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAtB2Z0github.com/Code0716/stock-price-repository/pb;pbb\x06proto3"

var (
	file_stock_brand_proto_rawDescOnce sync.Once
	file_stock_brand_proto_rawDescData []byte
)

func file_stock_brand_proto_rawDescGZIP() []byte {
	file_stock_brand_proto_rawDescOnce.Do(func() {
		file_stock_brand_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stock_brand_proto_rawDesc), len(file_stock_brand_proto_rawDesc)))
	})
	return file_stock_brand_proto_rawDescData
}

var file_stock_brand_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_stock_brand_proto_goTypes = []any{
	(*StockBrand)(nil), // 0: stock.StockBrand
}
var file_stock_brand_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_stock_brand_proto_init() }
func file_stock_brand_proto_init() {
	if File_stock_brand_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stock_brand_proto_rawDesc), len(file_stock_brand_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stock_brand_proto_goTypes,
		DependencyIndexes: file_stock_brand_proto_depIdxs,
		MessageInfos:      file_stock_brand_proto_msgTypes,
	}.Build()
	File_stock_brand_proto = out.File
	file_stock_brand_proto_goTypes = nil
	file_stock_brand_proto_depIdxs = nil
}
