// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: stock_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetHighVolumeStockBrandsRequest supports cursor-based pagination
type GetHighVolumeStockBrandsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SymbolFrom    string                 `protobuf:"bytes,1,opt,name=symbol_from,json=symbolFrom,proto3" json:"symbol_from,omitempty"` // Cursor for pagination (ticker symbol). Retrieves brands greater than this symbol.
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                            // Maximum number of records to retrieve. 0 means no limit (retrieve all).
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHighVolumeStockBrandsRequest) Reset() {
	*x = GetHighVolumeStockBrandsRequest{}
	mi := &file_stock_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHighVolumeStockBrandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHighVolumeStockBrandsRequest) ProtoMessage() {}

func (x *GetHighVolumeStockBrandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHighVolumeStockBrandsRequest.ProtoReflect.Descriptor instead.
func (*GetHighVolumeStockBrandsRequest) Descriptor() ([]byte, []int) {
	return file_stock_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetHighVolumeStockBrandsRequest) GetSymbolFrom() string {
	if x != nil {
		return x.SymbolFrom
	}
	return ""
}

func (x *GetHighVolumeStockBrandsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// GetHighVolumeStockBrandsResponse contains list of high volume stock brands with pagination info
type GetHighVolumeStockBrandsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Brands        []*HighVolumeStockBrand `protobuf:"bytes,1,rep,name=brands,proto3" json:"brands,omitempty"`
	Pagination    *PaginationInfo         `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"` // Pagination information (omitted if limit is 0)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHighVolumeStockBrandsResponse) Reset() {
	*x = GetHighVolumeStockBrandsResponse{}
	mi := &file_stock_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHighVolumeStockBrandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHighVolumeStockBrandsResponse) ProtoMessage() {}

func (x *GetHighVolumeStockBrandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stock_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHighVolumeStockBrandsResponse.ProtoReflect.Descriptor instead.
func (*GetHighVolumeStockBrandsResponse) Descriptor() ([]byte, []int) {
	return file_stock_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetHighVolumeStockBrandsResponse) GetBrands() []*HighVolumeStockBrand {
	if x != nil {
		return x.Brands
	}
	return nil
}

func (x *GetHighVolumeStockBrandsResponse) GetPagination() *PaginationInfo {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// HighVolumeStockBrand represents a stock brand with high trading volume
type HighVolumeStockBrand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StockBrandId  string                 `protobuf:"bytes,1,opt,name=stock_brand_id,json=stockBrandId,proto3" json:"stock_brand_id,omitempty"`
	TickerSymbol  string                 `protobuf:"bytes,2,opt,name=ticker_symbol,json=tickerSymbol,proto3" json:"ticker_symbol,omitempty"`
	CompanyName   string                 `protobuf:"bytes,3,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"` // Company name retrieved from stock_brand table
	VolumeAverage uint64                 `protobuf:"varint,4,opt,name=volume_average,json=volumeAverage,proto3" json:"volume_average,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // RFC3339 format (e.g., "2024-01-15T10:30:00Z")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HighVolumeStockBrand) Reset() {
	*x = HighVolumeStockBrand{}
	mi := &file_stock_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HighVolumeStockBrand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HighVolumeStockBrand) ProtoMessage() {}

func (x *HighVolumeStockBrand) ProtoReflect() protoreflect.Message {
	mi := &file_stock_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HighVolumeStockBrand.ProtoReflect.Descriptor instead.
func (*HighVolumeStockBrand) Descriptor() ([]byte, []int) {
	return file_stock_service_proto_rawDescGZIP(), []int{2}
}

func (x *HighVolumeStockBrand) GetStockBrandId() string {
	if x != nil {
		return x.StockBrandId
	}
	return ""
}

func (x *HighVolumeStockBrand) GetTickerSymbol() string {
	if x != nil {
		return x.TickerSymbol
	}
	return ""
}

func (x *HighVolumeStockBrand) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *HighVolumeStockBrand) GetVolumeAverage() uint64 {
	if x != nil {
		return x.VolumeAverage
	}
	return 0
}

func (x *HighVolumeStockBrand) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// PaginationInfo contains pagination metadata
type PaginationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextCursor    string                 `protobuf:"bytes,1,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"` // Next cursor for retrieving the next page. Empty string means this is the last page.
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                            // The limit used in the request
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationInfo) Reset() {
	*x = PaginationInfo{}
	mi := &file_stock_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationInfo) ProtoMessage() {}

func (x *PaginationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_stock_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationInfo.ProtoReflect.Descriptor instead.
func (*PaginationInfo) Descriptor() ([]byte, []int) {
	return file_stock_service_proto_rawDescGZIP(), []int{3}
}

func (x *PaginationInfo) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *PaginationInfo) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_stock_service_proto protoreflect.FileDescriptor

const file_stock_service_proto_rawDesc = "" +
	"\n" +
	"\x13stock_service.proto\x12\x05stock\"X\n" +
	"\x1fGetHighVolumeStockBrandsRequest\x12\x1f\n" +
	"\vsymbol_from\x18\x01 \x01(\tR\n" +
	"symbolFrom\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x8e\x01\n" +
	" GetHighVolumeStockBrandsResponse\x123\n" +
	"\x06brands\x18\x01 \x03(\v2\x1b.stock.HighVolumeStockBrandR\x06brands\x125\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x15.stock.PaginationInfoR\n" +
	"pagination\"\xca\x01\n" +
	"\x14HighVolumeStockBrand\x12$\n" +
	"\x0estock_brand_id\x18\x01 \x01(\tR\fstockBrandId\x12#\n" +
	"\rticker_symbol\x18\x02 \x01(\tR\ftickerSymbol\x12!\n" +
	"\fcompany_name\x18\x03 \x01(\tR\vcompanyName\x12%\n" +
	"\x0evolume_average\x18\x04 \x01(\x04R\rvolumeAverage\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"G\n" +
	"\x0ePaginationInfo\x12\x1f\n" +
	"\vnext_cursor\x18\x01 \x01(\tR\n" +
	"nextCursor\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit2{\n" +
	"\fStockService\x12k\n" +
	"\x18GetHighVolumeStockBrands\x12&.stock.GetHighVolumeStockBrandsRequest\x1a'.stock.GetHighVolumeStockBrandsResponseB2Z0github.com/Code0716/stock-price-repository/pb;pbb\x06proto3"

var (
	file_stock_service_proto_rawDescOnce sync.Once
	file_stock_service_proto_rawDescData []byte
)

func file_stock_service_proto_rawDescGZIP() []byte {
	file_stock_service_proto_rawDescOnce.Do(func() {
		file_stock_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stock_service_proto_rawDesc), len(file_stock_service_proto_rawDesc)))
	})
	return file_stock_service_proto_rawDescData
}

var file_stock_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_stock_service_proto_goTypes = []any{
	(*GetHighVolumeStockBrandsRequest)(nil),  // 0: stock.GetHighVolumeStockBrandsRequest
	(*GetHighVolumeStockBrandsResponse)(nil), // 1: stock.GetHighVolumeStockBrandsResponse
	(*HighVolumeStockBrand)(nil),             // 2: stock.HighVolumeStockBrand
	(*PaginationInfo)(nil),                   // 3: stock.PaginationInfo
}
var file_stock_service_proto_depIdxs = []int32{
	2, // 0: stock.GetHighVolumeStockBrandsResponse.brands:type_name -> stock.HighVolumeStockBrand
	3, // 1: stock.GetHighVolumeStockBrandsResponse.pagination:type_name -> stock.PaginationInfo
	0, // 2: stock.StockService.GetHighVolumeStockBrands:input_type -> stock.GetHighVolumeStockBrandsRequest
	1, // 3: stock.StockService.GetHighVolumeStockBrands:output_type -> stock.GetHighVolumeStockBrandsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_stock_service_proto_init() }
func file_stock_service_proto_init() {
	if File_stock_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stock_service_proto_rawDesc), len(file_stock_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stock_service_proto_goTypes,
		DependencyIndexes: file_stock_service_proto_depIdxs,
		MessageInfos:      file_stock_service_proto_msgTypes,
	}.Build()
	File_stock_service_proto = out.File
	file_stock_service_proto_goTypes = nil
	file_stock_service_proto_depIdxs = nil
}
