// Code generated by MockGen. DO NOT EDIT.
// Source: daily_stock_pick.go
//
// Generated by this command:
//
//	mockgen -source=daily_stock_pick.go -package=mock_database -destination=../../mock/database/daily_stock_pick.go
//

// Package mock_database is a generated GoMock package.
package mock_database
