// Code generated by MockGen. DO NOT EDIT.
// Source: daily_avoid_stock.go
//
// Generated by this command:
//
//	mockgen -source=daily_avoid_stock.go -package=mock_database -destination=../../mock/database/daily_avoid_stock.go
//

// Package mock_database is a generated GoMock package.
package mock_database
