// Code generated by MockGen. DO NOT EDIT.
// Source: dji.go
//
// Generated by this command:
//
//	mockgen -source=dji.go -package=mock_database -destination=../../mock/database/dji.go
//

// Package mock_database is a generated GoMock package.
package mock_database
