// Code generated by MockGen. DO NOT EDIT.
// Source: fin_announcement.go
//
// Generated by this command:
//
//	mockgen -source=fin_announcement.go -package=mock_database -destination=../../mock/database/fin_announcement.go
//

// Package mock_database is a generated GoMock package.
package mock_database
