// Code generated by MockGen. DO NOT EDIT.
// Source: fin_statement.go
//
// Generated by this command:
//
//	mockgen -source=fin_statement.go -package=mock_database -destination=../../mock/database/fin_statement.go
//

// Package mock_database is a generated GoMock package.
package mock_database
