// Code generated by MockGen. DO NOT EDIT.
// Source: high_volume_stock_brand.go
//
// Generated by this command:
//
//	mockgen -source=high_volume_stock_brand.go -package=mock_database -destination=../../mock/database/high_volume_stock_brand.go
//

// Package mock_database is a generated GoMock package.
package mock_database
