// Code generated by MockGen. DO NOT EDIT.
// Source: market_calendar.go
//
// Generated by this command:
//
//	mockgen -source=market_calendar.go -package=mock_database -destination=../../mock/database/market_calendar.go
//

// Package mock_database is a generated GoMock package.
package mock_database
