// Code generated by MockGen. DO NOT EDIT.
// Source: nikkei.go
//
// Generated by this command:
//
//	mockgen -source=nikkei.go -package=mock_database -destination=../../mock/database/nikkei.go
//

// Package mock_database is a generated GoMock package.
package mock_database
