// Code generated by MockGen. DO NOT EDIT.
// Source: quiz_daily_universe.go
//
// Generated by this command:
//
//	mockgen -source=quiz_daily_universe.go -package=mock_database -destination=../../mock/database/quiz_daily_universe.go
//

// Package mock_database is a generated GoMock package.
package mock_database
