// Code generated by MockGen. DO NOT EDIT.
// Source: quiz_answer.go
//
// Generated by this command:
//
//	mockgen -source=quiz_answer.go -package=mock_database -destination=../../mock/database/quiz_answer.go
//

// Package mock_database is a generated GoMock package.
package mock_database
