// Code generated by MockGen. DO NOT EDIT.
// Source: stock_brand.go
//
// Generated by this command:
//
//	mockgen -source=stock_brand.go -package=mock_database -destination=../../mock/database/stock_brand.go
//

// Package mock_database is a generated GoMock package.
package mock_database
