// Code generated by MockGen. DO NOT EDIT.
// Source: stock_brands_daily_stock_price.go
//
// Generated by this command:
//
//	mockgen -source=stock_brands_daily_stock_price.go -package=mock_database -destination=../../mock/database/stock_brands_daily_stock_price.go
//

// Package mock_database is a generated GoMock package.
package mock_database
