// Code generated by MockGen. DO NOT EDIT.
// Source: topix.go
//
// Generated by this command:
//
//	mockgen -source=topix.go -package=mock_database -destination=../../mock/database/topix.go
//

// Package mock_database is a generated GoMock package.
package mock_database
